-- TurboGear/references/dsk_type12_focus.lua
-- Display-only reference data for Anguish items used to make DSK Type 12 focus augs.
-- Generated/enriched by tools/fetch_dsk_type12_item_sources.py.
-- This file is intentionally NOT a BiS catalog list, so it will not create duplicate loot-link announce matches.
-- Enriched at: 2026-06-14 02:37:23

return {
    {
        category = "Spell Utility",
        focus = "Alacrity of the Aneuk / Ikaav",
        effect = "Spell Haste",
        items = {
            { name = "Everspring Sleeves of the Tangled Briars", slot = "Arms", id = 70889, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70889" },
            { name = "Ring of Persecution", slot = "Ring", id = 47290, source = "OMM", alla_url = "https://lazaruseq.com/alla/items/47290" },
            { name = "Earring of Dragonkin", slot = "Ear", id = 47288, source = "OMM", alla_url = "https://lazaruseq.com/alla/items/47288" },
            { name = "Glyphwielder's Sleeves of the Summoner", slot = "Arms", id = 70938, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70938" },
            { name = "Ritualchanter's Boots of the Ancestors", slot = "Feet", id = 70920, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70920" },
            { name = "Academic's Slippers of the Arcanists", slot = "Feet", id = 70934, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70934" },
            { name = "Mindreaver's Shoes of Coercion", slot = "Feet", id = 70948, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70948" },
            { name = "Dawnseeker's Boots of the Defender", slot = "Feet", id = 70871, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70871" },
            { name = "Faithbringer's Gloves of Conviction", slot = "Hands", id = 70863, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70863" },
            { name = "Everspring Mitts of the Tangled Briars", slot = "Hands", id = 70891, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70891" },
            { name = "Savagesoul Cap of the Wilds", slot = "Head", id = 70951, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70951" },
            { name = "Bladewhisper Chain Legguards of Journeys", slot = "Legs", id = 70880, source = "AMV or OOM", alla_url = "https://lazaruseq.com/alla/items/70880" },
        },
    },
    {
        category = "Spell Utility",
        focus = "Aneuk Glare / Ikaav Glare",
        effect = "Spell Range",
        items = {
            { name = "Mindreaver's Armguards of Coercion", slot = "Arms", id = 70945, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70945" },
            { name = "Duskbringer's Plate Armguards of the Hateful", slot = "Arms", id = 70882, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70882" },
            { name = "Mask of Forbidden Rites", slot = "Face", id = 47299, source = "AMV", alla_url = "https://lazaruseq.com/alla/items/47299" },
            { name = "Glyphwielder's Gloves of the Summoner", slot = "Hands", id = 70940, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70940" },
            { name = "Academic's Gloves of the Arcanists", slot = "Hands", id = 70933, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70933" },
            { name = "Dawnseeker's Mitts of the Defender", slot = "Hands", id = 70870, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70870" },
            { name = "Earring of Dark Conflict", slot = "Ear", id = 47289, source = "Jelvan", alla_url = "https://lazaruseq.com/alla/items/47289" },
            { name = "Dawnseeker's Coif of the Defender", slot = "Head", id = 11010, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/11010" },
        },
    },
    {
        category = "Spell Utility",
        focus = "Avariciousness (Aneuk / Ikaav)",
        effect = "Reduce Spell Mana Cost",
        items = {
            { name = "Dawnseeker's Sleeves of the Defender", slot = "Arms", id = 70868, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70868" },
            { name = "Plagueborn Cape", slot = "Back", id = 47306, source = "OMM", alla_url = "https://lazaruseq.com/alla/items/47306" },
            { name = "Duskbringer's Plate Helm of the Hateful", slot = "Head", id = 70881, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70881" },
            { name = "Warbeads of the Magus", slot = "Neck", id = 47276, source = "AMV", alla_url = "https://lazaruseq.com/alla/items/47276" },
            { name = "Academic's Cap of the Arcanists", slot = "Head", id = 70930, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70930" },
            { name = "Ring of Deterrence", slot = "Ring", id = 47291, source = "AMV", alla_url = "https://lazaruseq.com/alla/items/47291" },
            { name = "Chains of Anguish", slot = "Waist", id = 47282, source = "OMM", alla_url = "https://lazaruseq.com/alla/items/47282" },
        },
    },
    {
        category = "Spell Utility",
        focus = "Bulwark of the Dragorn",
        effect = "Spell Duration",
        items = {
            { name = "Faithbringer's Armguards of Conviction", slot = "Arms", id = 70861, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70861" },
            { name = "Bladewhisper Chain Sleeves of Journeys", slot = "Arms", id = 70875, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70875" },
            { name = "Ring of the Beast", slot = "Ring", id = 47292, source = "Hanvar", alla_url = "https://lazaruseq.com/alla/items/47292" },
            { name = "Amice of Ill-Will", slot = "Shoulder", id = 47280, source = "AMV", alla_url = "https://lazaruseq.com/alla/items/47280" },
            { name = "Everspring Wristband of the Tangled Briars", slot = "Wrist", id = 70890, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70890" },
        },
    },
    {
        category = "Spell Utility",
        focus = "Vindication of the Dragorn",
        effect = "Spell Duration",
        items = {
            { name = "Ritualchanter's Leggings of the Ancestors", slot = "Legs", id = 70922, source = "AMV or OOM", alla_url = "https://lazaruseq.com/alla/items/70922" },
            { name = "Cloak of Wailing Woes", slot = "Back", id = 47303, source = "Jelvan", alla_url = "https://lazaruseq.com/alla/items/47303" },
            { name = "Necklace of the Steadfast Spirit", slot = "Neck", id = 47275, source = "OMM", alla_url = "https://lazaruseq.com/alla/items/47275" },
            { name = "Belt of the Stagnant", slot = "Waist", id = 47284, source = "Hanvar", alla_url = "https://lazaruseq.com/alla/items/47284" },
            { name = "Blightbringer's Bracer of the Grave", slot = "Wrist", id = 70925, source = "Armor Quest", alla_url = "https://lazaruseq.com/alla/items/70925" },
            { name = "Duskbringer's Plate Wristguard of the Hateful", slot = "Wrist", id = 70883, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70883" },
        },
    },
    {
        category = "Healing / Pet",
        focus = "Blessing of Anguish",
        effect = "Healing",
        items = {
            { name = "Ritualchanter's Armguards of the Ancestors", slot = "Arms", id = 70917, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70917" },
            { name = "Everspring Slippers of the Tangled Briars", slot = "Feet", id = 70892, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70892" },
            { name = "Bladewhisper Chain Boots of Journeys", slot = "Feet", id = 70878, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70878" },
            { name = "Faithbringer's Leggings of Conviction", slot = "Legs", id = 70866, source = "AMV or OOM", alla_url = "https://lazaruseq.com/alla/items/70866" },
            { name = "Dawnseeker's Leggings of the Defender", slot = "Legs", id = 70873, source = "AMV or OOM", alla_url = "https://lazaruseq.com/alla/items/70873" },
            { name = "Savagesoul Wristband of the Wilds", slot = "Wrist", id = 70953, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70953" },
            { name = "Ring of Disdain", slot = "Ring", id = 47293, source = "Ture", alla_url = "https://lazaruseq.com/alla/items/47293" },
        },
    },
    {
        category = "Healing / Pet",
        focus = "Keeper's Blessing",
        effect = "Pet Heals",
        items = {
            { name = "Globe of Voltage", slot = "Range", id = 47298, source = "Jelvan", alla_url = "https://lazaruseq.com/alla/items/47298" },
            { name = "Blightbringer's Armband of the Grave", slot = "Arms", id = 70924, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70924" },
            { name = "Glyphwielder's Wristband of the Summoner", slot = "Wrist", id = 70939, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70939" },
        },
    },
    {
        category = "Melee / Physical",
        focus = "Cleave V",
        effect = "Crit Chance",
        items = {
            { name = "Savagesoul Sleeves of the Wilds", slot = "Arms", id = 70952, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70952" },
            { name = "Golem Stone Face Guard", slot = "Face", id = 47301, source = "Ture", alla_url = "https://lazaruseq.com/alla/items/47301" },
            { name = "Wrathbringer's Chain Boots of the Vindicator", slot = "Feet", id = 70962, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70962" },
            { name = "Whispering Boots of Shadows", slot = "Feet", id = 70913, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70913" },
            { name = "Gladiator's Plate Gloves of War", slot = "Hands", id = 70856, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70856" },
            { name = "Farseeker's Plate Gloves of Harmony", slot = "Hands", id = 70905, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70905" },
        },
    },
    {
        category = "Melee / Physical",
        focus = "Ferocity V",
        effect = "Double/Triple Attack/Chance To Hit",
        items = {
            { name = "Shoulderpads of Warfare", slot = "Shoulder", id = 47279, source = "Hanvar", alla_url = "https://lazaruseq.com/alla/items/47279" },
            { name = "Gladiator's Plate Boots of War", slot = "Feet", id = 70857, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70857" },
            { name = "Farseeker's Plate Legguards of Harmony", slot = "Legs", id = 70908, source = "AMV or OOM", alla_url = "https://lazaruseq.com/alla/items/70908" },
        },
    },
    {
        category = "Melee / Physical",
        focus = "Improved Dodge V",
        effect = "Dodge",
        items = {
            { name = "Faithbringer's Boots of Conviction", slot = "Feet", id = 70864, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70864" },
            { name = "Fiercehand Leggings of the Focused", slot = "Legs", id = 70901, source = "AMV or OOM", alla_url = "https://lazaruseq.com/alla/items/70901" },
            { name = "Whispering Pants of Shadows", slot = "Legs", id = 70915, source = "AMV or OOM", alla_url = "https://lazaruseq.com/alla/items/70915" },
            { name = "Savagesoul Legguards of the Wilds", slot = "Legs", id = 70957, source = "AMV or OOM", alla_url = "https://lazaruseq.com/alla/items/70957" },
            { name = "Shroud of Eternal Agony", slot = "Shoulder", id = 47278, source = "OMM", alla_url = "https://lazaruseq.com/alla/items/47278" },
        },
    },
    {
        category = "Melee / Physical",
        focus = "Improved Parry/Block V",
        effect = "Parry/Block",
        items = {
            { name = "Fiercehand Tabis of the Focused", slot = "Feet", id = 70899, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70899" },
            { name = "Bladewhisper Chain Gloves of Journeys", slot = "Hands", id = 70877, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70877" },
            { name = "Savagesoul Gloves of the Wilds", slot = "Hands", id = 70954, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70954" },
            { name = "Choker of Imprisoned Visions", slot = "Neck", id = 47274, source = "Keldovan", alla_url = "https://lazaruseq.com/alla/items/47274" },
        },
    },
    {
        category = "Melee / Physical",
        focus = "Sharpshooting V",
        effect = "Archery/Throwing",
        items = {
            { name = "Rigid Ring of Prowess", slot = "Ring", id = 47294, source = "Keldovan", alla_url = "https://lazaruseq.com/alla/items/47294" },
            { name = "Wrathbringer's Chain Sleeves of the Vindicator", slot = "Arms", id = 70959, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70959" },
            { name = "Bladewhisper Chain Wristband of Journeys", slot = "Wrist", id = 70876, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70876" },
        },
    },
    {
        category = "Caster Damage",
        focus = "Fire of Anguish",
        effect = "Fire Damage",
        items = {
            { name = "Stud of Chilling Precision", slot = "Ear", id = 47285, source = "Keldovan", alla_url = "https://lazaruseq.com/alla/items/47285" },
            { name = "Glyphwielder's Leggings of the Summoner", slot = "Legs", id = 70943, source = "AMV or OOM", alla_url = "https://lazaruseq.com/alla/items/70943" },
        },
    },
    {
        category = "Caster Damage",
        focus = "Frost of Anguish",
        effect = "Ice Damage",
        items = {
            { name = "Cloak of Regretful Transgressions", slot = "Back", id = 47304, source = "Hanvar", alla_url = "https://lazaruseq.com/alla/items/47304" },
            { name = "Ritualchanter's Mitts of the Ancestors", slot = "Hands", id = 70919, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70919" },
            { name = "Everspring Pants of the Tangled Briars", slot = "Legs", id = 70894, source = "AMV or OOM", alla_url = "https://lazaruseq.com/alla/items/70894" },
            { name = "Academic's Pants of the Arcanists", slot = "Legs", id = 70936, source = "AMV or OOM", alla_url = "https://lazaruseq.com/alla/items/70936" },
        },
    },
    {
        category = "Caster Damage",
        focus = "Plague of Anguish",
        effect = "Disease Damage",
        items = {
            { name = "Duskbringer's Plate Legguards of the Hateful", slot = "Legs", id = 70887, source = "AMV or OOM", alla_url = "https://lazaruseq.com/alla/items/70887" },
            { name = "Belt of Contempt", slot = "Waist", id = 47281, source = "Ture", alla_url = "https://lazaruseq.com/alla/items/47281" },
        },
    },
    {
        category = "Caster Damage",
        focus = "Thunder of Anguish",
        effect = "Magic Damage",
        items = {
            { name = "Aegis of the Dragorn Elders", slot = "Secondary", id = 47311, source = "Ture", alla_url = "https://lazaruseq.com/alla/items/47311" },
            { name = "Academic's Sleeves of the Arcanists", slot = "Arms", id = 70931, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70931" },
            { name = "Duskbringer's Plate Boots of the Hateful", slot = "Feet", id = 70885, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70885" },
            { name = "Blightbringer's Handguards of the Grave", slot = "Hands", id = 70926, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70926" },
            { name = "Bladewhisper Chain Cap of Journeys", slot = "Head", id = 70874, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70874" },
            { name = "Mindreaver's Leggings of Coercion", slot = "Legs", id = 70950, source = "AMV or OOM", alla_url = "https://lazaruseq.com/alla/items/70950" },
            { name = "Symbol of the Overlord", slot = "Range", id = 47295, source = "OMM", alla_url = "https://lazaruseq.com/alla/items/47295" },
            { name = "Dawnseeker's Wristguard of the Defender", slot = "Wrist", id = 70869, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70869" },
        },
    },
    {
        category = "Caster Damage",
        focus = "Venom of Anguish",
        effect = "Poison Damage",
        items = {
            { name = "Beaded Hoop of Demise", slot = "Ear", id = 47287, source = "AMV", alla_url = "https://lazaruseq.com/alla/items/47287" },
            { name = "Duskbringer's Plate Gloves of the Hateful", slot = "Hands", id = 70884, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70884" },
            { name = "Blightbringer's Pants of the Grave", slot = "Legs", id = 70929, source = "AMV or OOM", alla_url = "https://lazaruseq.com/alla/items/70929" },
            { name = "Ritualchanter's Wristband of the Ancestors", slot = "Wrist", id = 70918, source = "First Four Names", alla_url = "https://lazaruseq.com/alla/items/70918" },
        },
    },
}
