[Pack]
name=Epic and starter quest items
description=class epic quest and starter quest items

[ItemLimits]
; BARD
Dragorn Blood=KEEP
Bubonian Blood=KEEP
Alkaline Etched Stone=KEEP
Metallic Liquid=KEEP
Cracked Dragon Bone=KEEP
Black Chaos Breastplate=1
Black Chaos Gauntlets=1
Black Chaos Boots=1
; CLERIC
Akhevan Brain Stem=KEEP
Shissar Cerebral Cortex=KEEP
Tattered Quarter of a Map=KEEP
Shredded Quarter of a Map=KEEP
Ripped Quarter of a Map=KEEP
Torn Quarter of a Map=KEEP
Bazu Plasma=KEEP
; ROGUE skillups
Asmag Weed=Keep
Concentrated Grade A Nigriventer Venom=Keep
Concentrated Grade AA Nigriventer Venom=Keep
Crystalline Serum=Keep
Embalming Dust=Keep
Fresh Muscimol=Keep
Fresh Oleander=Keep
Mt. Death Mineral Salts=Keep
Ovate Jellyfish=Keep
Phosphorous Powder=Keep
Refined Grade A Gormar Venom=Keep
Refined Grade A Nigriventer Venom=Keep
Tainted Planar Essence=Keep
Venomous Secretions=Keep
; SHAMAN
Corruption Powder=KEEP
Corrosive Goo=KEEP
Perfect Marked Ukun Skin=KEEP
Revenant Tooth=KEEP
; PALADIN
Dark Skeleton Remains=1
;========================================================
; PoK booze quest (5 for the quest, tribute after)
;========================================================
Classic White Alvarinho=5
Velious Blue Vindigo=5
Planar Red Shiraz=5
Kunark Green Pinot Gris=5
Luclin Purple Merlot=5