[Pack]
name=GoD list
description=LOOK BEFORE USING - Gates of Discord items

[ItemLimits]
;========================================================
; *** GATES OF DISCORD ***
;========================================================

;========================================================
; GOD SPELL/HANDINS (KEEP)
;========================================================
Taelosian Geomancy Stone Eril=KEEP
Taelosian Geomancy Stone Jelki=KEEP
Taelosian Geomancy Stone Yiktu=KEEP
Chaos Runes=KEEP

;========================================================
; GOD TXEVU (SYMBOLS)
;========================================================
;------------------
; Txevu Tribute Items
;------------------
Dark Chain Circlet=tribute
Great Maul of the Mighty=tribute
Ixt Bone Scepter=tribute
Ruby of Steadfastness=tribute
Dark Chain Circlet=tribute
Gem of Peace=tribute
Jagged Blade of Ice=tribute
Sapphire of Capricious Magic=tribute
;------------------
; Ukun Bloodfeaster
;------------------
Carved Bone Gauntlets=1
Cloak of the Penumbra=1
Golden Half Mask of Convalescence=1
Hardened Bone Spike=1
Skullcap of Contemplation=1
Ukun-Hide Armplates of Mortification=1
Woven Chain Boots of Strife=1
;------------------
; Ixt Hsek Syat (arena)
;------------------
Chain Wraps of the Dark Master=1
Earring of Incessant Conflict=1
Forlorn Mantle of Shadows=1
Halberd of Endless Pain=1
Shadowy Coif of Condemnation=1
Sleeves of Cognitive Resonance=1
Stained Fur Mask=1
Steel Boots of the Slayer=1
;------------------
; High Priest Nkosi Bakari
;------------------
Barrier of Serenity=1
Bow of the Whispering Wind=1
Bulwark of Living Stone=1
Caduceus of Retribution=1
Jade Effigy of Trushar=1
Lute of False Worship=1
Mask of Eternity=1
Ring of Celestial Harmony=1
Staff of Revealed Secrets=1
Verge of the Mindless Servant=1
;------------------
; Ikaav Nysf Lleiv
;------------------
Armguards of Envy=1
Bloodfire Cabochon=1
Crown of the Forsaken=1
Earring of the Starless Night=1
Scepter of Forbidden Knowledge=1
Silken Slippers of Discordant Magic=1
Staff of Shattered Dreams=1
Suede Gloves of Creation=1
;------------------
; Ancient Cragbeast Matriarch
;------------------
Azure Trinket of Despair=1
Flayed-Skin Spiked Boots=1
Globe of Dancing Light=1
Hardened Scale Vambraces=1
Headband of the Endless Night=1
Lizard Skin Wardrums=1
Shroud of Pandemonium=1
Silken Gloves of the Chaos=1
;------------------
; Zun`Muram Tkarish Zyk
;------------------
Aegis of Discord=1
Band of Solid Shadow=1
Blackstone Figurine=1
Cape of Woven Steel=1
Edge of Chaos=1
Gem-Studded Band of Struggle=1
Gemstone of Dark Flame=1
Kaftan of Embroidered Light=1
Longsword of Execration=1
Muramite's Heavy Shackles=1
Shroud of Ceaseless Might=1
Spiked Steel Baton=1
Wristband of Chaotic Warfare=1

;========================================================
; GOD TACVI (SYMBOLS)
;========================================================
;------------------
; Pixtt Xxeric Kex
;------------------
Bracer of Grievous Harm=1
Glinting Onyx of Might=1
Glyphed Sandstone of Idealism=1
Ragestone of Hateful Thoughts=1
Shimmering Granite=1
Wristguard of Chaotic Essence=1
Xxeric's Battleworn Bracer=1
Xxeric's Warbraid=1
;------------------
; Pixtt Kretv Krakxt
;------------------
Bulwark of Lost Souls=1
Death's Head Mace=1
Earring of Pain Deliverance=1
Golden Idol of Destruction=1
Ring of Organic Darkness=1
Sleeves of Malefic Rapture=1
Vambraces of Eternal Twilight=1
;------------------
; Pixtt Riel Tavas
;------------------
Aegis of Midnight=1
Armband of Writhing Shadow=1
Armguards of Insidious Corruption=1
Mask of the Void=1
Ring of the Serpent=1
Ruby of Determined Assault=1
Tome of Discordant Magic=1
;------------------
; Zun`Muram Shaldn Boc
;------------------
Gloves of Wicked Ambition=1
Hammer of Delusions=1
Kelp-Covered Hammer=1
Loop of Entropic Hues=1
Mantle of Corruption=1
Mindreaper Club=1
Supple Slippers of the Stargazer=1
Zun'Muram's Scepter of Chaos=1
;------------------
; Zun`Muram Mordl Delt
;------------------
Blade of Natural Turmoil=1
Cloak of Nightmarish Visions=1
Dagger of Evil Summons=1
Jagged Axe of Uncontrolled Rage=1
Nightmarish Boots of Conflict=1
Runed Gauntlets of the Void=1
Shroud of the Legion=1
Zun'Muram's Spear of Doom=1
;------------------
; Zun`Muram Yihst Vor
;------------------
Boots of Captive Screams=1
Dagger of Death=1
Deathblade of the Zun'Muram=1
Discordant Dagger of Night=1
Gloves of Coalesced Flame=1
Pendant of Discord=1
Rapier of Somber Notes=1
Xxeric's Matted-Fur Mask=1
;------------------
; Zun`Muram Kvxe Pirik
;------------------
Bloodstone Blade of the Zun'Muram=1
Brutish Blade of Balance=1
Gauntlets of Malicious Intent=1
Girdle of the Zun'Muram=1
Luxurious Satin Slippers=1
Pauldron of Dark Auspices=1
Scepter of Incantations=1
Weighted Hammer of Conviction=1
;------------------
; Tunat`Muram Cuu Vauax
;------------------
Blade Warstone=1
Dark Tunic of the Enslavers=1
Drape of the Merciless Slaver=1
Greaves of the Dark Ritualist=1
Greaves of the Tunat'Muram=1
Jagged Glowing Prism=1
Lightning Prism of Swordplay=1
Merciless Enslaver's Britches=1
Solid Stone of the Iron Fist=1
Tunat'Muram's Bloodied Greaves=1
Tunat'Muram's Chainmail of Pain=1
Tunat'Muram's Chestplate of Agony=1
Worked Granite of Sundering=1

;========================================================
; GOD TS ITEMS
;========================================================
Aged Muramite Etched Scales=BANK
Chunk of Broken Ancient Stone Worker=BANK
Chunk of Discordian Rock=BANK
Dark Chain Circlet=BANK
Fine Laburnum=BANK
Fine Larkspur=BANK
Fine Privit=BANK
Flake of Loadstone=BANK
Fresh Delphinium=BANK
Meldstone=BANK
Muramite Bile Sack=BANK
Quality Laburnum=BANK
Raw Infused Dark Matter=BANK
Refined Grade AA Taipan Venom=BANK
Sample of Highland Sludge=BANK
Shimmering Aligned Ore=BANK
Taelosian Mountain Tea Leaves=BANK
Taelosian Mountain Wheat=BANK

;========================================================
;  GOD MURAMITE ARMOR
;========================================================
Muramite Boot Armor=KEEP
Muramite Bracer Armor=KEEP
Muramite Chest Armor=KEEP
Muramite Greaves Armor=KEEP
Muramite Helm Armor=KEEP
Muramite Sleeve Armor=KEEP

;========================================================
; GOD Destroy
;========================================================
Cracked Noc Hoof=DESTROY
Severed Ikaav head=DESTROY
Trusik Blood=DESTROY
Mangled Trusik Flesh=DESTROY
First Fragment of the Left Eye=DESTROY
Second Fragment of the Left Eye=DESTROY
Third Fragment of the Left Eye=DESTROY
Fourth Fragment of the Left Eye=DESTROY
Fifth Fragment of the Left Eye=DESTROY
Sixth Fragment of the Left Eye=DESTROY