[Pack]
name=Anguish and OoW items
description=armor quest mats, muramite runes, etc

[ItemLimits]
;========================================================
; *** OMENS OF WAR ***
;========================================================

;========================================================
; OOW MISC ITEMS (SELL) - (Dranik CataCombs)
;========================================================
Broken Ukun Leash=SELL
Congealed Bat Blood=SELL
Cracked Stone Eye=SELL
Curled Rat Foot=SELL
Dragorn Claw=SELL
Dragorn Eye=SELL
Dragorn Fang=SELL
Dragorn Wing Bones=SELL
Gnarled Rat Tail=SELL
Murkglider Sinew=SELL
Murkglider Stomach=SELL
Noc Claw=SELL
Noc Heart=SELL
Shattered Bat Fang=SELL
Shattered Visage=SELL
Shimmering Ukun Hide=SELL
Sleek Bat Fur=SELL
Sparkling Lightning Spike=SELL
Sparse Rat Fur=SELL
Splintered Bone Necklace=SELL
Starflow Stone=SELL
Stone Shard=SELL
Tattered Ikaav Braid=SELL
Torn Rat Ear=SELL
Ukun Guts=SELL
Wiry Rat Whiskers=SELL

;========================================================
; OOW SPELL/HANDINS (KEEP)
;========================================================
;Ancient Muramite Rune=KEEP
Glowing Muramite Rune=KEEP
Greater Muramite Rune=KEEP
Lesser Muramite Rune=KEEP
Minor Muramite Rune=KEEP
Muramite Rune=KEEP

;========================================================
; OOW MISC
;=======================================================
;Chamber of Celestial Creation=
;Chamber of the Crushing Void=
;Dragorn Silver Broadsword=
;Dragorn Greatstaff=

;========================================================
; OOW ANGUISH CHAIN (ARMOR MATS)
;========================================================
Dragorn Muramite Ring=KEEP
Ikaav Head=KEEP
Kyv Scout Ring=KEEP
Kyv Short Bow=KEEP
Kyv Whetstone=KEEP
Shattered Ukun Hide=KEEP
Withered Discordling Tongue=KEEP

;========================================================
; OOW ANGUISH CLOTH (ARMOR MATS)
;========================================================
Bar of Nashtar Berry Soap=KEEP
Ikaav Tail=KEEP
Kuuan Whetstone=KEEP
Piece of Vrenlar Fruit=KEEP
Riftseeker Trinket=KEEP
Softened Feran Hide=KEEP
Spool of Balemoon Silk=KEEP

;========================================================
; OOW ANGUISH LEATHER (ARMOR MATS)
;========================================================
Bazu Nail Bracelet=KEEP
Chimera Gut String=KEEP
Discordling Hoof=KEEP
Fine Chimera Hide=KEEP
Muramite Noble's March Award=KEEP
Quality Feran Hide=KEEP
Spiked Discordling Collar=KEEP

;========================================================
; OOW ANGUISH PLATE (ARMOR MATS)
;========================================================
Blackened Discordling Tail=KEEP
Ceremonial Dragorn Candle=KEEP
Crystal of Yearning=KEEP
Kyv Food Sack=KEEP
Kyv Hunter Ring=KEEP
Large Piece of Kuuan Ore=KEEP
Noc Right Hand=KEEP

;========================================================
; OOW Magnetized Drops
;========================================================
Gashed Magnetized Breastplate=KEEP
Bent Magnetized Pauldron=KEEP
Dented Magnetized Helm=KEEP
Smashed Magnetized Boots=KEEP
Twisted Magnetized Belt=KEEP
Mirrored Mask=IGNORE
Cracked Magnetized Bracer=KEEP
Mangled Magnetized Leggings=KEEP
Splitnered Magnetized Vambraces=KEEP