[Pack]
name=pop list
description=LOOK BEFORE USING - Planes of Power items

[ItemLimits]
;========================================================
; POP SPELL/HANDINS (KEEP)
;========================================================
Spectral Parchment=KEEP
Ethereal Parchment=KEEP
Glyphed Rune Word=KEEP

;========================================================
; PLANES OF POWER (KEEP)
;========================================================
Air Mephit Blood=KEEP
Fire Mephit Blood=KEEP
Earth Mephit Blood=KEEP
Water Mephit Blood=KEEP

;========================================================
; PLANES OF POWER ARMOR DROPS (TRIBUTE)
;========================================================
Elemental Boot Mold=TRIBUTE
Elemental Bracer Mold=TRIBUTE
Elemental Chain Boot Pattern=TRIBUTE
Elemental Chain Bracelet Pattern=TRIBUTE
Elemental Chain Coif Pattern=TRIBUTE
Elemental Chain Glove Pattern=TRIBUTE
Elemental Chain Pant Pattern=TRIBUTE
Elemental Chain Sleeve Pattern=TRIBUTE
Elemental Gauntlet Mold=TRIBUTE
Elemental Greaves Mold=TRIBUTE
Elemental Helm Mold=TRIBUTE
Elemental Leather Boot Pattern=TRIBUTE
Elemental Leather Glove Pattern=TRIBUTE
Elemental Leather Helm Pattern=TRIBUTE
Elemental Leather Pant Pattern=TRIBUTE
Elemental Leather Sleeve Pattern=TRIBUTE
Elemental Leather Wrist Pattern=TRIBUTE
Elemental Silk Boot Pattern=TRIBUTE
Elemental Silk Bracelet Pattern=TRIBUTE
Elemental Silk Glove Pattern=TRIBUTE
Elemental Silk Pant Pattern=TRIBUTE
Elemental Silk Sleeve Pattern=TRIBUTE
Elemental Silk Turban Pattern=TRIBUTE
Elemental Vambrace Mold=TRIBUTE

;========================================================
; PLANES OF POWER (DESTROY)
;========================================================
Air Arachnid Silk=DESTROY
Air Mephit Skin=DESTROY
Chunk of Wind Metal=DESTROY
Earth Mephit Skin=DESTROY
Elemental Stone=DESTROY
Emerald Colored Mephit Scales=DESTROY
Fresh Caladium=DESTROY
Fresh Privit=DESTROY
Gemmed Fin=DESTROY
Globe of Pure Air=DESTROY
Liquified Earth=DESTROY
Living Fragment of Air=DESTROY
Living Fragment of Earth=DESTROY
Mephit Meat=DESTROY
Multifaceted eye=DESTROY
Phoenix Egg=DESTROY
Prestidigitase=DESTROY
Prismatic Feather=DESTROY
Quality Oleander=DESTROY
Root Entwined Chunk of Dirt=DESTROY
Shattered Crystal=DESTROY
Shimmering Fish Gills=DESTROY
Tainted Planar Essence=DESTROY
Triloun Meat=DESTROY
Twilight Worms=DESTROY
Water Mephit Skin=DESTROY
Wax Flower=DESTROY

;========================================================
; PLANE OF TIME (those marked TRIBUTE are for tribute, 
; ----- those marked 1 are for symbols, ALL for Symbol of Nightmare)
;========================================================

;========================================================
; -----  Plane of Time Raid - Phase 1 (TRIBUTE)
;========================================================
Mask of Conceptual Energy=TRIBUTE
Pulsing Emerald Hoop=TRIBUTE
Ring of Force=TRIBUTE
Smooth Onyx Torque=TRIBUTE
Wristguard of Keen Vision=TRIBUTE

;========================================================
; -----  Plane of Time Raid - Phase 2 (TRIBUTE)
;========================================================
Cloak of Ferocity=TRIBUTE
Cudgel of Wrecking=TRIBUTE
Drape of the Unending=TRIBUTE
Gauntlets of Disruption=TRIBUTE
Girdle of Restoration=TRIBUTE
Glowing Chains=TRIBUTE
Hoop of the Enlightened=TRIBUTE
Shield of the Vortex=TRIBUTE
Tiny Jade Ring=TRIBUTE
Veil of Warmth=TRIBUTE
Wand of the Vortex=TRIBUTE

;========================================================
; -----  Plane of Time Raid - Phase 3 (TRIBUTE)
;========================================================
Cloak of Wishes=TRIBUTE
Dagger of Distraction=TRIBUTE
Necklace of Celestial Energy=TRIBUTE
Ossein of Limitless Time=TRIBUTE
Protective Sleeves=TRIBUTE
Time Phased Quintessence=DESTROY
Time Traveler's Abandoned Notebook=TRIBUTE

;========================================================
; -----  Plane of Time Raid - Phase 3 (SYMBOLS)
; The Supernatural Guardian and Avatar of the Elements
;========================================================
Earring of Xaoth Kor=1
Ethereal Destroyer=1
Faceguard of Frenzy=1
Fiery Crystal Guard=1
Mask of Strategic Insight=1
Pauldrons of Purity=1
Timeless Coral Greatsword=1

;========================================================
; -----  Plane of Time Raid - Phase 4 - Saryrn (SYMBOLS)
;========================================================
Cap of Flowing Time=1
Edge of Eternity=1
Girdle of Intense Durability=1
Gloves of the Unseen=1
Ring of Evasion=1
Runewarded Belt=1
Shroud of Provocation=1
Symbol of the Planemasters=1
Time's Antithesis=1
Veil of Lost Hopes=1

;========================================================
; -----  Plane of Time Raid - Phase 4 - Tallon Zek   (SYMBOLS)
;========================================================
Amulet of Crystal Dreams=1
Band of Prismatic Focus=1
Bracer of Precision=1
Circlet of Flowing Time=1
Cloak of the Falling Skies=1
Hopebringer=1
Mantle of Deadly Precision=1
Serpent of Vindication=1
Tactician's Shield=1
Winged Storm Boots=1

;========================================================
; -----  Plane of Time Raid - Phase 4 - Vallon Zek (SYMBOLS)
;========================================================
Bow of the Tempest=1
Cord of Potential=1
Earring of Temporal Solstice=1
Globe of Mystical Protection=1
Hammer of Holy Vengeance=1
Helm of Flowing Time=1
Shinai of the Ancients=1
Shoes of Fleeting Fury=1
Temporal Chainmail Sleeves=1
Wand of Temporal Power=1

;========================================================
; -----  Plane of Time Raid - Phase 4 - Terris Thule (SYMBOLS)
;========================================================
Armguards of the Brute=1
Cape of Endless Torment=1
Coif of Flowing Time=1
Cudgel of Venomous Hatred=1
Earring of Corporeal Essence=1
Hammer of Hours=1
Orb of Clinging Death=1
Talisman of Tainted Energy=1
Vanazir, Dreamer's Despair=1
Symbol of Nightmare=KEEP

;========================================================
; -----  Plane of Time Raid - Phase 5 - Bertoxxulous (SYMBOLS)
;========================================================
Belt of Temporal Bindings=1
Boots of Despair=1
Celestial Cloak=1
Collar of Catastrophe=1
Eye of Dreams=1
Greatblade of Chaos=1
Leggings of Furious Might=1
Pulsing Onyx Ring=1
Symbol of Ancient Summoning=1
Timeless Leather Tunic Pattern=1
Timespinner, Blade of the Hunter=1
Veil of the Inferno=1

;========================================================
; -----  Plane of Time Raid - Phase 5 - Cazic Thule (SYMBOLS)
;========================================================
Belt of Tidal Energy=1
Cloak of Retribution=1
Earring of Unseen Horrors=1
Greaves of Furious Might=1
Mask of Simplicity=1
Padded Tigerskin Gloves=1
Staff of Transcendence=1
Timeless Silk Robe Pattern=1
Timestone Adorned Ring=1
Wand of Impenetrable Force=1
Wristband of Echoed Thoughts=1
Zealot's Spiked Bracer=1

;========================================================
; -----  Plane of Time Raid - Phase 5 - Innoruuk (SYMBOLS)
;========================================================
Barrier of Freezing Winds=1
Bracer of Timeless Rage=1
Earring of Celestial Energy=1
Girdle of Stability=1
Gloves of Airy Mists=1
Jagged Timeforged Blade=1
Mantle of Pure Spirit=1
Necklace of Eternal Visions=1
Serrated Dart of Energy=1
Shroud of Survival=1
Songblade of the Eternal=1
Timeless Chain Tunic Pattern=1

;========================================================
; -----  Plane of Time Raid - Phase 5 - Rallos Zek (SYMBOLS)
;========================================================
Band of Primordial Energy=1
Darkblade of the Warlord=1
Greatstaff of Power=1
Pants of Furious Might=1
Pauldrons of Devastation=1
Platinum Cloak of War=1
Ring of Thunderous Forces=1
Sandals of Empowerment=1
Shield of Strife=1
Timeless Breastplate Mold=1
Ton Po's Mystical Pouch=1
Visor of the Berserker=1

;========================================================
; -----  Plane of Time Raid - Phase 6 - Quarm (SYMBOLS)
;========================================================
Bracer of the Inferno=1
Cord of Temporal Weavings=1
Earring of Influxed Gravity=1
Earthen Bracer of Fortitude=1
Ethereal Silk Leggings=1
Hammer of the Timeweaver=1
Prismatic Ring of Resistance=1
Shawl of Eternal Forces=1
Shroud of Eternity=1
Silver Hoop of Speed=1
Spool of Woven Time=1
Stone of Flowing Time=1
Talisman of the Elements=1
Timeless Breastplate Mold=1
Timeless Chain Tunic Pattern=1
Timeless Leather Tunic Pattern=1
Timeless Silk Robe Pattern=1
Whorl of Unnatural Forces=1
Wristband of Icy Vengeance=1