[Pack]
name=Project Lazarus items
description=server specific items from Project Lazarus

[ItemLimits]
A Lucky Ticket=KEEP
A Placid Void=KEEP
A Radiant Morsel=KEEP
Celestial Blessing of the Djinn=KEEP
Celestial Coffer=KEEP
Celestial Crest=KEEP
Diamond Coin=KEEP
Elemental Forging Temper=KEEP
Formless Blade=KEEP
Foul Smelling Liquid=KEEP
Gold Coin=KEEP
Lucky Coin=KEEP
Melodic Materium=KEEP
;Mycelium of Mimicry=1 needed per initial fungal aug upgrade
;Research Jar=25
Shattered Ornate Insignia=KEEP
Stolen Dragorn Clan Insignia=KEEP
Stuffed Christmas Stocking=KEEP
;----
Glimmering Coin=SELL
Resplendent Coin=SELL
Tarnished Coin=SELL
;----
Upper Runic Fragment=1
Center Runic Fragment=1
Lower Runic Fragment=1
;========================================================
; STAT FOOD - (KEEP) 
;========================================================
Armored Starfish Skewers=KEEP
Bamboo Defender Margarita=KEEP
Hunter's Meat and Taters=KEEP
Stalker's Spirit Slush=KEEP
Sleek Spring Roll Sampler=KEEP
Darting Dragonroot Daiquiri=KEEP
Sorcerer's Spice Chicken=KEEP
Arcane Ambrosia Daiquiri=KEEP
Inferno Fin Sizzle=KEEP
Pyroberry Tart Smoothie=KEEP
Frozen Tundra Stew=KEEP
Frostberry Chill=KEEP
Toxic Tangleberry Tarts=KEEP
Lethal Nightshade Colada=KEEP
Pestilent Plague Pie=KEEP
Infected Mushroom Cooler=KEEP
Stampede Satay Sticks=KEEP
Thundering Tamarind Tango=KEEP
;========================================================
; POTIONS
;========================================================
Distillate of Antidote VI=KEEP
Distillate of Celestial Healing X=KEEP
Distillate of Celestial Healing XI=KEEP
Distillate of Divine Healing X=KEEP
Distillate of Divine Healing XI=KEEP
Distillate of Immunization VI=KEEP
Draught of Earthen Grit I=KEEP
Draught of Opulent Healing I=KEEP
Draught of Fleeting Fortitude I=KEEP
Draught of Frenzied Endurance I=KEEP
Draught of Ill Omen=KEEP
Draught of Inferno Ward I=KEEP
Draught of Shimmering Reflection I=KEEP
Draught of the Clear Mind I=KEEP
Draught of the Craftsman=KEEP
Draught of Companion's Relief I=KEEP
Kerafyrm's Bite XI=KEEP
Kerafyrm's Bite XII=KEEP
Scorpion's Agony XII=KEEP
Spider's Bite XII=KEEP
;========================================================
; SEB ITEMS
;========================================================
Sebilisian Seal of Command=KEEP
Gem of Swirling Shadows=KEEP
Corrosive Bile=KEEP

;========================================================
; SEB ORIGINATOR'S OVERLOOKED ODDITY
;========================================================
; 
;Bloodstained Gear Assembly=1
;Bloodstained Spring=3
;Bloodstained Gear Set #1=1
;Bloodstained Gear Set #2=1
;Bloodstained Gear Set #3=1
;Senescent Sanitizer=KEEP

;========================================================
; WEREWOLVES
;========================================================
Bloody Werewolf Fang=SELL
Patch of Werewolf Fur=SELL
Essence of Werewolf Rage=SELL
Werewolf Tongue=SELL

;========================================================
; HC HOWLING STONES DZ MATS (KEEP)
;========================================================
Variegated Silk=KEEP
Variegated Leather=KEEP
Variegated Rings=KEEP
Variegated Powder=KEEP

;========================================================
; VEKSAR ARMOR LOOT (TRADEABLE)
;=======================================================
Contaminated Armguards of the Healing Waters=KEEP
Contaminated Boots of the Healing Waters=KEEP
Contaminated Bracer of the Healing Waters=KEEP
Contaminated Breastplate of the Healing Waters=KEEP
Contaminated Gauntlets of the Healing Waters=KEEP
Contaminated Greaves of the Healing Waters=KEEP
Contaminated Helm of the Healing Waters=KEEP
Corroded Kylong Darkmail Armguards=KEEP
Corroded Kylong Darkmail Chestguard=KEEP
Corroded Kylong Darkmail Footguards=KEEP
Corroded Kylong Darkmail Handguards=KEEP
Corroded Kylong Darkmail Headguard=KEEP
Corroded Kylong Darkmail Legguards=KEEP
Corroded Kylong Darkmail Wristguards=KEEP
Fraying Waterlogged Silk Blouse=KEEP
Fraying Waterlogged Silk Bracelet=KEEP
Fraying Waterlogged Silk Gloves=KEEP
Fraying Waterlogged Silk Headband=KEEP
Fraying Waterlogged Silk Pantaloons=KEEP
Fraying Waterlogged Silk Shoes=KEEP
Fraying Waterlogged Silk Sleeves=KEEP
Soggy Moss Covered Armwraps=KEEP
Soggy Moss Covered Handwraps=KEEP
Soggy Moss Covered Leggings=KEEP
Soggy Moss Covered Sandals=KEEP
Soggy Moss Covered Skullcap=KEEP
Soggy Moss Covered Tunic=KEEP
Soggy Moss Covered Wristband=KEEP
Forgotten Leather Leash=KEEP
Forgotten Mugger's Sap=KEEP
Forgotten Warlock's Ring=KEEP

;========================================================
; NIGHTVEIL LOOT (TRADABLE)
;========================================================
Scarlet Dream Essence=KEEP
Pure Dream Essence=KEEP
Pristine Dream Essence=KEEP
Perfect Dream Essence=KEEP
;Charred Obulus Relic=KEEP
;Glass Key to the Nowhere Door=KEEP
;Blacksalt Compass=KEEP
;Coldfire Lantern=KEEP
;Fragment of the Maestra=KEEP
;The Bone Violin=KEEP
;Phantom's Bride Doll=KEEP
;Eternal Jack-o-Lantern=KEEP
;Shroud of the Forgotten King=KEEP
;Withered Rose=KEEP
;Map of Midnight=KEEP
;The Ash Crown=KEEP
;The Witch's Bell=KEEP
;Fragment of Vzith=KEEP
;Crown of Radiant Dominion=KEEP
;Hat of the Forsaken Jester=KEEP
;Obsidian Chalice=KEEP
;The Crimson Dice=KEEP
;Death Quill=KEEP
;Mirror of the Last Gaze=KEEP
;Scythe of Silence=KEEP
;Remains of the Ancient Lich=KEEP
;Sword of the Celestial Dawn=KEEP
;Quill of Tomorrow=KEEP
;Ancient Alpha Skull=KEEP

;========================================================
; NIGHTVEIL LOOT (NO-TRADE)
;=======================================================
;Nightveil Scrip=KEEP
;========================================================
; MISC *(LORE CLICKIES/USABLES - KEEP / NEVER SELL)*
;========================================================
Amulet of Necropotence=KEEP
Cobalt Bracer=KEEP
Dollmaker's Locket=KEEP
Earring of Cleansing=KEEP
Earing of Purity=KEEP
Gravebinder=KEEP
Incarnadine Breastplate=KEEP
Prelate's Rubicite Helm=KEEP
Ring of Stealthy Travel=KEEP
Staff of Forbidden Rites=KEEP
Wild Mage's Wand=KEEP
