[Pack]
name=trash destroy list
description=LOOK BEFORE USING - a list of things some choose to destroy

[ItemLimits]
;========================================================
; MISC TS ITEMS  - (BANK) or (DESTROY) as needed
;========================================================
Alabaster Beak=DESTROY
Bonded Loam=DESTROY
Chunk of Taelosian Rock=DESTROY
Clockwork Carapace=DESTROY
Coiled Spring=DESTROY
Cracked Staff=DESTROY
Fine Caladium=DESTROY
Fine Labumum=DESTROY
Flake of Lodestan=DESTROY
Fresh Labumum=DESTROY
Fresh Muscimol=DESTROY
Harmonagate=DESTROY
Hemic Marrow=DESTROY
Immaculate Delphinium=DESTROY
Immaculate Larkspur=DESTROY
Immaculate Oleander=DESTROY
Immaculate Privit=DESTROY
Intricate Binding Powder=BANK
Iridescent Plume=DESTROY
Knuckle Joint=DESTROY
Large Myotis Bat Wing=DESTROY
Lucidem=DESTROY
Makeshift Binding Powder=BANK
Modest Binding Powder=BANK
Muramite Blood=DESTROY
Muramite Etched Scales=DESTROY
Nodding Blue Lily=DESTROY
Prestidigitase=DESTROY
Pristine Larkspur=DESTROY
Pristine Oleander=DESTROY
Pristine Privit=DESTROY
Quality Caladium=DESTROY
Quality Muscimol=DESTROY
Quality Privit=DESTROY
Raw Amber Nihilite=DESTROY
Raw Crimson Nihilite=DESTROY
Raw Dark Matter=DESTROY
Raw Indigo Nihilite=DESTROY
Raw Shimmering Nihilite=DESTROY
Runic Enchantment Plans=DESTROY
Rusty Dagger=DESTROY
Sample of Taelosian Sludge=DESTROY
Shaped Shimmering Nihilite=DESTROY
Soluble Loam=DESTROY
Staurolite=DESTROY
Superior Caladium=DESTROY
Superior Delphinium=DESTROY
Superior Labumum=DESTROY
Superior Larkspur=DESTROY
Superior Muscimol=DESTROY
Superior Oleander=DESTROY
Superior Privit=DESTROY
Taaffeite=DESTROY
Taelosian Wheat=DESTROY
Tiny Cloak of Darkest Night=1
Uncut Alexandrite=DESTROY
Uncut Amethyst=DESTROY
Uncut Black Sapphire=DESTROY
Uncut Combine Star=DESTROY
Uncut Demantoid=DESTROY
Uncut Goshenite=DESTROY
Uncut Jacinth=DESTROY
Uncut Morganite=DESTROY
Uncut Rubellite=DESTROY
Undamaged Noc Fang=DESTROY
Venomous Secretions=DESTROY
Versluierd Fungus=DESTROY
Viscous Clockwork Oil=BANK
Whole Snake Scales=DESTROY
Polished Blue Softstone=DESTROY
;========================================================
; VENOMS + POISONS
;========================================================
Concentrated Grade AA Gormar Venom=DESTROY
Concentrated Grade AA Nigriventer Venom=DESTROY
Concentrated Grade A Nigriventer Venom=DESTROY
Concentrated Grade AA Taipan Venom=DESTROY
Concentrated Grade B Taipan Venom=DESTROY
Distilled Grade C Gormar Venom=DESTROY
Distilled Grade C Taipan Venom=DESTROY
Purified Grade B Mamba Venom=DESTROY
Excellent Spinneret Fluid=DESTROY
Fine Muscimol=DESTROY
Fine Delphinium=DESTROY
Stale Delphinium=DESTROY
Fine Oleander=DESTROY
Fresh Larkspur=DESTROY
Fresh Oleander=DESTROY
Immaculate Muscimol=DESTROY
Pristine Caladium=DESTROY
Pristine Delphinium=DESTROY
Pristine Muscimol=DESTROY
Purified Grade A Gormar Venom=DESTROY
Purified Grade A Mamba Venom=DESTROY
Purified Grade A Nigriventer Venom=DESTROY
Purified Grade AA Gormar Venom=DESTROY
Purified Grade AA Choresine Sample=DESTROY
Purified Grade AA Nigriventer Venom=DESTROY
Purified Grade B Choresine Sample=DESTROY
Purified Grade B Gormar Venom=DESTROY
Purified Grade B Taipan Venom=DESTROY
Purified Grade B Nigriventer Venom=DESTROY
Quality Delphinium=DESTROY
Refined Grade AA Choresine Sample=DESTROY
Refined Grade A Mamba Venom=DESTROY
Refined Grade A Choresine Sample=DESTROY
Refined Grade A Gormar Venom=DESTROY
Refined Grade AA Mamba Venom=DESTROY
Refined Grade A Nigriventer Venom=DESTROY
Refined Grade A Taipan Venom=DESTROY
Refined Grade AA Gormar Venom=DESTROY
Refined Grade AA Nigriventer Venom=DESTROY
Refined Grade B Nigriventer Venom=DESTROY
Superior Labumum=DESTROY
Quality Larkspur=DESTROY
Superior Laburnum=DESTROY