[Pack]
name=tribute list
description=LOOK BEFORE USING - a list of things some choose to tribute

[ItemLimits]

;========================================================
; PLANES OF POWER ARMOR DROPS (TRIBUTE)
;========================================================
Elemental Boot Mold=TRIBUTE
Elemental Bracer Mold=TRIBUTE
Elemental Chain Boot Pattern=TRIBUTE
Elemental Chain Bracelet Pattern=TRIBUTE
Elemental Chain Coif Pattern=TRIBUTE
Elemental Chain Glove Pattern=TRIBUTE
Elemental Chain Pant Pattern=TRIBUTE
Elemental Chain Sleeve Pattern=TRIBUTE
Elemental Gauntlet Mold=TRIBUTE
Elemental Greaves Mold=TRIBUTE
Elemental Helm Mold=TRIBUTE
Elemental Leather Boot Pattern=TRIBUTE
Elemental Leather Glove Pattern=TRIBUTE
Elemental Leather Helm Pattern=TRIBUTE
Elemental Leather Pant Pattern=TRIBUTE
Elemental Leather Sleeve Pattern=TRIBUTE
Elemental Leather Wrist Pattern=TRIBUTE
Elemental Silk Boot Pattern=TRIBUTE
Elemental Silk Bracelet Pattern=TRIBUTE
Elemental Silk Glove Pattern=TRIBUTE
Elemental Silk Pant Pattern=TRIBUTE
Elemental Silk Sleeve Pattern=TRIBUTE
Elemental Silk Turban Pattern=TRIBUTE
Elemental Vambrace Mold=TRIBUTE
;========================================================
; PLANE OF TIME (those marked TRIBUTE are for tribute, 
; ----- those marked 1 are for symbols, ALL for Symbol of Nightmare)
;========================================================

;========================================================
; -----  Plane of Time Raid - Phase 1 (TRIBUTE)
;========================================================
Mask of Conceptual Energy=TRIBUTE
Pulsing Emerald Hoop=TRIBUTE
Ring of Force=TRIBUTE
Smooth Onyx Torque=TRIBUTE
Wristguard of Keen Vision=TRIBUTE

;========================================================
; -----  Plane of Time Raid - Phase 2 (TRIBUTE)
;========================================================
Cloak of Ferocity=TRIBUTE
Cudgel of Wrecking=TRIBUTE
Drape of the Unending=TRIBUTE
Gauntlets of Disruption=TRIBUTE
Girdle of Restoration=TRIBUTE
Glowing Chains=TRIBUTE
Hoop of the Enlightened=TRIBUTE
Shield of the Vortex=TRIBUTE
Tiny Jade Ring=TRIBUTE
Veil of Warmth=TRIBUTE
Wand of the Vortex=TRIBUTE

;========================================================
; -----  Plane of Time Raid - Phase 3 (TRIBUTE)
;========================================================
Cloak of Wishes=TRIBUTE
Dagger of Distraction=TRIBUTE
Necklace of Celestial Energy=TRIBUTE
Ossein of Limitless Time=TRIBUTE
Protective Sleeves=TRIBUTE
Time Phased Quintessence=DESTROY
Time Traveler's Abandoned Notebook=TRIBUTE
;========================================================
; MISC ITEMS (TRIBUTE)
;========================================================
Feranskin Sandals=TRIBUTE
Map of the Burned Woods=TRIBUTE
Mordant Sleeves=TRIBUTE
Mysterious Card=TRIBUTE
Worm Slayer=TRIBUTE
Featherwood Compound Bow=TRIBUTE