-- Run from the lua parent: luajit lua/tools/generate_turbogear_builtin_announce_index.lua [--stamp-hash] [--generated-at=ISO] [--catalog-root=DIR] [--out=PATH]
-- 1) --stamp-hash recomputes catalogs/lazbis.lua content_hash (build-only walker).
-- 2) Regenerates turbogear/generated/builtin_announce_index.lua from the catalog.
local ROOT = "lua/turbogear/"

local stamp, gen_at, out_path = false, nil, nil
local catalog_root = ROOT
for _, a in ipairs(arg or {}) do
    if a == "--stamp-hash" then stamp = true end
    local v = a:match("^%-%-generated%-at=(.+)$")
    if v then gen_at = v end
    v = a:match("^%-%-catalog%-root=(.+)$")
    if v then catalog_root = v end
    v = a:match("^%-%-out=(.+)$")
    if v then out_path = v end
end

local function slash(p) return tostring(p or ""):gsub("\\", "/") end
local function with_slash(p)
    p = slash(p)
    if p ~= "" and not p:match("/$") then p = p .. "/" end
    return p
end

ROOT = with_slash(ROOT)
catalog_root = with_slash(catalog_root)
out_path = out_path or (ROOT .. "generated/builtin_announce_index.lua")
package.path = catalog_root .. "?.lua;" .. catalog_root .. "?/init.lua;" .. ROOT .. "?.lua;" .. ROOT .. "?/init.lua;" .. package.path

local function read(p) local f = assert(io.open(p, "rb")); local s = f:read("*a"); f:close(); return s end
local function write(p, s) local f = assert(io.open(p, "wb")); f:write(s); f:close() end

if stamp then
    local hash = require("catalog_content_hash")
    local cpath = catalog_root .. "catalogs/lazbis.lua"
    local cat = dofile(cpath)
    local h = hash.compute(cat)
    local src = read(cpath)
    local n
    src, n = src:gsub('content_hash = "[^"]*"', 'content_hash = "' .. h .. '"', 1)
    assert(n == 1, "content_hash line not found")
    write(cpath, src)
    io.stderr:write("content_hash = " .. h .. "\n")
end

package.preload["mq"] = function()
    local empty = setmetatable({}, { __call = function() return nil end, __index = function() return nil end })
    return { TLO = setmetatable({ FindItem = function() return empty end, FindItemBank = function() return empty end },
        { __index = function() return empty end }), configDir = ".", pickle = function() end }
end
package.preload["config"] = function()
    return { CFG = {}, Settings = {}, SharedSettings = { bisAnnounceDisabledLists = {} },
        SaveSettings = function() end, SaveSharedSettings = function() end,
        known_class = function(c) return c end, canonical_class = function(c) return c end }
end
package.preload["diagnostics"] = function()
    return { time = function(_, fn) return fn() end, count = function() end, event = function() end,
        sample = function() end, context = function() end }
end

local catalog = require("bis_catalog")
catalog.warm_catalog("generator")
local payload = assert(catalog.generate_builtin_announce_index_payload())
if gen_at then payload.generated_at = gen_at end

local EOL = "\r\n"
local out = {}
local function emit(s) out[#out + 1] = s end
local function is_ident(k) return type(k) == "string" and k:match("^[%a_][%w_]*$") ~= nil end
local function is_array(t)
    local n = #t
    for k in pairs(t) do if type(k) ~= "number" or k < 1 or k > n or k % 1 ~= 0 then return false end end
    return true
end
local function fmt_key(k)
    if type(k) == "number" then return "[" .. tostring(k) .. "]" end
    if is_ident(k) then return k end
    return "[" .. string.format("%q", k) .. "]"
end
local function fmt_val(v)
    if type(v) == "string" then return string.format("%q", v) end
    return tostring(v)
end
local function ser(t, ind)
    local pad = string.rep("    ", ind)
    if is_array(t) and #t > 0 then
        for _, v in ipairs(t) do
            if type(v) == "table" then
                emit(pad .. "{" .. EOL); ser(v, ind + 1); emit(pad .. "}," .. EOL)
            else
                emit(pad .. fmt_val(v) .. "," .. EOL)
            end
        end
        return
    end
    local keys = {}
    for k in pairs(t) do keys[#keys + 1] = k end
    table.sort(keys, function(a, b) return tostring(a) < tostring(b) end)
    for _, k in ipairs(keys) do
        local v = t[k]
        if type(v) == "table" then
            emit(pad .. fmt_key(k) .. " = {" .. EOL); ser(v, ind + 1); emit(pad .. "}," .. EOL)
        else
            emit(pad .. fmt_key(k) .. " = " .. fmt_val(v) .. "," .. EOL)
        end
    end
end
emit("-- Generated by tools/generate_turbogear_builtin_announce_index.lua; do not edit by hand." .. EOL)
emit("return {" .. EOL)
ser(payload, 1)
emit("}" .. EOL)
write(out_path, table.concat(out))
io.stderr:write(string.format("locators=%d keys=%d fingerprint=%s\n", payload.locator_count, payload.key_count, payload.catalog_fingerprint))
