return {
  _meta = {
    format = 'TurboMobsAllaSeed',
    schema_version = 1,
    generator = 'tools/laz_alla_seed.py',
    generated_at = '2026-06-02',
    source = 'Project Lazarus Alla',
    report = {
      records = 2,
      points = 48,
      records_without_points = 0,
      duplicate_points = 11,
      points_missing_timers = 0,
    },
  },
  zones = {
    codecay = {
      zone = 'codecay',
      named = {
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 200010,
          id = 200010,
          name = 'Corrupted Knight',
          source_url = 'https://lazaruseq.com/alla/npcs/200010',
          timer_source = 'lazarus_alla',
          points = {
            { x = 526.0, y = 248.0, z = -79.0, chance = 95.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200010', timer_source = 'lazarus_alla', ph_names = { 'Elite Corrupted Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 483.0, y = 210.0, z = -79.0, chance = 95.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200010', timer_source = 'lazarus_alla', ph_names = { 'Elite Corrupted Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 450.0, y = 106.0, z = -57.0, chance = 95.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200010', timer_source = 'lazarus_alla', ph_names = { 'Elite Corrupted Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 491.0, y = -28.0, z = -54.0, chance = 95.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200010', timer_source = 'lazarus_alla', ph_names = { 'Elite Corrupted Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 344.0, y = -32.0, z = -59.0, chance = 95.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200010', timer_source = 'lazarus_alla', ph_names = { 'Elite Corrupted Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 385.0, y = -78.0, z = -59.0, chance = 95.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200010', timer_source = 'lazarus_alla', ph_names = { 'Elite Corrupted Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 385.0, y = -147.0, z = -59.0, chance = 95.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200010', timer_source = 'lazarus_alla', ph_names = { 'Elite Corrupted Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 325.0, y = 247.0, z = -69.0, chance = 95.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200010', timer_source = 'lazarus_alla', ph_names = { 'Elite Corrupted Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 401.0, y = 181.0, z = -59.0, chance = 95.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200010', timer_source = 'lazarus_alla', ph_names = { 'Elite Corrupted Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 363.0, y = 157.0, z = -59.0, chance = 65.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200010', timer_source = 'lazarus_alla', ph_names = { 'Deathbone Magus', 'Elite Corrupted Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 172.0, y = 296.0, z = -66.0, chance = 80.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200010', timer_source = 'lazarus_alla', ph_names = { 'Elite Corrupted Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus', 'Warlord Abouu' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 200014,
          id = 200014,
          name = 'Elite Corrupted Knight',
          source_url = 'https://lazaruseq.com/alla/npcs/200014',
          timer_source = 'lazarus_alla',
          points = {
            { x = 269.0, y = -106.0, z = -59.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Deathbone Magus', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 275.0, y = -3.0, z = -59.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Pestilence Priest', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 526.0, y = 248.0, z = -79.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Corrupted Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 483.0, y = 210.0, z = -79.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Corrupted Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 443.0, y = 249.0, z = -79.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Deathbone Magus', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 194.0, y = 271.0, z = -64.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Death Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 452.0, y = 143.0, z = -59.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Pestilence Priest', 'Firebone Magus', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 450.0, y = 106.0, z = -57.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Corrupted Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 445.0, y = 18.0, z = -54.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Pestilence Priest', 'Firebone Magus', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 491.0, y = -28.0, z = -54.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Corrupted Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 492.0, y = -141.0, z = -54.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Deathbone Magus', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 448.0, y = -158.0, z = -54.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Pestilence Priest', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 344.0, y = -32.0, z = -59.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Corrupted Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 385.0, y = -78.0, z = -59.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Corrupted Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 385.0, y = -147.0, z = -59.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Corrupted Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 353.0, y = -155.0, z = -59.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Death Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 309.0, y = -143.0, z = -59.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Death Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 197.0, y = 319.0, z = -64.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Death Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 344.0, y = 322.0, z = -69.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Death Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 296.0, y = 247.0, z = -69.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Deathbone Magus', 'Pestilence Priest', 'Firebone Magus', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 325.0, y = 247.0, z = -69.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Corrupted Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 326.0, y = 225.0, z = -67.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Death Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 199.0, y = 173.0, z = -69.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Pestilence Priest', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 226.0, y = 132.0, z = -69.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Death Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 401.0, y = 181.0, z = -59.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Corrupted Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 363.0, y = 157.0, z = -59.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Corrupted Knight', 'Deathbone Magus', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 468.0, y = -84.0, z = -54.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Firebone Magus', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 248.0, y = 185.0, z = -69.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Deathbone Magus', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 328.0, y = -79.0, z = -59.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Firebone Magus', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 172.0, y = 296.0, z = -66.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Corrupted Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus', 'Warlord Abouu' } },
            { x = 252.0, y = -42.0, z = -59.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Firebone Magus', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 271.0, y = -66.0, z = -59.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Pestilence Priest', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 257.0, y = 113.0, z = -69.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Pestilence Priest', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 202.0, y = -84.0, z = -74.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Firebone Magus', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 292.0, y = 225.0, z = -68.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Death Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 310.0, y = 176.0, z = -67.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Death Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
            { x = 280.0, y = 321.0, z = -69.0, chance = 1.0, respawn_seconds = 1320, source_url = 'https://lazaruseq.com/alla/npcs/200014', timer_source = 'lazarus_alla', ph_names = { 'Death Knight', 'Elite Death Knight', 'Pestilence Archon', 'Deathbone Archmagus', 'Firebone Archmagus' } },
          },
        },
      },
    },
  },
}
