return {
  _meta = {
    format = 'TurboMobsAllaSeed',
    schema_version = 1,
    generator = 'tools/laz_alla_seed.py',
    generated_at = '2026-06-02',
    source = 'Project Lazarus Alla',
    report = {
      records = 20,
      points = 22,
      records_without_points = 0,
      duplicate_points = 0,
      points_missing_timers = 0,
    },
  },
  zones = {
    gukbottom_hc = {
      zone = 'gukbottom_hc',
      named = {
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2066146,
          id = 2066146,
          name = 'A Frenzied Ghoul',
          source_url = 'https://lazaruseq.com/alla/npcs/2066146',
          timer_source = 'lazarus_alla',
          points = {
            { x = -1041.0, y = 1072.0, z = -193.0, chance = 25.0, respawn_seconds = 870, source_url = 'https://lazaruseq.com/alla/npcs/2066146', timer_source = 'lazarus_alla', ph_names = { 'a bloodthirsty ghoul' } },
            { x = -1056.0, y = 1077.0, z = -193.0, chance = 25.0, respawn_seconds = 870, source_url = 'https://lazaruseq.com/alla/npcs/2066146', timer_source = 'lazarus_alla', ph_names = { 'a dar ghoul knight', 'a bloodthirsty ghoul' } },
            { x = -1072.0, y = 1072.0, z = -193.0, chance = 25.0, respawn_seconds = 870, source_url = 'https://lazaruseq.com/alla/npcs/2066146', timer_source = 'lazarus_alla', ph_names = { 'a dar ghoul knight', 'a bloodthirsty ghoul' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2066153,
          id = 2066153,
          name = 'A Froglok Crusader',
          source_url = 'https://lazaruseq.com/alla/npcs/2066153',
          timer_source = 'lazarus_alla',
          points = {
            { x = -594.0, y = 231.0, z = -263.0, chance = 25.0, respawn_seconds = 870, source_url = 'https://lazaruseq.com/alla/npcs/2066153', timer_source = 'lazarus_alla', ph_names = { 'a froglok dar knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2066160,
          id = 2066160,
          name = 'A Froglok Herbalist',
          source_url = 'https://lazaruseq.com/alla/npcs/2066160',
          timer_source = 'lazarus_alla',
          points = {
            { x = -259.0, y = 18.0, z = -221.0, chance = 25.0, respawn_seconds = 870, source_url = 'https://lazaruseq.com/alla/npcs/2066160', timer_source = 'lazarus_alla', ph_names = { 'a froglok jin shaman' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2066175,
          id = 2066175,
          name = 'A Froglok Noble',
          source_url = 'https://lazaruseq.com/alla/npcs/2066175',
          timer_source = 'lazarus_alla',
          points = {
            { x = -101.0, y = 331.0, z = -221.0, chance = 25.0, respawn_seconds = 870, source_url = 'https://lazaruseq.com/alla/npcs/2066175', timer_source = 'lazarus_alla', ph_names = { 'a froglok zol knight', 'a froglok jin shaman' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2066121,
          id = 2066121,
          name = 'A Froglok Tactician',
          source_url = 'https://lazaruseq.com/alla/npcs/2066121',
          timer_source = 'lazarus_alla',
          points = {
            { x = -21.0, y = -75.0, z = -221.0, chance = 25.0, respawn_seconds = 870, source_url = 'https://lazaruseq.com/alla/npcs/2066121', timer_source = 'lazarus_alla', ph_names = { 'a froglok kor shaman' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2066171,
          id = 2066171,
          name = 'A Ghoul Assassin',
          source_url = 'https://lazaruseq.com/alla/npcs/2066171',
          timer_source = 'lazarus_alla',
          points = {
            { x = -758.0, y = 618.0, z = -108.0, chance = 30.0, respawn_seconds = 870, source_url = 'https://lazaruseq.com/alla/npcs/2066171', timer_source = 'lazarus_alla', ph_names = { 'a wan ghoul knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2066169,
          id = 2066169,
          name = 'A Ghoul Cavalier',
          source_url = 'https://lazaruseq.com/alla/npcs/2066169',
          timer_source = 'lazarus_alla',
          points = {
            { x = -608.0, y = 578.0, z = -193.0, chance = 25.0, respawn_seconds = 870, source_url = 'https://lazaruseq.com/alla/npcs/2066169', timer_source = 'lazarus_alla', ph_names = { 'a wan ghoul knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2066092,
          id = 2066092,
          name = 'A Ghoul Executioner',
          source_url = 'https://lazaruseq.com/alla/npcs/2066092',
          timer_source = 'lazarus_alla',
          points = {
            { x = -889.0, y = 622.0, z = -202.0, chance = 50.0, respawn_seconds = 870, source_url = 'https://lazaruseq.com/alla/npcs/2066092', timer_source = 'lazarus_alla', ph_names = { 'a wan ghoul knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2066108,
          id = 2066108,
          name = 'A Ghoul Ritualist',
          source_url = 'https://lazaruseq.com/alla/npcs/2066108',
          timer_source = 'lazarus_alla',
          points = {
            { x = -704.0, y = 769.0, z = -137.0, chance = 25.0, respawn_seconds = 870, source_url = 'https://lazaruseq.com/alla/npcs/2066108', timer_source = 'lazarus_alla', ph_names = { 'a tal ghoul wizard' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2066165,
          id = 2066165,
          name = 'A Ghoul Sage',
          source_url = 'https://lazaruseq.com/alla/npcs/2066165',
          timer_source = 'lazarus_alla',
          points = {
            { x = -744.0, y = 543.0, z = -192.0, chance = 25.0, respawn_seconds = 870, source_url = 'https://lazaruseq.com/alla/npcs/2066165', timer_source = 'lazarus_alla', ph_names = { 'a wan ghoul knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2066100,
          id = 2066100,
          name = 'A Ghoul Savant',
          source_url = 'https://lazaruseq.com/alla/npcs/2066100',
          timer_source = 'lazarus_alla',
          points = {
            { x = -602.0, y = 581.0, z = -165.0, chance = 25.0, respawn_seconds = 870, source_url = 'https://lazaruseq.com/alla/npcs/2066100', timer_source = 'lazarus_alla', ph_names = { 'a wan ghoul knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2066163,
          id = 2066163,
          name = 'A Ghoul Sentinel',
          source_url = 'https://lazaruseq.com/alla/npcs/2066163',
          timer_source = 'lazarus_alla',
          points = {
            { x = -1085.0, y = 845.0, z = -207.0, chance = 25.0, respawn_seconds = 870, source_url = 'https://lazaruseq.com/alla/npcs/2066163', timer_source = 'lazarus_alla', ph_names = { 'a dar ghoul knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2066021,
          id = 2066021,
          name = 'A Ghoul Supplier',
          source_url = 'https://lazaruseq.com/alla/npcs/2066021',
          timer_source = 'lazarus_alla',
          points = {
            { x = -770.0, y = 638.0, z = -108.0, chance = 25.0, respawn_seconds = 870, source_url = 'https://lazaruseq.com/alla/npcs/2066021', timer_source = 'lazarus_alla', ph_names = { 'a wan ghoul knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2066000,
          id = 2066000,
          name = 'A Minotaur Elder',
          source_url = 'https://lazaruseq.com/alla/npcs/2066000',
          timer_source = 'lazarus_alla',
          points = {
            { x = -299.0, y = 903.0, z = -233.0, chance = 25.0, respawn_seconds = 870, source_url = 'https://lazaruseq.com/alla/npcs/2066000', timer_source = 'lazarus_alla', ph_names = { 'a greater minotaur' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2066219,
          id = 2066219,
          name = 'A Minotaur Patriarch',
          source_url = 'https://lazaruseq.com/alla/npcs/2066219',
          timer_source = 'lazarus_alla',
          points = {
            { x = 133.0, y = 745.0, z = -207.0, chance = 25.0, respawn_seconds = 870, source_url = 'https://lazaruseq.com/alla/npcs/2066219', timer_source = 'lazarus_alla', ph_names = { 'a greater minotaur', 'a froglok vis knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2066151,
          id = 2066151,
          name = 'A Reanimated Hand',
          source_url = 'https://lazaruseq.com/alla/npcs/2066151',
          timer_source = 'lazarus_alla',
          points = {
            { x = -687.0, y = 1134.0, z = -124.0, chance = 100.0, respawn_seconds = 870, source_url = 'https://lazaruseq.com/alla/npcs/2066151', timer_source = 'lazarus_alla', ph_names = {  } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2066135,
          id = 2066135,
          name = 'An Evil Eye',
          source_url = 'https://lazaruseq.com/alla/npcs/2066135',
          timer_source = 'lazarus_alla',
          points = {
            { x = -450.0, y = 622.0, z = -191.0, chance = 25.0, respawn_seconds = 870, source_url = 'https://lazaruseq.com/alla/npcs/2066135', timer_source = 'lazarus_alla', ph_names = { 'a froglok urd shaman' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2066156,
          id = 2066156,
          name = 'The Ghoul Arch Magus',
          source_url = 'https://lazaruseq.com/alla/npcs/2066156',
          timer_source = 'lazarus_alla',
          points = {
            { x = -831.0, y = 1184.0, z = -193.0, chance = 25.0, respawn_seconds = 870, source_url = 'https://lazaruseq.com/alla/npcs/2066156', timer_source = 'lazarus_alla', ph_names = { 'a kor ghoul wizard' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2066005,
          id = 2066005,
          name = 'The Ghoul Lord',
          source_url = 'https://lazaruseq.com/alla/npcs/2066005',
          timer_source = 'lazarus_alla',
          points = {
            { x = -748.0, y = 1558.0, z = -169.0, chance = 25.0, respawn_seconds = 870, source_url = 'https://lazaruseq.com/alla/npcs/2066005', timer_source = 'lazarus_alla', ph_names = { 'a dar ghoul knight', 'a guk ghoul wizard', 'a bok ghoul knight', 'a guk ghoul knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2066159,
          id = 2066159,
          name = 'the froglok king',
          source_url = 'https://lazaruseq.com/alla/npcs/2066159',
          timer_source = 'lazarus_alla',
          points = {
            { x = 22.0, y = -104.0, z = -230.0, chance = 25.0, respawn_seconds = 870, source_url = 'https://lazaruseq.com/alla/npcs/2066159', timer_source = 'lazarus_alla', ph_names = { 'a froglok jin shaman', 'a froglok guk shaman', 'a froglok guk knight' } },
          },
        },
      },
    },
  },
}
