return {
  _meta = {
    format = 'TurboMobsAllaSeed',
    schema_version = 1,
    generator = 'tools/laz_alla_seed.py',
    generated_at = '2026-06-02',
    source = 'Project Lazarus Alla',
    report = {
      records = 20,
      points = 21,
      records_without_points = 0,
      duplicate_points = 0,
      points_missing_timers = 0,
    },
  },
  zones = {
    gukbottom = {
      zone = 'gukbottom',
      named = {
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 66146,
          id = 66146,
          name = 'a frenzied ghoul',
          source_url = 'https://lazaruseq.com/alla/npcs/66146',
          timer_source = 'lazarus_alla',
          points = {
            { x = -1073.0, y = 1072.0, z = -193.0, chance = 20.0, respawn_seconds = 1740, source_url = 'https://lazaruseq.com/alla/npcs/66146', timer_source = 'lazarus_alla', ph_names = { 'a zol ghoul knight', 'a bloodthirsty ghoul' } },
            { x = -1057.0, y = 1077.0, z = -192.0, chance = 20.0, respawn_seconds = 1740, source_url = 'https://lazaruseq.com/alla/npcs/66146', timer_source = 'lazarus_alla', ph_names = { 'a zol ghoul knight', 'a bloodthirsty ghoul' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 66153,
          id = 66153,
          name = 'a froglok crusader',
          source_url = 'https://lazaruseq.com/alla/npcs/66153',
          timer_source = 'lazarus_alla',
          points = {
            { x = -595.0, y = 231.0, z = -263.0, chance = 34.0, respawn_seconds = 1740, source_url = 'https://lazaruseq.com/alla/npcs/66153', timer_source = 'lazarus_alla', ph_names = { 'a froglok zol knight', 'a froglok dar knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 66160,
          id = 66160,
          name = 'a froglok herbalist',
          source_url = 'https://lazaruseq.com/alla/npcs/66160',
          timer_source = 'lazarus_alla',
          points = {
            { x = -260.0, y = 18.0, z = -221.0, chance = 34.0, respawn_seconds = 1740, source_url = 'https://lazaruseq.com/alla/npcs/66160', timer_source = 'lazarus_alla', ph_names = { 'a froglok jin shaman', 'a froglok bok knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 66175,
          id = 66175,
          name = 'a froglok noble',
          source_url = 'https://lazaruseq.com/alla/npcs/66175',
          timer_source = 'lazarus_alla',
          points = {
            { x = -80.0, y = 362.0, z = -235.0, chance = 25.0, respawn_seconds = 1740, source_url = 'https://lazaruseq.com/alla/npcs/66175', timer_source = 'lazarus_alla', ph_names = { 'a froglok jin shaman' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 66121,
          id = 66121,
          name = 'a froglok tactician',
          source_url = 'https://lazaruseq.com/alla/npcs/66121',
          timer_source = 'lazarus_alla',
          points = {
            { x = -22.0, y = -76.0, z = -221.0, chance = 30.0, respawn_seconds = 1740, source_url = 'https://lazaruseq.com/alla/npcs/66121', timer_source = 'lazarus_alla', ph_names = { 'a froglok kor shaman' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 66171,
          id = 66171,
          name = 'a ghoul assassin',
          source_url = 'https://lazaruseq.com/alla/npcs/66171',
          timer_source = 'lazarus_alla',
          points = {
            { x = -754.0, y = 620.0, z = -109.0, chance = 30.0, respawn_seconds = 1740, source_url = 'https://lazaruseq.com/alla/npcs/66171', timer_source = 'lazarus_alla', ph_names = { 'a wan ghoul knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 66169,
          id = 66169,
          name = 'a ghoul cavalier',
          source_url = 'https://lazaruseq.com/alla/npcs/66169',
          timer_source = 'lazarus_alla',
          points = {
            { x = -609.0, y = 578.0, z = -190.0, chance = 30.0, respawn_seconds = 1740, source_url = 'https://lazaruseq.com/alla/npcs/66169', timer_source = 'lazarus_alla', ph_names = { 'a wan ghoul knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 66092,
          id = 66092,
          name = 'a ghoul executioner',
          source_url = 'https://lazaruseq.com/alla/npcs/66092',
          timer_source = 'lazarus_alla',
          points = {
            { x = -890.0, y = 622.0, z = -203.0, chance = 30.0, respawn_seconds = 1740, source_url = 'https://lazaruseq.com/alla/npcs/66092', timer_source = 'lazarus_alla', ph_names = { 'a wan ghoul knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 66108,
          id = 66108,
          name = 'a ghoul ritualist',
          source_url = 'https://lazaruseq.com/alla/npcs/66108',
          timer_source = 'lazarus_alla',
          points = {
            { x = -705.0, y = 769.0, z = -137.0, chance = 30.0, respawn_seconds = 1740, source_url = 'https://lazaruseq.com/alla/npcs/66108', timer_source = 'lazarus_alla', ph_names = { 'a tal ghoul wizard' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 66165,
          id = 66165,
          name = 'a ghoul sage',
          source_url = 'https://lazaruseq.com/alla/npcs/66165',
          timer_source = 'lazarus_alla',
          points = {
            { x = -740.0, y = 538.0, z = -190.0, chance = 34.0, respawn_seconds = 1740, source_url = 'https://lazaruseq.com/alla/npcs/66165', timer_source = 'lazarus_alla', ph_names = { 'a zol ghoul knight', 'an urd ghoul wizard' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 66100,
          id = 66100,
          name = 'a ghoul savant',
          source_url = 'https://lazaruseq.com/alla/npcs/66100',
          timer_source = 'lazarus_alla',
          points = {
            { x = -603.0, y = 581.0, z = -165.0, chance = 34.0, respawn_seconds = 1740, source_url = 'https://lazaruseq.com/alla/npcs/66100', timer_source = 'lazarus_alla', ph_names = { 'a wan ghoul knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 66163,
          id = 66163,
          name = 'a ghoul sentinel',
          source_url = 'https://lazaruseq.com/alla/npcs/66163',
          timer_source = 'lazarus_alla',
          points = {
            { x = -1085.0, y = 845.0, z = -204.0, chance = 30.0, respawn_seconds = 1740, source_url = 'https://lazaruseq.com/alla/npcs/66163', timer_source = 'lazarus_alla', ph_names = { 'a dar ghoul knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 66021,
          id = 66021,
          name = 'a ghoul supplier',
          source_url = 'https://lazaruseq.com/alla/npcs/66021',
          timer_source = 'lazarus_alla',
          points = {
            { x = -774.0, y = 638.0, z = -108.0, chance = 30.0, respawn_seconds = 1740, source_url = 'https://lazaruseq.com/alla/npcs/66021', timer_source = 'lazarus_alla', ph_names = { 'a wan ghoul knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 66178,
          id = 66178,
          name = 'a minotaur elder',
          source_url = 'https://lazaruseq.com/alla/npcs/66178',
          timer_source = 'lazarus_alla',
          points = {
            { x = -304.0, y = 903.0, z = -233.0, chance = 20.0, respawn_seconds = 1740, source_url = 'https://lazaruseq.com/alla/npcs/66178', timer_source = 'lazarus_alla', ph_names = { 'a greater minotaur' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 66173,
          id = 66173,
          name = 'a minotaur patriarch',
          source_url = 'https://lazaruseq.com/alla/npcs/66173',
          timer_source = 'lazarus_alla',
          points = {
            { x = -507.0, y = 648.0, z = -198.0, chance = 30.0, respawn_seconds = 1740, source_url = 'https://lazaruseq.com/alla/npcs/66173', timer_source = 'lazarus_alla', ph_names = { 'a greater minotaur' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 66036,
          id = 66036,
          name = 'a reanimated hand',
          source_url = 'https://lazaruseq.com/alla/npcs/66036',
          timer_source = 'lazarus_alla',
          points = {
            { x = -688.0, y = 1126.0, z = -124.0, chance = 33.0, respawn_seconds = 1740, source_url = 'https://lazaruseq.com/alla/npcs/66036', timer_source = 'lazarus_alla', ph_names = {  } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 66014,
          id = 66014,
          name = 'an evil eye',
          source_url = 'https://lazaruseq.com/alla/npcs/66014',
          timer_source = 'lazarus_alla',
          points = {
            { x = -451.0, y = 622.0, z = -191.0, chance = 33.0, respawn_seconds = 1740, source_url = 'https://lazaruseq.com/alla/npcs/66014', timer_source = 'lazarus_alla', ph_names = { 'a froglok tal shaman' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 66159,
          id = 66159,
          name = 'the froglok king',
          source_url = 'https://lazaruseq.com/alla/npcs/66159',
          timer_source = 'lazarus_alla',
          points = {
            { x = 22.0, y = -105.0, z = -230.0, chance = 20.0, respawn_seconds = 1740, source_url = 'https://lazaruseq.com/alla/npcs/66159', timer_source = 'lazarus_alla', ph_names = { 'a froglok bok knight', 'a froglok guk shaman', 'a froglok guk knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 66156,
          id = 66156,
          name = 'the ghoul arch magus',
          source_url = 'https://lazaruseq.com/alla/npcs/66156',
          timer_source = 'lazarus_alla',
          points = {
            { x = -832.0, y = 1184.0, z = -190.0, chance = 25.0, respawn_seconds = 1740, source_url = 'https://lazaruseq.com/alla/npcs/66156', timer_source = 'lazarus_alla', ph_names = { 'a kor ghoul wizard', 'a jin ghoul wizard' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 66005,
          id = 66005,
          name = 'the ghoul lord',
          source_url = 'https://lazaruseq.com/alla/npcs/66005',
          timer_source = 'lazarus_alla',
          points = {
            { x = -749.0, y = 1558.0, z = -166.0, chance = 33.0, respawn_seconds = 1740, source_url = 'https://lazaruseq.com/alla/npcs/66005', timer_source = 'lazarus_alla', ph_names = { 'a guk ghoul knight', 'a guk ghoul wizard' } },
          },
        },
      },
    },
  },
}
