return {
  _meta = {
    format = 'TurboMobsAllaSeed',
    schema_version = 1,
    generator = 'tools/laz_alla_seed.py',
    generated_at = '2026-06-16',
    source = 'Project Lazarus Alla',
    report = {
      records = 25,
      points = 25,
      records_without_points = 0,
      duplicate_points = 0,
      points_missing_timers = 0,
    },
  },
  zones = {
    hateplaneb = {
      zone = 'hateplaneb',
      named = {
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186177,
          id = 186177,
          name = 'Arcanist V`Gimis',
          source_url = 'https://lazaruseq.com/alla/npcs/186177',
          timer_source = 'lazarus_alla',
          points = {
            { x = -79.0, y = -856.0, z = 4.0, chance = 10.0, respawn_seconds = 3600, source_url = 'https://lazaruseq.com/alla/npcs/186177', timer_source = 'lazarus_alla', ph_names = { 'a sorcerer of hate' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186176,
          id = 186176,
          name = 'Arch Lich T`Vaxok',
          source_url = 'https://lazaruseq.com/alla/npcs/186176',
          timer_source = 'lazarus_alla',
          points = {
            { x = 129.0, y = -667.0, z = 4.0, chance = 10.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/186176', timer_source = 'lazarus_alla', ph_names = { 'a warlock of hate' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186175,
          id = 186175,
          name = 'Archon G`Uvin',
          source_url = 'https://lazaruseq.com/alla/npcs/186175',
          timer_source = 'lazarus_alla',
          points = {
            { x = 177.0, y = -795.0, z = 4.0, chance = 10.0, respawn_seconds = 3600, source_url = 'https://lazaruseq.com/alla/npcs/186175', timer_source = 'lazarus_alla', ph_names = { 'a high priest of hate' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186167,
          id = 186167,
          name = 'Assassin Z`Jrix',
          source_url = 'https://lazaruseq.com/alla/npcs/186167',
          timer_source = 'lazarus_alla',
          points = {
            { x = 71.0, y = -381.0, z = 4.0, chance = 10.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/186167', timer_source = 'lazarus_alla', ph_names = { 'an agent of hate' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186170,
          id = 186170,
          name = 'Dread Knight T`Kamax',
          source_url = 'https://lazaruseq.com/alla/npcs/186170',
          timer_source = 'lazarus_alla',
          points = {
            { x = 379.0, y = -621.0, z = 4.0, chance = 20.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/186170', timer_source = 'lazarus_alla', ph_names = { 'a knight of hate' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186174,
          id = 186174,
          name = 'Dreadlord M`Noxin',
          source_url = 'https://lazaruseq.com/alla/npcs/186174',
          timer_source = 'lazarus_alla',
          points = {
            { x = 540.0, y = -874.0, z = 24.0, chance = 20.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/186174', timer_source = 'lazarus_alla', ph_names = { 'a gravelord of hate' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186169,
          id = 186169,
          name = 'Evangelist W`Rixxus',
          source_url = 'https://lazaruseq.com/alla/npcs/186169',
          timer_source = 'lazarus_alla',
          points = {
            { x = 532.0, y = -520.0, z = 4.0, chance = 20.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/186169', timer_source = 'lazarus_alla', ph_names = { 'a templar of hate' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186183,
          id = 186183,
          name = 'Grandmaster H`Qilm',
          source_url = 'https://lazaruseq.com/alla/npcs/186183',
          timer_source = 'lazarus_alla',
          points = {
            { x = -507.0, y = -495.0, z = 6.0, chance = 10.0, respawn_seconds = 3, source_url = 'https://lazaruseq.com/alla/npcs/186183', timer_source = 'lazarus_alla', ph_names = { 'a greater kiraikuei' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186186,
          id = 186186,
          name = 'Grim Abhorrent Kaltik',
          source_url = 'https://lazaruseq.com/alla/npcs/186186',
          timer_source = 'lazarus_alla',
          points = {
            { x = -737.0, y = -201.0, z = 6.0, chance = 10.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/186186', timer_source = 'lazarus_alla', ph_names = { 'a grim abhorrent' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186187,
          id = 186187,
          name = 'Lord of Fury',
          source_url = 'https://lazaruseq.com/alla/npcs/186187',
          timer_source = 'lazarus_alla',
          points = {
            { x = 406.0, y = -95.0, z = 10.0, chance = 10.0, respawn_seconds = 3600, source_url = 'https://lazaruseq.com/alla/npcs/186187', timer_source = 'lazarus_alla', ph_names = { 'a fury ghast' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186154,
          id = 186154,
          name = 'Lord of Ire',
          source_url = 'https://lazaruseq.com/alla/npcs/186154',
          timer_source = 'lazarus_alla',
          points = {
            { x = -598.0, y = 502.0, z = 4.0, chance = 10.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/186154', timer_source = 'lazarus_alla', ph_names = { 'an ire ghast' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186184,
          id = 186184,
          name = 'Master D`Samni',
          source_url = 'https://lazaruseq.com/alla/npcs/186184',
          timer_source = 'lazarus_alla',
          points = {
            { x = 457.0, y = -318.0, z = 25.0, chance = 10.0, respawn_seconds = 3600, source_url = 'https://lazaruseq.com/alla/npcs/186184', timer_source = 'lazarus_alla', ph_names = { 'a sinister lich' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186156,
          id = 186156,
          name = 'Master R`Tal',
          source_url = 'https://lazaruseq.com/alla/npcs/186156',
          timer_source = 'lazarus_alla',
          points = {
            { x = -537.0, y = 218.0, z = 4.0, chance = 10.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/186156', timer_source = 'lazarus_alla', ph_names = { 'a kiraikuei' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186151,
          id = 186151,
          name = 'Mistress A`Zara',
          source_url = 'https://lazaruseq.com/alla/npcs/186151',
          timer_source = 'lazarus_alla',
          points = {
            { x = -814.0, y = -549.0, z = 5.0, chance = 20.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/186151', timer_source = 'lazarus_alla', ph_names = { 'a forsaken revenant' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186181,
          id = 186181,
          name = 'Mistress of Malevolence',
          source_url = 'https://lazaruseq.com/alla/npcs/186181',
          timer_source = 'lazarus_alla',
          points = {
            { x = 562.0, y = -409.0, z = 26.0, chance = 10.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/186181', timer_source = 'lazarus_alla', ph_names = { 'a malevolent banshee' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186173,
          id = 186173,
          name = 'Overlord R`Gahbsa',
          source_url = 'https://lazaruseq.com/alla/npcs/186173',
          timer_source = 'lazarus_alla',
          points = {
            { x = 407.0, y = -732.0, z = 24.0, chance = 20.0, respawn_seconds = 3600, source_url = 'https://lazaruseq.com/alla/npcs/186173', timer_source = 'lazarus_alla', ph_names = { 'a warlord of hate' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186168,
          id = 186168,
          name = 'Sorcerer C`Gazin',
          source_url = 'https://lazaruseq.com/alla/npcs/186168',
          timer_source = 'lazarus_alla',
          points = {
            { x = 138.0, y = -225.0, z = 4.0, chance = 20.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/186168', timer_source = 'lazarus_alla', ph_names = { 'a sage of hate' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186172,
          id = 186172,
          name = 'Spy Master I`Kavin',
          source_url = 'https://lazaruseq.com/alla/npcs/186172',
          timer_source = 'lazarus_alla',
          points = {
            { x = 276.0, y = -717.0, z = 4.0, chance = 20.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/186172', timer_source = 'lazarus_alla', ph_names = { 'an assassin of hate' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186188,
          id = 186188,
          name = 'Templar J`Rosix',
          source_url = 'https://lazaruseq.com/alla/npcs/186188',
          timer_source = 'lazarus_alla',
          points = {
            { x = -736.0, y = -858.0, z = 25.0, chance = 10.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/186188', timer_source = 'lazarus_alla', ph_names = { 'a vicar of hate' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186164,
          id = 186164,
          name = 'Vicar M`Kari',
          source_url = 'https://lazaruseq.com/alla/npcs/186164',
          timer_source = 'lazarus_alla',
          points = {
            { x = 31.0, y = 409.0, z = 24.0, chance = 10.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/186164', timer_source = 'lazarus_alla', ph_names = { 'a cleric of hate' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186182,
          id = 186182,
          name = 'Warlock J`Rath',
          source_url = 'https://lazaruseq.com/alla/npcs/186182',
          timer_source = 'lazarus_alla',
          points = {
            { x = 389.0, y = -263.0, z = 8.0, chance = 10.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/186182', timer_source = 'lazarus_alla', ph_names = { 'a warlock of hate' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186171,
          id = 186171,
          name = 'Warlord E`Prosio',
          source_url = 'https://lazaruseq.com/alla/npcs/186171',
          timer_source = 'lazarus_alla',
          points = {
            { x = 353.0, y = -497.0, z = 14.0, chance = 20.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/186171', timer_source = 'lazarus_alla', ph_names = { 'a champion of hate' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186166,
          id = 186166,
          name = 'a hideous rat',
          source_url = 'https://lazaruseq.com/alla/npcs/186166',
          timer_source = 'lazarus_alla',
          points = {
            { x = -825.0, y = 353.0, z = 8.0, chance = 20.0, respawn_seconds = 3600, source_url = 'https://lazaruseq.com/alla/npcs/186166', timer_source = 'lazarus_alla', ph_names = { 'a repulsive rat' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186161,
          id = 186161,
          name = 'an ashenbone broodmaster',
          source_url = 'https://lazaruseq.com/alla/npcs/186161',
          timer_source = 'lazarus_alla',
          points = {
            { x = -179.0, y = 251.0, z = 4.0, chance = 10.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/186161', timer_source = 'lazarus_alla', ph_names = { 'an ashenbone drake' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 186162,
          id = 186162,
          name = 'an eerie chest',
          source_url = 'https://lazaruseq.com/alla/npcs/186162',
          timer_source = 'lazarus_alla',
          points = {
            { x = -242.0, y = 600.0, z = 4.0, chance = 10.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/186162', timer_source = 'lazarus_alla', ph_names = { 'a haunted chest' } },
          },
        },
      },
    },
  },
}
