return {
  _meta = {
    format = 'TurboMobsAllaSeed',
    schema_version = 1,
    generator = 'tools/laz_alla_seed.py',
    generated_at = '2026-06-03',
    source = 'Project Lazarus Alla',
    report = {
      records = 10,
      points = 38,
      records_without_points = 0,
      duplicate_points = 0,
      points_missing_timers = 0,
    },
  },
  zones = {
    hole = {
      zone = 'hole',
      named = {
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 39159,
          id = 39159,
          name = 'Dartain the Lost',
          source_url = 'https://lazaruseq.com/alla/npcs/39159',
          timer_source = 'lazarus_alla',
          points = {
            { x = 514.0, y = 851.0, z = -680.0, chance = 100.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/39159', timer_source = 'lazarus_alla', ph_names = {  } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 39142,
          id = 39142,
          name = 'Gibartik',
          source_url = 'https://lazaruseq.com/alla/npcs/39142',
          timer_source = 'lazarus_alla',
          points = {
            { x = -339.0, y = 347.0, z = -192.0, chance = 14.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39142', timer_source = 'lazarus_alla', ph_names = { 'an elemental monstrosity', 'an elemental warrior', 'an elemental wizard', 'Stonegrinder Minion', 'bejeweled elemental' } },
            { x = -224.0, y = 496.0, z = -219.0, chance = 20.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39142', timer_source = 'lazarus_alla', ph_names = { 'a citybound spirit', 'a rock golem', 'Stonegrinder Minion' } },
            { x = 373.0, y = 262.0, z = -346.0, chance = 20.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39142', timer_source = 'lazarus_alla', ph_names = { 'a spirit of the old city', 'Stonegrinder Minion' } },
            { x = 727.0, y = 52.0, z = -373.0, chance = 34.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39142', timer_source = 'lazarus_alla', ph_names = { 'a spirit of the old city' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 39150,
          id = 39150,
          name = 'Initiate Sirlis',
          source_url = 'https://lazaruseq.com/alla/npcs/39150',
          timer_source = 'lazarus_alla',
          points = {
            { x = 552.0, y = 825.0, z = -661.0, chance = 34.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39150', timer_source = 'lazarus_alla', ph_names = { 'a templebound spirit' } },
            { x = 573.0, y = 760.0, z = -566.0, chance = 25.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39150', timer_source = 'lazarus_alla', ph_names = { 'a templebound spirit' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 39162,
          id = 39162,
          name = 'Irslak the Wretched',
          source_url = 'https://lazaruseq.com/alla/npcs/39162',
          timer_source = 'lazarus_alla',
          points = {
            { x = 525.0, y = 878.0, z = -570.0, chance = 25.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39162', timer_source = 'lazarus_alla', ph_names = { 'a templebound spirit' } },
            { x = 443.0, y = 972.0, z = -574.0, chance = 25.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39162', timer_source = 'lazarus_alla', ph_names = { 'a templebound spirit', 'a temple researcher' } },
            { x = 545.0, y = 879.0, z = -661.0, chance = 25.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39162', timer_source = 'lazarus_alla', ph_names = { 'a templebound spirit', 'a temple researcher' } },
            { x = 503.0, y = 733.0, z = -655.0, chance = 34.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39162', timer_source = 'lazarus_alla', ph_names = { 'a templebound spirit' } },
            { x = 606.0, y = 971.0, z = -574.0, chance = 25.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39162', timer_source = 'lazarus_alla', ph_names = { 'a templebound spirit' } },
            { x = 535.0, y = 516.0, z = -681.0, chance = 100.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/39162', timer_source = 'lazarus_alla', ph_names = {  } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 39148,
          id = 39148,
          name = 'Nortlav the Scalekeeper',
          source_url = 'https://lazaruseq.com/alla/npcs/39148',
          timer_source = 'lazarus_alla',
          points = {
            { x = 102.0, y = 676.0, z = -906.0, chance = 100.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/39148', timer_source = 'lazarus_alla', ph_names = {  } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 39134,
          id = 39134,
          name = 'Rocksoul',
          source_url = 'https://lazaruseq.com/alla/npcs/39134',
          timer_source = 'lazarus_alla',
          points = {
            { x = 88.0, y = -120.0, z = -347.0, chance = 20.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39134', timer_source = 'lazarus_alla', ph_names = { 'a spirit of the ruins', 'an elemental capturer', 'muck covered elemental' } },
            { x = 293.0, y = -31.0, z = -245.0, chance = 25.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39134', timer_source = 'lazarus_alla', ph_names = { 'a spirit of the old city', 'an elemental capturer' } },
            { x = 481.0, y = 64.0, z = -347.0, chance = 20.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39134', timer_source = 'lazarus_alla', ph_names = { 'a spirit of the old city', 'an elemental capturer' } },
            { x = 40.0, y = 24.0, z = -333.0, chance = 25.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39134', timer_source = 'lazarus_alla', ph_names = { 'a spirit of the ruins', 'an elemental capturer' } },
            { x = 664.0, y = 65.0, z = -372.0, chance = 50.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39134', timer_source = 'lazarus_alla', ph_names = { 'an elemental capturer' } },
            { x = 252.0, y = 81.0, z = -343.0, chance = 33.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39134', timer_source = 'lazarus_alla', ph_names = { 'an elemental capturer', 'muck covered elemental' } },
            { x = 287.0, y = 85.0, z = -382.0, chance = 33.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39134', timer_source = 'lazarus_alla', ph_names = { 'an elemental capturer', 'a rock golem' } },
            { x = 703.0, y = 195.0, z = -372.0, chance = 50.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39134', timer_source = 'lazarus_alla', ph_names = { 'an elemental capturer' } },
            { x = 560.0, y = 374.0, z = -640.0, chance = 50.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39134', timer_source = 'lazarus_alla', ph_names = { 'an elemental capturer' } },
            { x = -239.0, y = 534.0, z = -192.0, chance = 33.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39134', timer_source = 'lazarus_alla', ph_names = { 'an elemental capturer', 'muck covered elemental' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 39160,
          id = 39160,
          name = 'Schnozz the Flighty',
          source_url = 'https://lazaruseq.com/alla/npcs/39160',
          timer_source = 'lazarus_alla',
          points = {
            { x = 247.0, y = -28.0, z = -241.0, chance = 100.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/39160', timer_source = 'lazarus_alla', ph_names = {  } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 39135,
          id = 39135,
          name = 'Slizik the Mighty',
          source_url = 'https://lazaruseq.com/alla/npcs/39135',
          timer_source = 'lazarus_alla',
          points = {
            { x = -262.0, y = 476.0, z = -192.0, chance = 20.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39135', timer_source = 'lazarus_alla', ph_names = { 'an elemental warrior', 'a ratman warrior', 'an elemental channeler' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 39132,
          id = 39132,
          name = 'Stonesoul the Unmoving',
          source_url = 'https://lazaruseq.com/alla/npcs/39132',
          timer_source = 'lazarus_alla',
          points = {
            { x = 209.0, y = 121.0, z = -333.0, chance = 20.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39132', timer_source = 'lazarus_alla', ph_names = { 'a spirit of the ruins', 'an elemental harvester' } },
            { x = 273.0, y = -107.0, z = -305.0, chance = 20.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39132', timer_source = 'lazarus_alla', ph_names = { 'a spirit of the old city', 'an elemental harvester' } },
            { x = 687.0, y = 158.0, z = -347.0, chance = 25.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39132', timer_source = 'lazarus_alla', ph_names = { 'a spirit of the old city', 'an elemental harvester' } },
            { x = 443.0, y = 291.0, z = -332.0, chance = 16.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39132', timer_source = 'lazarus_alla', ph_names = { 'a spirit of the old city', 'a flighty fiend', 'an elemental harvester' } },
            { x = 470.0, y = 95.0, z = -323.0, chance = 33.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39132', timer_source = 'lazarus_alla', ph_names = { 'an elemental harvester', 'an elemental deceiver' } },
            { x = 491.0, y = 168.0, z = -323.0, chance = 50.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39132', timer_source = 'lazarus_alla', ph_names = { 'an elemental harvester' } },
            { x = 499.0, y = 279.0, z = -330.0, chance = 50.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39132', timer_source = 'lazarus_alla', ph_names = { 'an elemental harvester' } },
            { x = -201.0, y = 452.0, z = -182.0, chance = 50.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39132', timer_source = 'lazarus_alla', ph_names = { 'an elemental harvester' } },
            { x = -282.0, y = 478.0, z = -192.0, chance = 50.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39132', timer_source = 'lazarus_alla', ph_names = { 'an elemental harvester' } },
            { x = -217.0, y = 544.0, z = -192.0, chance = 50.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39132', timer_source = 'lazarus_alla', ph_names = { 'an elemental harvester' } },
            { x = -103.0, y = 593.0, z = -231.0, chance = 50.0, respawn_seconds = 1200, source_url = 'https://lazaruseq.com/alla/npcs/39132', timer_source = 'lazarus_alla', ph_names = { 'an elemental harvester' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 39152,
          id = 39152,
          name = 'Ulrik the Devout',
          source_url = 'https://lazaruseq.com/alla/npcs/39152',
          timer_source = 'lazarus_alla',
          points = {
            { x = 488.0, y = 800.0, z = -654.0, chance = 50.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/39152', timer_source = 'lazarus_alla', ph_names = { 'a wanderer' } },
          },
        },
      },
    },
  },
}
