return {
  _meta = {
    format = 'TurboMobsAllaSeed',
    schema_version = 1,
    generator = 'tools/laz_alla_seed.py',
    generated_at = '2026-06-16',
    source = 'Project Lazarus Alla',
    report = {
      records = 7,
      points = 41,
      records_without_points = 1,
      duplicate_points = 4,
      points_missing_timers = 0,
    },
  },
  zones = {
    karnor = {
      zone = 'karnor',
      named = {
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 102084,
          id = 102084,
          name = 'Construct of Sathir',
          source_url = 'https://lazaruseq.com/alla/npcs/102084',
          timer_source = 'lazarus_alla',
          points = {
            { x = -635.0, y = 181.0, z = 31.0, chance = 20.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102084', timer_source = 'lazarus_alla', ph_names = { 'a cursed hand', 'a construct' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 102124,
          id = 102124,
          name = 'Hangnail',
          source_url = 'https://lazaruseq.com/alla/npcs/102124',
          timer_source = 'lazarus_alla',
          points = {
            { x = -691.0, y = 126.0, z = 31.0, chance = 20.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102124', timer_source = 'lazarus_alla', ph_names = { 'a cursed hand', 'a construct' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 102119,
          id = 102119,
          name = 'Knight of Sathir',
          source_url = 'https://lazaruseq.com/alla/npcs/102119',
          timer_source = 'lazarus_alla',
          points = {
            { x = -675.0, y = -72.0, z = 12.0, chance = 10.0, respawn_seconds = 3600, source_url = 'https://lazaruseq.com/alla/npcs/102119', timer_source = 'lazarus_alla', ph_names = { 'spectral protector' } },
            { x = -541.0, y = -1.0, z = 19.0, chance = 10.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102119', timer_source = 'lazarus_alla', ph_names = { 'spectral knight', 'skeletal protector', 'spectral protector' } },
            { x = -504.0, y = -174.0, z = 19.0, chance = 10.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102119', timer_source = 'lazarus_alla', ph_names = { 'spectral protector', 'spectral knight', 'skeletal protector' } },
            { x = -416.0, y = -83.0, z = 21.0, chance = 10.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102119', timer_source = 'lazarus_alla', ph_names = { 'spectral knight', 'spectral protector' } },
            { x = -439.0, y = -63.0, z = 21.0, chance = 10.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102119', timer_source = 'lazarus_alla', ph_names = { 'spectral knight', 'spectral protector' } },
            { x = -740.0, y = -111.0, z = 12.0, chance = 10.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102119', timer_source = 'lazarus_alla', ph_names = { 'spectral protector', 'spectral knight' } },
            { x = -768.0, y = -113.0, z = 12.0, chance = 10.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102119', timer_source = 'lazarus_alla', ph_names = { 'spectral knight', 'skeletal protector', 'spectral protector' } },
            { x = -778.0, y = -68.0, z = 11.0, chance = 10.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102119', timer_source = 'lazarus_alla', ph_names = { 'spectral protector', 'spectral knight' } },
            { x = -666.0, y = -126.0, z = 32.0, chance = 10.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102119', timer_source = 'lazarus_alla', ph_names = { 'spectral knight', 'spectral protector' } },
            { x = -696.0, y = -125.0, z = 31.0, chance = 10.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102119', timer_source = 'lazarus_alla', ph_names = { 'spectral knight', 'spectral protector', 'skeletal protector' } },
            { x = -697.0, y = -160.0, z = 32.0, chance = 10.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102119', timer_source = 'lazarus_alla', ph_names = { 'spectral knight', 'spectral protector' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 102123,
          id = 102123,
          name = 'Spirit of Venril Sathir',
          source_url = 'https://lazaruseq.com/alla/npcs/102123',
          timer_source = 'lazarus_alla',
          points = {
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 102125,
          id = 102125,
          name = 'sentry of Sathir',
          source_url = 'https://lazaruseq.com/alla/npcs/102125',
          timer_source = 'lazarus_alla',
          points = {
            { x = -351.0, y = 125.0, z = 3.0, chance = 25.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102125', timer_source = 'lazarus_alla', ph_names = { 'a drolvarg sentry', 'skeletal warlord', 'skeletal guardian' } },
            { x = -257.0, y = 73.0, z = 3.0, chance = 25.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102125', timer_source = 'lazarus_alla', ph_names = { 'a drolvarg sentry' } },
            { x = -305.0, y = 75.0, z = 3.0, chance = 25.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102125', timer_source = 'lazarus_alla', ph_names = { 'a drolvarg sentry', 'skeletal guardian', 'skeletal warlord' } },
            { x = -330.0, y = -93.0, z = 3.0, chance = 20.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102125', timer_source = 'lazarus_alla', ph_names = { 'a drolvarg sentry', 'skeletal guardian', 'skeletal warlord' } },
            { x = -428.0, y = -82.0, z = -49.0, chance = 34.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102125', timer_source = 'lazarus_alla', ph_names = { 'a drolvarg sentry' } },
            { x = -255.0, y = -19.0, z = 3.0, chance = 25.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102125', timer_source = 'lazarus_alla', ph_names = { 'a drolvarg sentry' } },
            { x = -233.0, y = -101.0, z = 3.0, chance = 20.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102125', timer_source = 'lazarus_alla', ph_names = { 'a drolvarg sentry', 'skeletal guardian', 'skeletal warlord' } },
            { x = -302.0, y = -134.0, z = 3.0, chance = 20.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102125', timer_source = 'lazarus_alla', ph_names = { 'a drolvarg sentry', 'skeletal guardian', 'skeletal warlord' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 102120,
          id = 102120,
          name = 'skeletal berserker',
          source_url = 'https://lazaruseq.com/alla/npcs/102120',
          timer_source = 'lazarus_alla',
          points = {
            { x = -527.0, y = 18.0, z = 3.0, chance = 5.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102120', timer_source = 'lazarus_alla', ph_names = { 'a drolvarg sentry', 'skeletal warlord', 'spectral caller' } },
            { x = -408.0, y = 175.0, z = 3.0, chance = 5.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102120', timer_source = 'lazarus_alla', ph_names = { 'a drolvarg sentry', 'spectral curate', 'spectral caller', 'skeletal warlord', 'skeletal guardian' } },
            { x = -426.0, y = 175.0, z = 3.0, chance = 5.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102120', timer_source = 'lazarus_alla', ph_names = { 'a drolvarg sentry', 'skeletal warlord', 'skeletal guardian' } },
            { x = -436.0, y = 35.0, z = 3.0, chance = 5.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102120', timer_source = 'lazarus_alla', ph_names = { 'a drolvarg sentry', 'spectral curate', 'skeletal warlord', 'skeletal guardian' } },
            { x = -514.0, y = -22.0, z = 3.0, chance = 5.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102120', timer_source = 'lazarus_alla', ph_names = { 'a drolvarg sentry', 'skeletal guardian', 'skeletal warlord', 'spectral caller' } },
            { x = -383.0, y = 116.0, z = 5.0, chance = 5.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102120', timer_source = 'lazarus_alla', ph_names = { 'a drolvarg sentry', 'skeletal warlord', 'spectral curate' } },
            { x = -521.0, y = 78.0, z = 5.0, chance = 5.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102120', timer_source = 'lazarus_alla', ph_names = { 'spectral curate', 'skeletal guardian', 'skeletal warlord', 'a drolvarg sentry' } },
            { x = -521.0, y = 102.0, z = 3.0, chance = 5.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102120', timer_source = 'lazarus_alla', ph_names = { 'a drolvarg sentry', 'skeletal warlord', 'skeletal guardian' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 102002,
          id = 102002,
          name = 'spectral curate',
          source_url = 'https://lazaruseq.com/alla/npcs/102002',
          timer_source = 'lazarus_alla',
          points = {
            { x = -278.0, y = -21.0, z = 5.0, chance = 50.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102002', timer_source = 'lazarus_alla', ph_names = {  } },
            { x = -436.0, y = 35.0, z = 3.0, chance = 20.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102002', timer_source = 'lazarus_alla', ph_names = { 'a drolvarg sentry', 'skeletal warlord', 'skeletal guardian', 'skeletal berserker' } },
            { x = -521.0, y = 78.0, z = 5.0, chance = 15.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102002', timer_source = 'lazarus_alla', ph_names = { 'skeletal guardian', 'skeletal warlord', 'a drolvarg sentry', 'skeletal berserker' } },
            { x = -432.0, y = -130.0, z = 21.0, chance = 33.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102002', timer_source = 'lazarus_alla', ph_names = { 'a drolvarg sentry', 'spectral caller' } },
            { x = -426.0, y = -12.0, z = -35.0, chance = 50.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102002', timer_source = 'lazarus_alla', ph_names = { 'spectral caller' } },
            { x = -261.0, y = 88.0, z = 5.0, chance = 100.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102010', timer_source = 'lazarus_alla', ph_names = {  } },
            { x = -408.0, y = 175.0, z = 3.0, chance = 20.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102010', timer_source = 'lazarus_alla', ph_names = { 'a drolvarg sentry', 'spectral caller', 'skeletal warlord', 'skeletal guardian', 'skeletal berserker' } },
            { x = -373.0, y = -131.0, z = 19.0, chance = 25.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102010', timer_source = 'lazarus_alla', ph_names = { 'a drolvarg sentry', 'skeletal guardian', 'skeletal warlord' } },
            { x = -435.0, y = -114.0, z = 21.0, chance = 20.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102010', timer_source = 'lazarus_alla', ph_names = { 'skeletal warlord', 'spectral caller', 'skeletal guardian' } },
            { x = -438.0, y = -130.0, z = 3.0, chance = 25.0, respawn_seconds = 3600, source_url = 'https://lazaruseq.com/alla/npcs/102032', timer_source = 'lazarus_alla', ph_names = { 'a drolvarg sentry', 'skeletal scryer' } },
            { x = -383.0, y = 116.0, z = 5.0, chance = 20.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102032', timer_source = 'lazarus_alla', ph_names = { 'a drolvarg sentry', 'skeletal warlord', 'skeletal berserker' } },
            { x = -433.0, y = -61.0, z = 3.0, chance = 25.0, respawn_seconds = 1440, source_url = 'https://lazaruseq.com/alla/npcs/102032', timer_source = 'lazarus_alla', ph_names = { 'a drolvarg sentry', 'skeletal scryer' } },
          },
        },
      },
    },
  },
}
