return {
  _meta = {
    format = 'TurboMobsAllaSeedManifest',
    schema_version = 1,
    generator = 'tools/laz_alla_seed.py',
    generated_at = '2026-06-16',
  },
  zones = {
    {
      zone = 'abysmal',
      variant = 'normal',
      alla_zone_id = 1,
      label = 'The Abysmal Sea abysmal - 235% exp',
      url = 'https://lazaruseq.com/alla/zones/1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'acrylia',
      variant = 'normal',
      alla_zone_id = 2,
      label = 'The Acrylia Caverns acrylia - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/2',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'airplane',
      variant = 'normal',
      alla_zone_id = 3,
      label = 'The Plane of Sky airplane - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/3',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'airplane_hc',
      variant = 'hardcore',
      alla_zone_id = 6041,
      label = 'The Plane of Sky: Hardcore airplane (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6041?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'akanon',
      variant = 'normal',
      alla_zone_id = 4,
      label = 'Ak\'Anon akanon - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/4',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'akheva',
      variant = 'normal',
      alla_zone_id = 5,
      label = 'The Akheva Ruins akheva - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/5',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'anguish',
      variant = 'normal',
      alla_zone_id = 6,
      label = 'Anguish, the Fallen Palace anguish - 245% exp',
      url = 'https://lazaruseq.com/alla/zones/6',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'arena',
      variant = 'normal',
      alla_zone_id = 9,
      label = 'The Arena arena - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/9',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'barindu',
      variant = 'normal',
      alla_zone_id = 15,
      label = 'Barindu, Hanging Gardens barindu - 235% exp',
      url = 'https://lazaruseq.com/alla/zones/15',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'bazaar',
      variant = 'normal',
      alla_zone_id = 18,
      label = 'The Bazaar bazaar (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/18?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'bazaar',
      variant = 'normal',
      alla_zone_id = 5880,
      label = 'The Bazaar bazaar - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/5880',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'befallen',
      variant = 'normal',
      alla_zone_id = 19,
      label = 'Befallen befallen - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/19',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'befallen_hc',
      variant = 'hardcore',
      alla_zone_id = 6027,
      label = 'Befallen: Hardcore befallen (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6027?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'beholder',
      variant = 'normal',
      alla_zone_id = 21,
      label = 'Gorge of King Xorbb beholder - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/21',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'blackburrow',
      variant = 'normal',
      alla_zone_id = 23,
      label = 'Blackburrow blackburrow - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/23',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'blackburrow_hc',
      variant = 'hardcore',
      alla_zone_id = 6022,
      label = 'Blackburrow: Hardcore blackburrow (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6022?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'bloodfields',
      variant = 'normal',
      alla_zone_id = 25,
      label = 'The Bloodfields bloodfields - 245% exp',
      url = 'https://lazaruseq.com/alla/zones/25',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'bothunder',
      variant = 'normal',
      alla_zone_id = 27,
      label = 'Bastion of Thunder bothunder - 225% exp',
      url = 'https://lazaruseq.com/alla/zones/27',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'burningwood',
      variant = 'normal',
      alla_zone_id = 30,
      label = 'The Burning Wood burningwood - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/30',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'butcher',
      variant = 'normal',
      alla_zone_id = 31,
      label = 'Butcherblock Mountains butcher - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/31',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'cabeast',
      variant = 'normal',
      alla_zone_id = 32,
      label = 'Cabilis East cabeast - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/32',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'cabwest',
      variant = 'normal',
      alla_zone_id = 33,
      label = 'Cabilis West cabwest - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/33',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'cauldron',
      variant = 'normal',
      alla_zone_id = 34,
      label = 'Dagnor\'s Cauldron cauldron - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/34',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'causeway',
      variant = 'normal',
      alla_zone_id = 35,
      label = 'Nobles\' Causeway causeway - 245% exp',
      url = 'https://lazaruseq.com/alla/zones/35',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'cazicthule',
      variant = 'normal',
      alla_zone_id = 36,
      label = 'Accursed Temple of CazicThule cazicthule - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/36',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'cazicthule_hc',
      variant = 'hardcore',
      alla_zone_id = 6031,
      label = 'Accursed Temple of CazicThule: Hardcore cazicthule (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6031?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'chambersa',
      variant = 'normal',
      alla_zone_id = 37,
      label = 'Muramite Proving Grounds chambersa - 245% exp',
      url = 'https://lazaruseq.com/alla/zones/37',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'chambersb',
      variant = 'normal',
      alla_zone_id = 38,
      label = 'Muramite Proving Grounds chambersb - 245% exp',
      url = 'https://lazaruseq.com/alla/zones/38',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'chambersc',
      variant = 'normal',
      alla_zone_id = 39,
      label = 'Muramite Proving Grounds chambersc - 245% exp',
      url = 'https://lazaruseq.com/alla/zones/39',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'chambersd',
      variant = 'normal',
      alla_zone_id = 40,
      label = 'Muramite Proving Grounds chambersd - 245% exp',
      url = 'https://lazaruseq.com/alla/zones/40',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'chamberse',
      variant = 'normal',
      alla_zone_id = 41,
      label = 'Muramite Proving Grounds chamberse - 245% exp',
      url = 'https://lazaruseq.com/alla/zones/41',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'chambersf',
      variant = 'normal',
      alla_zone_id = 42,
      label = 'Muramite Proving Grounds chambersf - 245% exp',
      url = 'https://lazaruseq.com/alla/zones/42',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'charasis',
      variant = 'normal',
      alla_zone_id = 43,
      label = 'The Howling Stones charasis - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/43',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'chardok',
      variant = 'normal',
      alla_zone_id = 44,
      label = 'Chardok chardok - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/44',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'chardokb',
      variant = 'normal',
      alla_zone_id = 45,
      label = 'Chardok: The Halls of Betrayal chardokb - 185% exp',
      url = 'https://lazaruseq.com/alla/zones/45',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'citymist',
      variant = 'normal',
      alla_zone_id = 46,
      label = 'The City of Mist citymist - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/46',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'cobaltscar',
      variant = 'normal',
      alla_zone_id = 48,
      label = 'Cobaltscar cobaltscar - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/48',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'codecay',
      variant = 'normal',
      alla_zone_id = 49,
      label = 'The Crypt of Decay codecay - 225% exp',
      url = 'https://lazaruseq.com/alla/zones/49',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'commons',
      variant = 'normal',
      alla_zone_id = 51,
      label = 'West Commonlands commons - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/51',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'crushbone',
      variant = 'normal',
      alla_zone_id = 56,
      label = 'Crushbone crushbone - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/56',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'crushbone_hc',
      variant = 'hardcore',
      alla_zone_id = 6032,
      label = 'Crushbone: Hardcore crushbone (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6032?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'crystal',
      variant = 'normal',
      alla_zone_id = 58,
      label = 'The Crystal Caverns crystal - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/58',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'crystallos',
      variant = 'normal',
      alla_zone_id = 59,
      label = 'Crystallos, Lair of the Awakened crystallos - 100% exp',
      url = 'https://lazaruseq.com/alla/zones/59',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'dalnir',
      variant = 'normal',
      alla_zone_id = 61,
      label = 'The Crypt of Dalnir dalnir - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/61',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'dawnshroud',
      variant = 'normal',
      alla_zone_id = 62,
      label = 'The Dawnshroud Peaks dawnshroud - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/62',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'delveb',
      variant = 'normal',
      alla_zone_id = 65,
      label = 'Tirranun\'s Delve delveb - 100% exp',
      url = 'https://lazaruseq.com/alla/zones/65',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'discordtower',
      variant = 'normal',
      alla_zone_id = 70,
      label = 'Citadel of the Worldslayer discordtower - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/70',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'dragoncrypt',
      variant = 'normal',
      alla_zone_id = 5879,
      label = 'Lair of the Risen dragoncrypt - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/5879',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'dranik',
      variant = 'normal',
      alla_zone_id = 77,
      label = 'The Ruined City of Dranik dranik - 245% exp',
      url = 'https://lazaruseq.com/alla/zones/77',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'dranikcatacombsa',
      variant = 'normal',
      alla_zone_id = 78,
      label = 'Catacombs of Dranik dranikcatacombsa - 200% exp',
      url = 'https://lazaruseq.com/alla/zones/78',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'dranikcatacombsb',
      variant = 'normal',
      alla_zone_id = 79,
      label = 'Catacombs of Dranik dranikcatacombsb - 200% exp',
      url = 'https://lazaruseq.com/alla/zones/79',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'dranikcatacombsc',
      variant = 'normal',
      alla_zone_id = 80,
      label = 'Catacombs of Dranik dranikcatacombsc - 200% exp',
      url = 'https://lazaruseq.com/alla/zones/80',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'dranikhollowsa',
      variant = 'normal',
      alla_zone_id = 81,
      label = 'Dranik\'s Hollows dranikhollowsa - 200% exp',
      url = 'https://lazaruseq.com/alla/zones/81',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'dranikhollowsb',
      variant = 'normal',
      alla_zone_id = 82,
      label = 'Dranik\'s Hollows dranikhollowsb - 200% exp',
      url = 'https://lazaruseq.com/alla/zones/82',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'dranikhollowsc',
      variant = 'normal',
      alla_zone_id = 83,
      label = 'Dranik\'s Hollows dranikhollowsc - 200% exp',
      url = 'https://lazaruseq.com/alla/zones/83',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'draniksewersa',
      variant = 'normal',
      alla_zone_id = 91,
      label = 'Sewers of Dranik draniksewersa - 200% exp',
      url = 'https://lazaruseq.com/alla/zones/91',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'draniksewersb',
      variant = 'normal',
      alla_zone_id = 92,
      label = 'Sewers of Dranik draniksewersb - 200% exp',
      url = 'https://lazaruseq.com/alla/zones/92',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'draniksewersc',
      variant = 'normal',
      alla_zone_id = 93,
      label = 'Sewers of Dranik draniksewersc - 200% exp',
      url = 'https://lazaruseq.com/alla/zones/93',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'draniksscar',
      variant = 'normal',
      alla_zone_id = 94,
      label = 'Dranik\'s Scar draniksscar - 225% exp',
      url = 'https://lazaruseq.com/alla/zones/94',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'dreadlands',
      variant = 'normal',
      alla_zone_id = 95,
      label = 'The Dreadlands dreadlands - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/95',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'dreadspire_hc_v2',
      variant = 'hardcore',
      alla_zone_id = 6046,
      label = 'Dreadspire Keep: Hardcore dreadspire (v2) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6046?v=2',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'droga',
      variant = 'normal',
      alla_zone_id = 97,
      label = 'The Temple of Droga droga - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/97',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'dulak',
      variant = 'normal',
      alla_zone_id = 98,
      label = 'Dulak\'s Harbor dulak - 180% exp',
      url = 'https://lazaruseq.com/alla/zones/98',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'eastkarana',
      variant = 'normal',
      alla_zone_id = 99,
      label = 'Eastern Plains of Karana eastkarana - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/99',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'eastwastes',
      variant = 'normal',
      alla_zone_id = 102,
      label = 'Eastern Wastes eastwastes - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/102',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'echo',
      variant = 'normal',
      alla_zone_id = 103,
      label = 'The Echo Caverns echo - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/103',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'ecommons',
      variant = 'normal',
      alla_zone_id = 104,
      label = 'East Commonlands ecommons - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/104',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'emeraldjungle',
      variant = 'normal',
      alla_zone_id = 107,
      label = 'The Emerald Jungle emeraldjungle - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/107',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'erudnext',
      variant = 'normal',
      alla_zone_id = 108,
      label = 'Erudin erudnext - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/108',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'erudnint',
      variant = 'normal',
      alla_zone_id = 109,
      label = 'The Erudin Palace erudnint - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/109',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'erudsxing',
      variant = 'normal',
      alla_zone_id = 110,
      label = 'Erud\'s Crossing erudsxing - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/110',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'everfrost',
      variant = 'normal',
      alla_zone_id = 112,
      label = 'Everfrost Peaks everfrost - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/112',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'everfrost_hc',
      variant = 'hardcore',
      alla_zone_id = 6024,
      label = 'Everfrost Peaks: Hardcore everfrost (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6024?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'fearplane',
      variant = 'normal',
      alla_zone_id = 113,
      label = 'The Plane of Fear fearplane - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/113',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'fearplane_hc',
      variant = 'hardcore',
      alla_zone_id = 6038,
      label = 'The Plane of Fear: Hardcore fearplane (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6038?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'feerrott',
      variant = 'normal',
      alla_zone_id = 114,
      label = 'The Feerrott feerrott - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/114',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'felwithea',
      variant = 'normal',
      alla_zone_id = 115,
      label = 'Northern Felwithe felwithea - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/115',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'felwitheb',
      variant = 'normal',
      alla_zone_id = 116,
      label = 'Southern Felwithe felwitheb - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/116',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'ferubi',
      variant = 'normal',
      alla_zone_id = 117,
      label = 'Ferubi, Forgotten Temple of Taelosia ferubi - 235% exp',
      url = 'https://lazaruseq.com/alla/zones/117',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'fieldofbone',
      variant = 'normal',
      alla_zone_id = 119,
      label = 'The Field of Bone fieldofbone - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/119',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'firiona',
      variant = 'normal',
      alla_zone_id = 120,
      label = 'Firiona Vie firiona - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/120',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'freporte',
      variant = 'normal',
      alla_zone_id = 131,
      label = 'East Freeport freporte - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/131',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'freportn',
      variant = 'normal',
      alla_zone_id = 132,
      label = 'North Freeport freportn - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/132',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'freportw',
      variant = 'normal',
      alla_zone_id = 133,
      label = 'West Freeport freportw - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/133',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'frontiermtns',
      variant = 'normal',
      alla_zone_id = 134,
      label = 'Frontier Mountains frontiermtns - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/134',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'frozenshadow',
      variant = 'normal',
      alla_zone_id = 136,
      label = 'The Tower of Frozen Shadow frozenshadow - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/136',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'fungusgrove',
      variant = 'normal',
      alla_zone_id = 137,
      label = 'The Fungus Grove fungusgrove - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/137',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'gfaydark',
      variant = 'normal',
      alla_zone_id = 138,
      label = 'The Greater Faydark gfaydark - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/138',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'greatdivide',
      variant = 'normal',
      alla_zone_id = 139,
      label = 'The Great Divide greatdivide - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/139',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'griegsend',
      variant = 'normal',
      alla_zone_id = 140,
      label = 'Grieg\'s End griegsend - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/140',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'grimling',
      variant = 'normal',
      alla_zone_id = 141,
      label = 'Grimling Forest grimling - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/141',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'grobb',
      variant = 'normal',
      alla_zone_id = 142,
      label = 'Grobb grobb - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/142',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'growthplane',
      variant = 'normal',
      alla_zone_id = 143,
      label = 'The Plane of Growth growthplane - 190% exp',
      url = 'https://lazaruseq.com/alla/zones/143',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'guka',
      variant = 'normal',
      alla_zone_id = 147,
      label = 'Deepest Guk: Cauldron of Lost Souls guka - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/147',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'gukb',
      variant = 'normal',
      alla_zone_id = 148,
      label = 'The Drowning Crypt gukb - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/148',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'gukbottom',
      variant = 'normal',
      alla_zone_id = 149,
      label = 'The Ruins of Old Guk gukbottom - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/149',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'gukbottom_hc',
      variant = 'hardcore',
      alla_zone_id = 6036,
      label = 'The Ruins of Old Guk: Hardcore gukbottom (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6036?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'gukc',
      variant = 'normal',
      alla_zone_id = 150,
      label = 'Deepest Guk: Ancient Aqueducts gukc - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/150',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'gukc',
      variant = 'normal',
      alla_zone_id = 5966,
      label = 'Deepest Guk: The Rescue gukc (v1) - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/5966?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'gukd',
      variant = 'normal',
      alla_zone_id = 151,
      label = 'Deepest Guk: The Mushroom Grove gukd - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/151',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'guke',
      variant = 'normal',
      alla_zone_id = 152,
      label = 'Deepest Guk: The Curse Reborn guke - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/152',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'gukf',
      variant = 'normal',
      alla_zone_id = 153,
      label = 'Deepest Guk: Chapel of the Witnesses gukf - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/153',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'gukg',
      variant = 'normal',
      alla_zone_id = 154,
      label = 'Deepest Guk: The Root Garden gukg - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/154',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'gukg',
      variant = 'normal',
      alla_zone_id = 6019,
      label = 'Deepest Guk: Ritualist of Hate gukg (v1) - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/6019?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'gukh',
      variant = 'normal',
      alla_zone_id = 155,
      label = 'Deepest Guk: Accursed Sanctuary gukh - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/155',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'guktop',
      variant = 'normal',
      alla_zone_id = 156,
      label = 'The City of Guk guktop - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/156',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'guktop_hc',
      variant = 'hardcore',
      alla_zone_id = 6035,
      label = 'The City of Guk: Hardcore guktop (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6035?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'gunthak',
      variant = 'normal',
      alla_zone_id = 157,
      label = 'The Gulf of Gunthak gunthak - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/157',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'halas',
      variant = 'normal',
      alla_zone_id = 160,
      label = 'Halas halas - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/160',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'harbingers',
      variant = 'normal',
      alla_zone_id = 161,
      label = 'Harbinger\'s Spire harbingers - 245% exp',
      url = 'https://lazaruseq.com/alla/zones/161',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'hateplane',
      variant = 'normal',
      alla_zone_id = 162,
      label = 'Plane of Hate hateplane - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/162',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'hateplane_hc',
      variant = 'hardcore',
      alla_zone_id = 6040,
      label = 'Plane of Hate: Hardcore hateplane (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6040?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'hateplaneb',
      variant = 'normal',
      alla_zone_id = 163,
      label = 'The Plane of Hate hateplaneb - 180% exp',
      url = 'https://lazaruseq.com/alla/zones/163',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'hatesfury',
      variant = 'normal',
      alla_zone_id = 164,
      label = 'Hate\'s Fury hatesfury - 185% exp',
      url = 'https://lazaruseq.com/alla/zones/164',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'highkeep',
      variant = 'normal',
      alla_zone_id = 165,
      label = 'High Keep highkeep - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/165',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'highpass',
      variant = 'normal',
      alla_zone_id = 166,
      label = 'Highpass Hold highpass - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/166',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'hohonora',
      variant = 'normal',
      alla_zone_id = 170,
      label = 'The Halls of Honor hohonora - 225% exp',
      url = 'https://lazaruseq.com/alla/zones/170',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'hohonorb',
      variant = 'normal',
      alla_zone_id = 171,
      label = 'The Temple of Marr hohonorb - 225% exp',
      url = 'https://lazaruseq.com/alla/zones/171',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'hole',
      variant = 'normal',
      alla_zone_id = 172,
      label = 'The Hole hole - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/172',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'hole_hc',
      variant = 'hardcore',
      alla_zone_id = 6029,
      label = 'The Hole: Hardcore hole (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6029?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'hollowshade',
      variant = 'normal',
      alla_zone_id = 173,
      label = 'Hollowshade Moor hollowshade - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/173',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'iceclad',
      variant = 'normal',
      alla_zone_id = 174,
      label = 'The Iceclad Ocean iceclad - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/174',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'ikkinz',
      variant = 'normal',
      alla_zone_id = 176,
      label = 'Ikkinz, Chambers of Transcendence ikkinz - 235% exp',
      url = 'https://lazaruseq.com/alla/zones/176',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'inktuta',
      variant = 'normal',
      alla_zone_id = 181,
      label = 'Inktu\'Ta, the Unmasked Chapel inktuta - 235% exp',
      url = 'https://lazaruseq.com/alla/zones/181',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'innothule',
      variant = 'normal',
      alla_zone_id = 182,
      label = 'Innothule Swamp innothule - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/182',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'jaggedpine',
      variant = 'normal',
      alla_zone_id = 184,
      label = 'The Jaggedpine Forest jaggedpine - 170% exp',
      url = 'https://lazaruseq.com/alla/zones/184',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'kael',
      variant = 'normal',
      alla_zone_id = 186,
      label = 'Kael Drakkel kael - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/186',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'kaesora',
      variant = 'normal',
      alla_zone_id = 187,
      label = 'Kaesora kaesora - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/187',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'kaladima',
      variant = 'normal',
      alla_zone_id = 188,
      label = 'South Kaladim kaladima - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/188',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'kaladimb',
      variant = 'normal',
      alla_zone_id = 189,
      label = 'North Kaladim kaladimb - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/189',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'karnor',
      variant = 'normal',
      alla_zone_id = 190,
      label = 'Karnor\'s Castle karnor - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/190',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'katta',
      variant = 'normal',
      alla_zone_id = 191,
      label = 'Katta Castellum katta - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/191',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'kedge',
      variant = 'normal',
      alla_zone_id = 193,
      label = 'Kedge Keep kedge - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/193',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'kerraridge',
      variant = 'normal',
      alla_zone_id = 194,
      label = 'Kerra Isle kerraridge - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/194',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'kithicor',
      variant = 'normal',
      alla_zone_id = 196,
      label = 'Kithicor Forest kithicor - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/196',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'kodtaz',
      variant = 'normal',
      alla_zone_id = 197,
      label = 'Kod\'Taz, Broken Trial Grounds kodtaz - 235% exp',
      url = 'https://lazaruseq.com/alla/zones/197',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'kurn',
      variant = 'normal',
      alla_zone_id = 199,
      label = 'Kurn\'s Tower kurn - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/199',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'lakeofillomen',
      variant = 'normal',
      alla_zone_id = 200,
      label = 'Lake of Ill Omen lakeofillomen - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/200',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'lakerathe',
      variant = 'normal',
      alla_zone_id = 201,
      label = 'Lake Rathetear lakerathe - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/201',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'lavastorm',
      variant = 'normal',
      alla_zone_id = 202,
      label = 'The Lavastorm Mountains lavastorm - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/202',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'letalis',
      variant = 'normal',
      alla_zone_id = 203,
      label = 'Mons Letalis letalis - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/203',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'lfaydark',
      variant = 'normal',
      alla_zone_id = 204,
      label = 'The Lesser Faydark lfaydark - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/204',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'maiden',
      variant = 'normal',
      alla_zone_id = 208,
      label = 'The Maiden\'s Eye maiden - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/208',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mira',
      variant = 'normal',
      alla_zone_id = 213,
      label = 'Miragul\'s Menagerie: Silent Gallery mira - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/213',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mirb',
      variant = 'normal',
      alla_zone_id = 214,
      label = 'Miragul\'s Menagerie: Frozen Nightmare mirb - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/214',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mirc',
      variant = 'normal',
      alla_zone_id = 215,
      label = 'The Spider Den mirc - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/215',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mirc',
      variant = 'normal',
      alla_zone_id = 5967,
      label = 'Miragul\'s Menagerie: Spider Den mirc (v1) - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/5967?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mird',
      variant = 'normal',
      alla_zone_id = 216,
      label = 'Miragul\'s Menagerie: Hushed Banquet mird - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/216',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mire',
      variant = 'normal',
      alla_zone_id = 217,
      label = 'The Frosted Halls mire - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/217',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mirf',
      variant = 'normal',
      alla_zone_id = 218,
      label = 'The Forgotten Wastes mirf - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/218',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mirg',
      variant = 'normal',
      alla_zone_id = 219,
      label = 'Miragul\'s Menagerie: Heart of the Menagerie mirg - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/219',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mirh',
      variant = 'normal',
      alla_zone_id = 220,
      label = 'The Morbid Laboratory mirh - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/220',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'miri',
      variant = 'normal',
      alla_zone_id = 221,
      label = 'The Theater of Imprisoned Horror miri - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/221',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mirj',
      variant = 'normal',
      alla_zone_id = 222,
      label = 'Miragul\'s Menagerie: Grand Library mirj - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/222',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mischiefplane',
      variant = 'normal',
      alla_zone_id = 223,
      label = 'The Plane of Mischief mischiefplane - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/223',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mistmoore',
      variant = 'normal',
      alla_zone_id = 224,
      label = 'The Castle of Mistmoore mistmoore - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/224',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mistmoore_hc',
      variant = 'hardcore',
      alla_zone_id = 6033,
      label = 'The Castle of Mistmoore: Hardcore mistmoore (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6033?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'misty',
      variant = 'normal',
      alla_zone_id = 225,
      label = 'Misty Thicket misty - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/225',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mmca',
      variant = 'normal',
      alla_zone_id = 227,
      label = 'Mistmoore\'s Catacombs: Forlorn Caverns mmca - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/227',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mmcb',
      variant = 'normal',
      alla_zone_id = 228,
      label = 'Mistmoore\'s Catacombs: Dreary Grotto mmcb - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/228',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mmcc',
      variant = 'normal',
      alla_zone_id = 229,
      label = 'Mistmoore\'s Catacombs: Struggles within the Progeny mmcc - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/229',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mmcd',
      variant = 'normal',
      alla_zone_id = 230,
      label = 'Mistmoore\'s Catacombs: Chambers of Eternal Affliction mmcd - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/230',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mmce',
      variant = 'normal',
      alla_zone_id = 231,
      label = 'Mistmoore\'s Catacombs: Sepulcher of the Damned mmce - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/231',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mmcf',
      variant = 'normal',
      alla_zone_id = 232,
      label = 'Mistmoore\'s Catacombs: Scion Lair of Fury mmcf - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/232',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mmcg',
      variant = 'normal',
      alla_zone_id = 233,
      label = 'Mistmoore\'s Catacombs: Cesspits of Putrescence mmcg - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/233',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mmch',
      variant = 'normal',
      alla_zone_id = 234,
      label = 'Mistmoore\'s Catacombs: Aisles of Blood mmch - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/234',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mmci',
      variant = 'normal',
      alla_zone_id = 235,
      label = 'Mistmoore\'s Catacombs: Halls of Sanguinary Rites mmci - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/235',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mmcj',
      variant = 'normal',
      alla_zone_id = 236,
      label = 'Mistmoore\'s Catacombs: Infernal Sanctuary mmcj - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/236',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'mseru',
      variant = 'normal',
      alla_zone_id = 239,
      label = 'Marus Seru mseru - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/239',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'nadox',
      variant = 'normal',
      alla_zone_id = 240,
      label = 'The Crypt of Nadox nadox - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/240',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'najena',
      variant = 'normal',
      alla_zone_id = 241,
      label = 'Najena najena - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/241',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'najena_hc',
      variant = 'hardcore',
      alla_zone_id = 6030,
      label = 'Najena: Hardcore najena (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6030?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'natimbi',
      variant = 'normal',
      alla_zone_id = 242,
      label = 'Natimbi, the Broken Shores natimbi - 235% exp',
      url = 'https://lazaruseq.com/alla/zones/242',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'necropolis',
      variant = 'normal',
      alla_zone_id = 243,
      label = 'Dragon Necropolis necropolis - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/243',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'nedaria',
      variant = 'normal',
      alla_zone_id = 244,
      label = 'Nedaria\'s Landing nedaria - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/244',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'nektulos',
      variant = 'normal',
      alla_zone_id = 246,
      label = 'The Nektulos Forest nektulos - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/246',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'nektulos',
      variant = 'normal',
      alla_zone_id = 439,
      label = 'The Nektulos Forest (NEW) nektulos (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/439?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'neriaka',
      variant = 'normal',
      alla_zone_id = 248,
      label = 'Neriak - Foreign Quarter neriaka - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/248',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'neriakb',
      variant = 'normal',
      alla_zone_id = 249,
      label = 'Neriak - Commons neriakb - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/249',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'neriakc',
      variant = 'normal',
      alla_zone_id = 250,
      label = 'Neriak - 3rd Gate neriakc - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/250',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'netherbian',
      variant = 'normal',
      alla_zone_id = 252,
      label = 'Netherbian Lair netherbian - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/252',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'nexus',
      variant = 'normal',
      alla_zone_id = 253,
      label = 'Nexus nexus - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/253',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'nightmareb',
      variant = 'normal',
      alla_zone_id = 254,
      label = 'The Lair of Terris Thule nightmareb - 225% exp',
      url = 'https://lazaruseq.com/alla/zones/254',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'northkarana',
      variant = 'normal',
      alla_zone_id = 255,
      label = 'The Northern Plains of Karana northkarana - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/255',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'nro',
      variant = 'normal',
      alla_zone_id = 257,
      label = 'Northern Desert of Ro nro - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/257',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'nurga',
      variant = 'normal',
      alla_zone_id = 258,
      label = 'The Mines of Nurga nurga - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/258',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'oasis',
      variant = 'normal',
      alla_zone_id = 259,
      label = 'Oasis of Marr oasis - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/259',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'oasis_hc',
      variant = 'hardcore',
      alla_zone_id = 6028,
      label = 'Oasis of Marr: Hardcore oasis (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6028?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'oggok',
      variant = 'normal',
      alla_zone_id = 263,
      label = 'Oggok oggok - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/263',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'oot',
      variant = 'normal',
      alla_zone_id = 274,
      label = 'Ocean of Tears oot - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/274',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'oot_hc',
      variant = 'hardcore',
      alla_zone_id = 6037,
      label = 'Ocean of Tears: Hardcore oot (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6037?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'overthere',
      variant = 'normal',
      alla_zone_id = 275,
      label = 'The Overthere overthere - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/275',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'paineel',
      variant = 'normal',
      alla_zone_id = 276,
      label = 'Paineel paineel - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/276',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'paludal',
      variant = 'normal',
      alla_zone_id = 277,
      label = 'The Paludal Caverns paludal - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/277',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'paw',
      variant = 'normal',
      alla_zone_id = 278,
      label = 'The Lair of the Splitpaw paw - 170% exp',
      url = 'https://lazaruseq.com/alla/zones/278',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'paw_hc',
      variant = 'hardcore',
      alla_zone_id = 6023,
      label = 'The Lair of the Splitpaw: Hardcore paw (v1) - 170% exp',
      url = 'https://lazaruseq.com/alla/zones/6023?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'pellucid',
      variant = 'normal',
      alla_zone_id = 442,
      label = 'Pellucid Grotto: Manastone Source pellucid (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/442?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'permafrost',
      variant = 'normal',
      alla_zone_id = 279,
      label = 'The Permafrost Caverns permafrost - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/279',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'permafrost_hc',
      variant = 'hardcore',
      alla_zone_id = 6039,
      label = 'The Permafrost Caverns: Hardcore permafrost (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6039?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'poair',
      variant = 'normal',
      alla_zone_id = 280,
      label = 'The Plane of Air poair - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/280',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'podisease',
      variant = 'normal',
      alla_zone_id = 281,
      label = 'The Plane of Disease podisease - 225% exp',
      url = 'https://lazaruseq.com/alla/zones/281',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'poeartha',
      variant = 'normal',
      alla_zone_id = 282,
      label = 'The Plane of Earth poeartha - 245% exp',
      url = 'https://lazaruseq.com/alla/zones/282',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'poearthb',
      variant = 'normal',
      alla_zone_id = 283,
      label = 'The Plane of Earth poearthb - 245% exp',
      url = 'https://lazaruseq.com/alla/zones/283',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'pofire',
      variant = 'normal',
      alla_zone_id = 284,
      label = 'The Plane of Fire pofire - 245% exp',
      url = 'https://lazaruseq.com/alla/zones/284',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'poinnovation',
      variant = 'normal',
      alla_zone_id = 285,
      label = 'The Plane of Innovation poinnovation - 200% exp',
      url = 'https://lazaruseq.com/alla/zones/285',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'pojustice',
      variant = 'normal',
      alla_zone_id = 286,
      label = 'The Plane of Justice pojustice - 225% exp',
      url = 'https://lazaruseq.com/alla/zones/286',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'poknowledge',
      variant = 'normal',
      alla_zone_id = 287,
      label = 'The Plane of Knowledge poknowledge - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/287',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'ponightmare',
      variant = 'normal',
      alla_zone_id = 288,
      label = 'The Plane of Nightmares ponightmare - 225% exp',
      url = 'https://lazaruseq.com/alla/zones/288',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'postorms',
      variant = 'normal',
      alla_zone_id = 289,
      label = 'The Plane of Storms postorms - 235% exp',
      url = 'https://lazaruseq.com/alla/zones/289',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'potactics',
      variant = 'normal',
      alla_zone_id = 290,
      label = 'Drunder, the Fortress of Zek potactics - 225% exp',
      url = 'https://lazaruseq.com/alla/zones/290',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'potimea',
      variant = 'normal',
      alla_zone_id = 291,
      label = 'The Plane of Time potimea - 225% exp',
      url = 'https://lazaruseq.com/alla/zones/291',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'potimeb',
      variant = 'normal',
      alla_zone_id = 292,
      label = 'The Plane of Time potimeb - 225% exp',
      url = 'https://lazaruseq.com/alla/zones/292',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'potorment',
      variant = 'normal',
      alla_zone_id = 293,
      label = 'Torment, the Plane of Pain potorment - 225% exp',
      url = 'https://lazaruseq.com/alla/zones/293',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'potranquility',
      variant = 'normal',
      alla_zone_id = 294,
      label = 'The Plane of Tranquility potranquility - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/294',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'povalor',
      variant = 'normal',
      alla_zone_id = 295,
      label = 'The Plane of Valor povalor - 225% exp',
      url = 'https://lazaruseq.com/alla/zones/295',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'powater',
      variant = 'normal',
      alla_zone_id = 297,
      label = 'The Plane of Water powater - 245% exp',
      url = 'https://lazaruseq.com/alla/zones/297',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'provinggrounds',
      variant = 'normal',
      alla_zone_id = 299,
      label = 'Muramite Proving Grounds provinggrounds - 245% exp',
      url = 'https://lazaruseq.com/alla/zones/299',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'qcat',
      variant = 'normal',
      alla_zone_id = 300,
      label = 'The Qeynos Aqueduct System qcat - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/300',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'qey2hh1',
      variant = 'normal',
      alla_zone_id = 301,
      label = 'The Western Plains of Karana qey2hh1 - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/301',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'qeynos',
      variant = 'normal',
      alla_zone_id = 302,
      label = 'South Qeynos qeynos - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/302',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'qeynos2',
      variant = 'normal',
      alla_zone_id = 303,
      label = 'North Qeynos qeynos2 - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/303',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'qeytoqrg',
      variant = 'normal',
      alla_zone_id = 304,
      label = 'The Qeynos Hills qeytoqrg - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/304',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'qeytoqrg_hc',
      variant = 'hardcore',
      alla_zone_id = 6020,
      label = 'The Qeynos Hills: Hardcore qeytoqrg (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6020?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'qinimi',
      variant = 'normal',
      alla_zone_id = 305,
      label = 'Qinimi, Court of Nihilia qinimi - 235% exp',
      url = 'https://lazaruseq.com/alla/zones/305',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'qrg',
      variant = 'normal',
      alla_zone_id = 306,
      label = 'The Surefall Glade qrg - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/306',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'qvic',
      variant = 'normal',
      alla_zone_id = 307,
      label = 'Qvic, Prayer Grounds of Calling qvic - 235% exp',
      url = 'https://lazaruseq.com/alla/zones/307',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'rathemtn',
      variant = 'normal',
      alla_zone_id = 312,
      label = 'The Rathe Mountains rathemtn - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/312',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'rathemtn_hc',
      variant = 'hardcore',
      alla_zone_id = 6043,
      label = 'The Rathe Mountains: Hardcore rathemtn (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6043?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'riftseekers',
      variant = 'normal',
      alla_zone_id = 315,
      label = 'Riftseekers\' Sanctum riftseekers - 315% exp',
      url = 'https://lazaruseq.com/alla/zones/315',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'rivervale',
      variant = 'normal',
      alla_zone_id = 316,
      label = 'Rivervale rivervale - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/316',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'riwwi',
      variant = 'normal',
      alla_zone_id = 317,
      label = 'Riwwi, Coliseum of Games riwwi - 235% exp',
      url = 'https://lazaruseq.com/alla/zones/317',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'ruja',
      variant = 'normal',
      alla_zone_id = 319,
      label = 'The Rujarkian Hills: Bloodied Quarries ruja - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/319',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'rujb',
      variant = 'normal',
      alla_zone_id = 320,
      label = 'The Rujarkian Hills: Halls of War rujb - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/320',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'rujc',
      variant = 'normal',
      alla_zone_id = 321,
      label = 'The Rujarkian Hills: Wind Bridges rujc - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/321',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'rujd',
      variant = 'normal',
      alla_zone_id = 322,
      label = 'The Rujarkian Hills: Prison Break rujd - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/322',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'ruje',
      variant = 'normal',
      alla_zone_id = 323,
      label = 'The Rujarkian Hills: Drudge Hollows ruje - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/323',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'rujf',
      variant = 'normal',
      alla_zone_id = 324,
      label = 'The Rujarkian Hills: Fortified Lair of the Taskmasters rujf - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/324',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'rujg',
      variant = 'normal',
      alla_zone_id = 325,
      label = 'The Rujarkian Hills: Hidden Vale of Deceit rujg - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/325',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'rujh',
      variant = 'normal',
      alla_zone_id = 326,
      label = 'The Rujarkian Hills: Blazing Forge rujh - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/326',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'ruji',
      variant = 'normal',
      alla_zone_id = 327,
      label = 'The Rujarkian Hills: Arena of Chance ruji - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/327',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'rujj',
      variant = 'normal',
      alla_zone_id = 328,
      label = 'The Rujarkian Hills: Barracks of War rujj - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/328',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'rujj',
      variant = 'normal',
      alla_zone_id = 5974,
      label = 'The Rujarkian Hills: War March of Imal Ojun rujj - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/5974',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'runnyeye',
      variant = 'normal',
      alla_zone_id = 329,
      label = 'The Liberated Citadel of Runnyeye runnyeye - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/329',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'runnyeye_hc',
      variant = 'hardcore',
      alla_zone_id = 6021,
      label = 'The Liberated Citadel of Runnyeye: Hardcore runnyeye (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6021?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'scarlet',
      variant = 'normal',
      alla_zone_id = 330,
      label = 'The Scarlet Desert scarlet - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/330',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'sebilis',
      variant = 'normal',
      alla_zone_id = 331,
      label = 'The Ruins of Sebilis sebilis - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/331',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'sebilis_hc',
      variant = 'hardcore',
      alla_zone_id = 6048,
      label = 'The Ruins of Sebilis: Hardcore sebilis (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6048?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'shadeweaver',
      variant = 'normal',
      alla_zone_id = 332,
      label = 'Shadeweaver\'s Thicket shadeweaver - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/332',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'shadowhaven',
      variant = 'normal',
      alla_zone_id = 333,
      label = 'Shadow Haven shadowhaven - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/333',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'shadowrest',
      variant = 'normal',
      alla_zone_id = 334,
      label = 'Shadowrest shadowrest - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/334',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'sharvahl',
      variant = 'normal',
      alla_zone_id = 336,
      label = 'The City of Shar Vahl sharvahl - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/336',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'sirens',
      variant = 'normal',
      alla_zone_id = 344,
      label = 'Siren\'s Grotto sirens - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/344',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'skyfire',
      variant = 'normal',
      alla_zone_id = 345,
      label = 'The Skyfire Mountains skyfire - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/345',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'skyshrine',
      variant = 'normal',
      alla_zone_id = 347,
      label = 'Skyshrine skyshrine - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/347',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'sleeper',
      variant = 'normal',
      alla_zone_id = 348,
      label = 'The Sleeper\'s Tomb sleeper - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/348',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'sncrematory',
      variant = 'normal',
      alla_zone_id = 349,
      label = 'Sewers of Nihilia, Emanating Cre sncrematory - 195% exp',
      url = 'https://lazaruseq.com/alla/zones/349',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'snlair',
      variant = 'normal',
      alla_zone_id = 350,
      label = 'Sewers of Nihilia, Lair of Trapp snlair - 195% exp',
      url = 'https://lazaruseq.com/alla/zones/350',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'snplant',
      variant = 'normal',
      alla_zone_id = 351,
      label = 'Sewers of Nihilia, Purifying Pla snplant - 195% exp',
      url = 'https://lazaruseq.com/alla/zones/351',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'snpool',
      variant = 'normal',
      alla_zone_id = 352,
      label = 'Sewers of Nihilia, Pool of Sludg snpool - 195% exp',
      url = 'https://lazaruseq.com/alla/zones/352',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'soldunga',
      variant = 'normal',
      alla_zone_id = 353,
      label = 'Solusek\'s Eye soldunga - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/353',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'soldunga_hc',
      variant = 'hardcore',
      alla_zone_id = 6025,
      label = 'Solusek\'s Eye: Hardcore soldunga (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6025?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'soldungb',
      variant = 'normal',
      alla_zone_id = 354,
      label = 'Nagafen\'s Lair soldungb - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/354',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'soldungb_hc',
      variant = 'hardcore',
      alla_zone_id = 6026,
      label = 'Nagafen\'s Lair: Hardcore soldungb (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6026?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'soldungb_hc_v2',
      variant = 'hardcore',
      alla_zone_id = 6047,
      label = 'Nagafen\'s Lair: Hardcore Raid soldungb (v2) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6047?v=2',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'soldungc',
      variant = 'normal',
      alla_zone_id = 355,
      label = 'The Caverns of Exile soldungc - 180% exp',
      url = 'https://lazaruseq.com/alla/zones/355',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'solrotower',
      variant = 'normal',
      alla_zone_id = 356,
      label = 'The Tower of Solusek Ro solrotower - 245% exp',
      url = 'https://lazaruseq.com/alla/zones/356',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'soltemple',
      variant = 'normal',
      alla_zone_id = 357,
      label = 'The Temple of Solusek Ro soltemple - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/357',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'southkarana',
      variant = 'normal',
      alla_zone_id = 359,
      label = 'The Southern Plains of Karana southkarana - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/359',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'southkarana_hc',
      variant = 'hardcore',
      alla_zone_id = 6045,
      label = 'The Southern Plains of Karana: Hardcore southkarana (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6045?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'sro',
      variant = 'normal',
      alla_zone_id = 361,
      label = 'Southern Desert of Ro sro - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/361',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'sseru',
      variant = 'normal',
      alla_zone_id = 362,
      label = 'Sanctus Seru sseru - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/362',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'ssratemple',
      variant = 'normal',
      alla_zone_id = 363,
      label = 'Ssraeshza Temple ssratemple - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/363',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'steamfont',
      variant = 'normal',
      alla_zone_id = 365,
      label = 'Steamfont Mountains steamfont - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/365',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'steamfont',
      variant = 'normal',
      alla_zone_id = 6042,
      label = 'Steamfont Mountains steamfont (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6042?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'stonebrunt',
      variant = 'normal',
      alla_zone_id = 370,
      label = 'The Stonebrunt Mountains stonebrunt - 170% exp',
      url = 'https://lazaruseq.com/alla/zones/370',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'swampofnohope',
      variant = 'normal',
      alla_zone_id = 374,
      label = 'The Swamp of No Hope swampofnohope - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/374',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'tacvi',
      variant = 'normal',
      alla_zone_id = 375,
      label = 'Tacvi, The Broken Temple tacvi - 235% exp',
      url = 'https://lazaruseq.com/alla/zones/375',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'taka',
      variant = 'normal',
      alla_zone_id = 5970,
      label = 'Takish-Hiz: Sunken Library taka - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/5970',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'takb',
      variant = 'normal',
      alla_zone_id = 377,
      label = 'Takish-Hiz: Shifting Tower takb - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/377',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'takc',
      variant = 'normal',
      alla_zone_id = 378,
      label = 'Takish-Hiz: Within the Compact takc - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/378',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'takd',
      variant = 'normal',
      alla_zone_id = 379,
      label = 'Takish-Hiz: Royal Observatory takd - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/379',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'take',
      variant = 'normal',
      alla_zone_id = 380,
      label = 'Takish-Hiz: River of Recollection take - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/380',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'take',
      variant = 'normal',
      alla_zone_id = 6018,
      label = 'Takish-Hiz: The Palace Grounds take (v1) - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/6018?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'takf',
      variant = 'normal',
      alla_zone_id = 381,
      label = 'Takish-Hiz: Sandfall Corridors takf - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/381',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'takg',
      variant = 'normal',
      alla_zone_id = 382,
      label = 'Takish-Hiz: Balancing Chamber takg - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/382',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'takh',
      variant = 'normal',
      alla_zone_id = 383,
      label = 'Takish-Hiz: Sweeping Tides takh - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/383',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'taki',
      variant = 'normal',
      alla_zone_id = 384,
      label = 'Takish-Hiz: Antiquated Palace taki - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/384',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'takj',
      variant = 'normal',
      alla_zone_id = 387,
      label = 'Takish-Hiz: Prismatic Corridors takj - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/387',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'templeveeshan',
      variant = 'normal',
      alla_zone_id = 388,
      label = 'The Temple of Veeshan templeveeshan - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/388',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'tenebrous',
      variant = 'normal',
      alla_zone_id = 389,
      label = 'The Tenebrous Mountains tenebrous - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/389',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'thedeep',
      variant = 'normal',
      alla_zone_id = 393,
      label = 'The Deep thedeep - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/393',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'thegrey',
      variant = 'normal',
      alla_zone_id = 394,
      label = 'The Grey thegrey - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/394',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'thevoida',
      variant = 'normal',
      alla_zone_id = 396,
      label = 'The Void thevoida - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/396',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'thurgadina',
      variant = 'normal',
      alla_zone_id = 404,
      label = 'The City of Thurgadin thurgadina - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/404',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'thurgadinb',
      variant = 'normal',
      alla_zone_id = 405,
      label = 'Icewell Keep thurgadinb - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/405',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'timorous',
      variant = 'normal',
      alla_zone_id = 406,
      label = 'Timorous Deep timorous - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/406',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'tipt',
      variant = 'normal',
      alla_zone_id = 407,
      label = 'Tipt, Treacherous Crags tipt - 235% exp',
      url = 'https://lazaruseq.com/alla/zones/407',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'torgiran',
      variant = 'normal',
      alla_zone_id = 408,
      label = 'The Torgiran Mines torgiran - 185% exp',
      url = 'https://lazaruseq.com/alla/zones/408',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'tox',
      variant = 'normal',
      alla_zone_id = 410,
      label = 'Toxxulia Forest tox - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/410',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'trakanon',
      variant = 'normal',
      alla_zone_id = 412,
      label = 'Trakanon\'s Teeth trakanon - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/412',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'tutorialb',
      variant = 'normal',
      alla_zone_id = 415,
      label = 'The Mines of Gloomingdeep tutorialb - 100% exp',
      url = 'https://lazaruseq.com/alla/zones/415',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'twilight',
      variant = 'normal',
      alla_zone_id = 416,
      label = 'The Twilight Sea twilight - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/416',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'txevu',
      variant = 'normal',
      alla_zone_id = 417,
      label = 'Txevu, Lair of the Elite txevu - 235% exp',
      url = 'https://lazaruseq.com/alla/zones/417',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'umbral',
      variant = 'normal',
      alla_zone_id = 418,
      label = 'The Umbral Plains umbral - 200% exp',
      url = 'https://lazaruseq.com/alla/zones/418',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'unrest',
      variant = 'normal',
      alla_zone_id = 419,
      label = 'The Estate of Unrest unrest - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/419',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'unrest_hc',
      variant = 'hardcore',
      alla_zone_id = 6034,
      label = 'The Estate of Unrest: Hardcore unrest (v1) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6034?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'uqua',
      variant = 'normal',
      alla_zone_id = 420,
      label = 'Uqua, the Ocean God Chantry uqua - 235% exp',
      url = 'https://lazaruseq.com/alla/zones/420',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'veeshan',
      variant = 'normal',
      alla_zone_id = 422,
      label = 'Veeshan\'s Peak veeshan - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/422',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'veeshan_hc_v5',
      variant = 'hardcore',
      alla_zone_id = 6052,
      label = 'Veeshan\'s Peak: Hardcore veeshan (v5) - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/6052?v=5',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'veksar',
      variant = 'normal',
      alla_zone_id = 423,
      label = 'Veksar veksar - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/423',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'veksar_hc',
      variant = 'hardcore',
      alla_zone_id = 6049,
      label = 'Veksar: Hardcore veksar (v1) - 175% exp',
      url = 'https://lazaruseq.com/alla/zones/6049?v=1',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'velketor',
      variant = 'normal',
      alla_zone_id = 424,
      label = 'Velketor\'s Labyrinth velketor - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/424',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'vexthal',
      variant = 'normal',
      alla_zone_id = 426,
      label = 'Vex Thal vexthal - 200% exp',
      url = 'https://lazaruseq.com/alla/zones/426',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'vxed',
      variant = 'normal',
      alla_zone_id = 427,
      label = 'Vxed, the Crumbling Caverns vxed - 235% exp',
      url = 'https://lazaruseq.com/alla/zones/427',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'wakening',
      variant = 'normal',
      alla_zone_id = 428,
      label = 'The Wakening Land wakening - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/428',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'wallofslaughter',
      variant = 'normal',
      alla_zone_id = 429,
      label = 'Wall of Slaughter wallofslaughter - 245% exp',
      url = 'https://lazaruseq.com/alla/zones/429',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'warrens',
      variant = 'normal',
      alla_zone_id = 430,
      label = 'The Warrens warrens - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/430',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'warslikswood',
      variant = 'normal',
      alla_zone_id = 431,
      label = 'The Warsliks Woods warslikswood - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/431',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'westwastes',
      variant = 'normal',
      alla_zone_id = 436,
      label = 'The Western Wastes westwastes - 150% exp',
      url = 'https://lazaruseq.com/alla/zones/436',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
    {
      zone = 'yxtta',
      variant = 'normal',
      alla_zone_id = 437,
      label = 'Yxtta, Pulpit of Exiles yxtta - 235% exp',
      url = 'https://lazaruseq.com/alla/zones/437',
      file = '',
      zone_key_source = 'label',
      records = 0,
      points = 0,
    },
  },
}
