return {
  _meta = {
    format = 'TurboMobsAllaSeed',
    schema_version = 1,
    generator = 'tools/laz_alla_seed.py',
    generated_at = '2026-06-03',
    source = 'Project Lazarus Alla',
    report = {
      records = 24,
      points = 24,
      records_without_points = 0,
      duplicate_points = 0,
      points_missing_timers = 0,
    },
  },
  zones = {
    sebilis = {
      zone = 'sebilis',
      named = {
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89172,
          id = 89172,
          name = 'Arch Duke Iatol',
          source_url = 'https://lazaruseq.com/alla/npcs/89172',
          timer_source = 'lazarus_alla',
          points = {
            { x = 243.0, y = -1310.0, z = -103.0, chance = 20.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/89172', timer_source = 'lazarus_alla', ph_names = { 'skeletal duke' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89174,
          id = 89174,
          name = 'Baron Yosig',
          source_url = 'https://lazaruseq.com/alla/npcs/89174',
          timer_source = 'lazarus_alla',
          points = {
            { x = 27.0, y = -1425.0, z = -103.0, chance = 20.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/89174', timer_source = 'lazarus_alla', ph_names = { 'skeletal baron' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89167,
          id = 89167,
          name = 'Brogg',
          source_url = 'https://lazaruseq.com/alla/npcs/89167',
          timer_source = 'lazarus_alla',
          points = {
            { x = -727.0, y = -1109.0, z = -112.0, chance = 25.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/89167', timer_source = 'lazarus_alla', ph_names = { 'a sebilite golem' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89144,
          id = 89144,
          name = 'Emperor Chottal',
          source_url = 'https://lazaruseq.com/alla/npcs/89144',
          timer_source = 'lazarus_alla',
          points = {
            { x = 225.0, y = -1913.0, z = -121.0, chance = 25.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/89144', timer_source = 'lazarus_alla', ph_names = { 'spectral harbinger' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89124,
          id = 89124,
          name = 'Froggy',
          source_url = 'https://lazaruseq.com/alla/npcs/89124',
          timer_source = 'lazarus_alla',
          points = {
            { x = 873.0, y = -913.0, z = -51.0, chance = 20.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/89124', timer_source = 'lazarus_alla', ph_names = { 'froglok krup knight', 'froglok krup wizard', 'froglok krup shaman' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89175,
          id = 89175,
          name = 'Gruplinort',
          source_url = 'https://lazaruseq.com/alla/npcs/89175',
          timer_source = 'lazarus_alla',
          points = {
            { x = -386.0, y = -977.0, z = -101.0, chance = 20.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/89175', timer_source = 'lazarus_alla', ph_names = { 'froglok ilis wizard', 'froglok ilis acolyte' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89129,
          id = 89129,
          name = 'Harbinger Freglor',
          source_url = 'https://lazaruseq.com/alla/npcs/89129',
          timer_source = 'lazarus_alla',
          points = {
            { x = 243.0, y = -1424.0, z = -103.0, chance = 20.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/89129', timer_source = 'lazarus_alla', ph_names = { 'skeletal harbinger' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89163,
          id = 89163,
          name = 'Hierophant Prime Grekal',
          source_url = 'https://lazaruseq.com/alla/npcs/89163',
          timer_source = 'lazarus_alla',
          points = {
            { x = 27.0, y = -1311.0, z = -103.0, chance = 20.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/89163', timer_source = 'lazarus_alla', ph_names = { 'skeletal hierophant' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89000,
          id = 89000,
          name = 'Tolapumj',
          source_url = 'https://lazaruseq.com/alla/npcs/89000',
          timer_source = 'lazarus_alla',
          points = {
            { x = -444.0, y = -2185.0, z = -141.0, chance = 100.0, respawn_seconds = 7200, source_url = 'https://lazaruseq.com/alla/npcs/89000', timer_source = 'lazarus_alla', ph_names = { } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89159,
          id = 89159,
          name = 'blood of chottal',
          source_url = 'https://lazaruseq.com/alla/npcs/89159',
          timer_source = 'lazarus_alla',
          points = {
            { x = 225.0, y = -1727.0, z = -121.0, chance = 25.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/89159', timer_source = 'lazarus_alla', ph_names = { 'skeletal duke' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89177,
          id = 89177,
          name = 'crypt caretaker',
          source_url = 'https://lazaruseq.com/alla/npcs/89177',
          timer_source = 'lazarus_alla',
          points = {
            { x = 135.0, y = -1301.0, z = -123.0, chance = 20.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/89177', timer_source = 'lazarus_alla', ph_names = { 'dar ghoul knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89173,
          id = 89173,
          name = 'frenzied pox scarab',
          source_url = 'https://lazaruseq.com/alla/npcs/89173',
          timer_source = 'lazarus_alla',
          points = {
            { x = -246.0, y = -927.0, z = -104.0, chance = 16.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/89173', timer_source = 'lazarus_alla', ph_names = { 'a pox scarab', 'froglok dar wizard', 'froglok dar shaman' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89180,
          id = 89180,
          name = 'froglok armorer',
          source_url = 'https://lazaruseq.com/alla/npcs/89180',
          timer_source = 'lazarus_alla',
          points = {
            { x = 537.0, y = -692.0, z = -69.0, chance = 16.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/89180', timer_source = 'lazarus_alla', ph_names = { 'froglok krup shaman', 'froglok krup knight', 'froglok krup enchanter' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89006,
          id = 89006,
          name = 'froglok armsman',
          source_url = 'https://lazaruseq.com/alla/npcs/89006',
          timer_source = 'lazarus_alla',
          points = {
            { x = 647.0, y = -896.0, z = -51.0, chance = 14.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/89006', timer_source = 'lazarus_alla', ph_names = { 'froglok krup shaman', 'froglok krup knight', 'froglok bok wizard', 'froglok bok shaman' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89131,
          id = 89131,
          name = 'froglok bartender',
          source_url = 'https://lazaruseq.com/alla/npcs/89131',
          timer_source = 'lazarus_alla',
          points = {
            { x = 658.0, y = -742.0, z = -69.0, chance = 16.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/89131', timer_source = 'lazarus_alla', ph_names = { 'froglok krup shaman', 'froglok krup knight', 'froglok bok wizard', 'froglok bok shaman' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89164,
          id = 89164,
          name = 'froglok chef',
          source_url = 'https://lazaruseq.com/alla/npcs/89164',
          timer_source = 'lazarus_alla',
          points = {
            { x = 768.0, y = -1120.0, z = -87.0, chance = 20.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/89164', timer_source = 'lazarus_alla', ph_names = { 'froglok krup shaman', 'froglok krup knight', 'froglok krup wizard', 'froglok krup enchanter' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89166,
          id = 89166,
          name = 'froglok commander',
          source_url = 'https://lazaruseq.com/alla/npcs/89166',
          timer_source = 'lazarus_alla',
          points = {
            { x = -334.0, y = -1199.0, z = -105.0, chance = 20.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/89166', timer_source = 'lazarus_alla', ph_names = { 'froglok ilis knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89057,
          id = 89057,
          name = 'froglok ostiary',
          source_url = 'https://lazaruseq.com/alla/npcs/89057',
          timer_source = 'lazarus_alla',
          points = {
            { x = -352.0, y = -927.0, z = -105.0, chance = 20.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/89057', timer_source = 'lazarus_alla', ph_names = { 'froglok zol knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89171,
          id = 89171,
          name = 'froglok pickler',
          source_url = 'https://lazaruseq.com/alla/npcs/89171',
          timer_source = 'lazarus_alla',
          points = {
            { x = -467.0, y = -1223.0, z = -105.0, chance = 20.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/89171', timer_source = 'lazarus_alla', ph_names = { 'froglok dar knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89146,
          id = 89146,
          name = 'froglok repairer',
          source_url = 'https://lazaruseq.com/alla/npcs/89146',
          timer_source = 'lazarus_alla',
          points = {
            { x = 782.0, y = -1144.0, z = -87.0, chance = 20.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/89146', timer_source = 'lazarus_alla', ph_names = { 'froglok krup knight', 'froglok krup wizard', 'froglok krup enchanter', 'froglok krup shaman' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89149,
          id = 89149,
          name = 'gangrenous scarab',
          source_url = 'https://lazaruseq.com/alla/npcs/89149',
          timer_source = 'lazarus_alla',
          points = {
            { x = 321.0, y = -460.0, z = -68.0, chance = 20.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/89149', timer_source = 'lazarus_alla', ph_names = { 'leprous scarab', 'a leprous scarab' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89153,
          id = 89153,
          name = 'myconid spore king',
          source_url = 'https://lazaruseq.com/alla/npcs/89153',
          timer_source = 'lazarus_alla',
          points = {
            { x = 109.0, y = -910.0, z = -165.0, chance = 25.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/89153', timer_source = 'lazarus_alla', ph_names = { 'myconid reaver' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89112,
          id = 89112,
          name = 'sebilite guardian',
          source_url = 'https://lazaruseq.com/alla/npcs/89112',
          timer_source = 'lazarus_alla',
          points = {
            { x = 133.0, y = -888.0, z = -6.0, chance = 16.0, respawn_seconds = 640, source_url = 'https://lazaruseq.com/alla/npcs/89112', timer_source = 'lazarus_alla', ph_names = { 'sebilite golem', 'a sebilite golem' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 89001,
          id = 89001,
          name = 'sebilite protector',
          source_url = 'https://lazaruseq.com/alla/npcs/89001',
          timer_source = 'lazarus_alla',
          points = {
            { x = -624.0, y = -2085.0, z = -134.0, chance = 100.0, respawn_seconds = 7200, source_url = 'https://lazaruseq.com/alla/npcs/89001', timer_source = 'lazarus_alla', ph_names = {  } },
          },
        },
      },
    },
  },
}
