return {
  _meta = {
    format = 'TurboMobsAllaSeed',
    schema_version = 1,
    generator = 'tools/laz_alla_seed.py',
    generated_at = '2026-06-03',
    source = 'Project Lazarus Alla',
    report = {
      records = 27,
      points = 28,
      records_without_points = 0,
      duplicate_points = 1,
      points_missing_timers = 0,
    },
  },
  zones = {
    sebilis_hc = {
      zone = 'sebilis_hc',
      named = {
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089172,
          id = 2089172,
          name = 'Arch Duke Iatol',
          source_url = 'https://lazaruseq.com/alla/npcs/2089172',
          timer_source = 'lazarus_alla',
          points = {
            { x = 243.0, y = -1310.0, z = -103.0, chance = 10.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089172', timer_source = 'lazarus_alla', ph_names = { 'skeletal duke' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089174,
          id = 2089174,
          name = 'Baron Yosig',
          source_url = 'https://lazaruseq.com/alla/npcs/2089174',
          timer_source = 'lazarus_alla',
          points = {
            { x = 27.0, y = -1425.0, z = -103.0, chance = 10.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089174', timer_source = 'lazarus_alla', ph_names = { 'skeletal baron' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089159,
          id = 2089159,
          name = 'Blood of Chottal',
          source_url = 'https://lazaruseq.com/alla/npcs/2089159',
          timer_source = 'lazarus_alla',
          points = {
            { x = 225.0, y = -1727.0, z = -121.0, chance = 15.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089159', timer_source = 'lazarus_alla', ph_names = { 'skeletal duke' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089167,
          id = 2089167,
          name = 'Brogg',
          source_url = 'https://lazaruseq.com/alla/npcs/2089167',
          timer_source = 'lazarus_alla',
          points = {
            { x = -727.0, y = -1109.0, z = -112.0, chance = 15.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089167', timer_source = 'lazarus_alla', ph_names = { 'a sebilite golem' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089177,
          id = 2089177,
          name = 'Crypt Caretaker',
          source_url = 'https://lazaruseq.com/alla/npcs/2089177',
          timer_source = 'lazarus_alla',
          points = {
            { x = 135.0, y = -1301.0, z = -123.0, chance = 15.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089177', timer_source = 'lazarus_alla', ph_names = { 'dar ghoul knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089144,
          id = 2089144,
          name = 'Emperor Chottal',
          source_url = 'https://lazaruseq.com/alla/npcs/2089144',
          timer_source = 'lazarus_alla',
          points = {
            { x = 225.0, y = -1913.0, z = -121.0, chance = 15.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089144', timer_source = 'lazarus_alla', ph_names = { 'spectral harbinger' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089173,
          id = 2089173,
          name = 'Frenzied Pox Scarab',
          source_url = 'https://lazaruseq.com/alla/npcs/2089173',
          timer_source = 'lazarus_alla',
          points = {
            { x = -246.0, y = -927.0, z = -104.0, chance = 15.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089173', timer_source = 'lazarus_alla', ph_names = { 'a pox scarab', 'froglok dar wizard', 'froglok dar shaman' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089124,
          id = 2089124,
          name = 'Froggy',
          source_url = 'https://lazaruseq.com/alla/npcs/2089124',
          timer_source = 'lazarus_alla',
          points = {
            { x = 873.0, y = -913.0, z = -51.0, chance = 15.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089124', timer_source = 'lazarus_alla', ph_names = { 'froglok krup knight', 'froglok krup wizard', 'froglok krup shaman' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089180,
          id = 2089180,
          name = 'Froglok Armorer',
          source_url = 'https://lazaruseq.com/alla/npcs/2089180',
          timer_source = 'lazarus_alla',
          points = {
            { x = 537.0, y = -692.0, z = -69.0, chance = 25.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089180', timer_source = 'lazarus_alla', ph_names = { 'froglok krup shaman', 'froglok krup knight', 'froglok krup enchanter' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089006,
          id = 2089006,
          name = 'Froglok Armsman',
          source_url = 'https://lazaruseq.com/alla/npcs/2089006',
          timer_source = 'lazarus_alla',
          points = {
            { x = 647.0, y = -896.0, z = -51.0, chance = 14.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089006', timer_source = 'lazarus_alla', ph_names = { 'froglok krup shaman', 'froglok krup knight', 'froglok bok wizard', 'froglok bok shaman' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089131,
          id = 2089131,
          name = 'Froglok Bartender',
          source_url = 'https://lazaruseq.com/alla/npcs/2089131',
          timer_source = 'lazarus_alla',
          points = {
            { x = 658.0, y = -742.0, z = -69.0, chance = 15.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089131', timer_source = 'lazarus_alla', ph_names = { 'froglok krup shaman', 'froglok krup knight', 'froglok bok wizard', 'froglok bok shaman' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089164,
          id = 2089164,
          name = 'Froglok Chef',
          source_url = 'https://lazaruseq.com/alla/npcs/2089164',
          timer_source = 'lazarus_alla',
          points = {
            { x = 768.0, y = -1120.0, z = -87.0, chance = 15.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089164', timer_source = 'lazarus_alla', ph_names = { 'froglok krup shaman', 'froglok krup knight', 'froglok krup wizard', 'froglok krup enchanter' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089166,
          id = 2089166,
          name = 'Froglok Commander',
          source_url = 'https://lazaruseq.com/alla/npcs/2089166',
          timer_source = 'lazarus_alla',
          points = {
            { x = -334.0, y = -1199.0, z = -105.0, chance = 15.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089166', timer_source = 'lazarus_alla', ph_names = { 'froglok ilis knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089057,
          id = 2089057,
          name = 'Froglok Ostiary',
          source_url = 'https://lazaruseq.com/alla/npcs/2089057',
          timer_source = 'lazarus_alla',
          points = {
            { x = -352.0, y = -927.0, z = -105.0, chance = 15.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089057', timer_source = 'lazarus_alla', ph_names = { 'froglok zol knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089171,
          id = 2089171,
          name = 'Froglok Pickler',
          source_url = 'https://lazaruseq.com/alla/npcs/2089171',
          timer_source = 'lazarus_alla',
          points = {
            { x = -467.0, y = -1223.0, z = -105.0, chance = 15.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089171', timer_source = 'lazarus_alla', ph_names = { 'froglok dar knight' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089146,
          id = 2089146,
          name = 'Froglok Repairer',
          source_url = 'https://lazaruseq.com/alla/npcs/2089146',
          timer_source = 'lazarus_alla',
          points = {
            { x = 782.0, y = -1144.0, z = -87.0, chance = 10.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089146', timer_source = 'lazarus_alla', ph_names = { 'froglok krup knight', 'froglok krup wizard', 'froglok krup enchanter', 'froglok krup shaman', 'Froglok Watcher' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089182,
          id = 2089182,
          name = 'Froglok Watcher',
          source_url = 'https://lazaruseq.com/alla/npcs/2089182',
          timer_source = 'lazarus_alla',
          points = {
            { x = 782.0, y = -1144.0, z = -87.0, chance = 15.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089182', timer_source = 'lazarus_alla', ph_names = { 'froglok krup knight', 'froglok krup wizard', 'froglok krup enchanter', 'froglok krup shaman', 'Froglok Repairer' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089149,
          id = 2089149,
          name = 'Gangrenous Scarab',
          source_url = 'https://lazaruseq.com/alla/npcs/2089149',
          timer_source = 'lazarus_alla',
          points = {
            { x = 321.0, y = -460.0, z = -68.0, chance = 15.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089149', timer_source = 'lazarus_alla', ph_names = { 'leprous scarab', 'a leprous scarab' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089175,
          id = 2089175,
          name = 'Gruplinort',
          source_url = 'https://lazaruseq.com/alla/npcs/2089175',
          timer_source = 'lazarus_alla',
          points = {
            { x = -386.0, y = -977.0, z = -101.0, chance = 15.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089175', timer_source = 'lazarus_alla', ph_names = { 'froglok ilis wizard', 'froglok ilis acolyte' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089129,
          id = 2089129,
          name = 'Harbinger Freglor',
          source_url = 'https://lazaruseq.com/alla/npcs/2089129',
          timer_source = 'lazarus_alla',
          points = {
            { x = 243.0, y = -1424.0, z = -103.0, chance = 10.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089129', timer_source = 'lazarus_alla', ph_names = { 'skeletal harbinger' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089163,
          id = 2089163,
          name = 'Hierophant Prime Grekal',
          source_url = 'https://lazaruseq.com/alla/npcs/2089163',
          timer_source = 'lazarus_alla',
          points = {
            { x = 27.0, y = -1311.0, z = -103.0, chance = 10.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089163', timer_source = 'lazarus_alla', ph_names = { 'skeletal hierophant' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089200,
          id = 2089200,
          name = 'Myconid Assassin',
          source_url = 'https://lazaruseq.com/alla/npcs/2089200',
          timer_source = 'lazarus_alla',
          points = {
            { x = 225.0, y = -922.0, z = -173.0, chance = 15.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089200', timer_source = 'lazarus_alla', ph_names = { 'myconid priest', 'myconid warrior', 'myconid reaver' } },
            { x = -62.0, y = -777.0, z = -175.0, chance = 15.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089200', timer_source = 'lazarus_alla', ph_names = { 'myconid priest', 'myconid warrior', 'myconid reaver' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089153,
          id = 2089153,
          name = 'Myconid Spore King',
          source_url = 'https://lazaruseq.com/alla/npcs/2089153',
          timer_source = 'lazarus_alla',
          points = {
            { x = 109.0, y = -910.0, z = -165.0, chance = 15.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089153', timer_source = 'lazarus_alla', ph_names = { 'myconid reaver' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089112,
          id = 2089112,
          name = 'Sebilite Guardian',
          source_url = 'https://lazaruseq.com/alla/npcs/2089112',
          timer_source = 'lazarus_alla',
          points = {
            { x = 133.0, y = -888.0, z = -6.0, chance = 15.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089112', timer_source = 'lazarus_alla', ph_names = { 'sebilite golem', 'a sebilite golem' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089001,
          id = 2089001,
          name = 'Sebilite Protector',
          source_url = 'https://lazaruseq.com/alla/npcs/2089001',
          timer_source = 'lazarus_alla',
          points = {
            { x = -624.0, y = -2085.0, z = -134.0, chance = 15.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089001', timer_source = 'lazarus_alla', ph_names = { 'sebilite juggernaut' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089154,
          id = 2089154,
          name = 'The Legendary Trakanon',
          source_url = 'https://lazaruseq.com/alla/npcs/2089154',
          timer_source = 'lazarus_alla',
          points = {
            { x = -679.0, y = -2133.0, z = -132.0, chance = 100.0, respawn_seconds = 3, source_url = 'https://lazaruseq.com/alla/npcs/2089154', timer_source = 'lazarus_alla', ph_names = {  } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 2089000,
          id = 2089000,
          name = 'Tolapumj',
          source_url = 'https://lazaruseq.com/alla/npcs/2089000',
          timer_source = 'lazarus_alla',
          points = {
            { x = -444.0, y = -2185.0, z = -141.0, chance = 15.0, respawn_seconds = 480, source_url = 'https://lazaruseq.com/alla/npcs/2089000', timer_source = 'lazarus_alla', ph_names = { 'froglok ilis enchanter' } },
          },
        },
      },
    },
  },
}
