return {
  _meta = {
    format = 'TurboMobsAllaSeed',
    schema_version = 1,
    generator = 'tools/laz_alla_seed.py',
    generated_at = '2026-06-02',
    source = 'Project Lazarus Alla',
    report = {
      records = 31,
      points = 43,
      records_without_points = 0,
      duplicate_points = 4,
      points_missing_timers = 0,
    },
  },
  zones = {
    wallofslaughter = {
      zone = 'wallofslaughter',
      named = {
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300000,
          id = 300000,
          name = 'Bazu Bonesmasher',
          source_url = 'https://lazaruseq.com/alla/npcs/300000',
          timer_source = 'lazarus_alla',
          points = {
            { x = -556.0, y = -1379.0, z = -3.0, chance = 25.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300000', timer_source = 'lazarus_alla', ph_names = { 'an infernal chimera', 'a bazu thrasher', 'a savage feran' } },
            { x = -870.0, y = -1185.0, z = -21.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300000', timer_source = 'lazarus_alla', ph_names = { 'a bazu thrasher', 'a savage feran' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300049,
          id = 300049,
          name = 'Bazu Destroyer',
          source_url = 'https://lazaruseq.com/alla/npcs/300049',
          timer_source = 'lazarus_alla',
          points = {
            { x = -428.0, y = -1506.0, z = 0.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300049', timer_source = 'lazarus_alla', ph_names = { 'a bazu thrasher' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300047,
          id = 300047,
          name = 'Chimera Deathbringer',
          source_url = 'https://lazaruseq.com/alla/npcs/300047',
          timer_source = 'lazarus_alla',
          points = {
            { x = -1055.0, y = -918.0, z = -27.0, chance = 13.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300047', timer_source = 'lazarus_alla', ph_names = { 'an infernal chimera', 'a bazu thrasher', 'a savage feran', 'a ferocious feran', 'a raging chimera' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300060,
          id = 300060,
          name = 'Chimera Seether',
          source_url = 'https://lazaruseq.com/alla/npcs/300060',
          timer_source = 'lazarus_alla',
          points = {
            { x = -95.0, y = -1079.0, z = 1.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300060', timer_source = 'lazarus_alla', ph_names = { 'an infernal chimera', 'a raging chimera' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300031,
          id = 300031,
          name = 'Cipheron',
          source_url = 'https://lazaruseq.com/alla/npcs/300031',
          timer_source = 'lazarus_alla',
          points = {
            { x = -748.0, y = -236.0, z = -14.0, chance = 100.0, respawn_seconds = 7264, source_url = 'https://lazaruseq.com/alla/npcs/300031', timer_source = 'lazarus_alla', ph_names = {  } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300068,
          id = 300068,
          name = 'Discordling Bloodfiend',
          source_url = 'https://lazaruseq.com/alla/npcs/300068',
          timer_source = 'lazarus_alla',
          points = {
            { x = -889.0, y = 791.0, z = -9.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300068', timer_source = 'lazarus_alla', ph_names = { 'a discordling enchainer' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300078,
          id = 300078,
          name = 'Discordling Chaosfiend',
          source_url = 'https://lazaruseq.com/alla/npcs/300078',
          timer_source = 'lazarus_alla',
          points = {
            { x = -1041.0, y = 724.0, z = -12.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300078', timer_source = 'lazarus_alla', ph_names = { 'a discordling enchainer' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300052,
          id = 300052,
          name = 'Discordling Warfiend',
          source_url = 'https://lazaruseq.com/alla/npcs/300052',
          timer_source = 'lazarus_alla',
          points = {
            { x = -958.0, y = 556.0, z = -8.0, chance = 100.0, respawn_seconds = 7264, source_url = 'https://lazaruseq.com/alla/npcs/300052', timer_source = 'lazarus_alla', ph_names = { 'a discordling enchainer', 'a discordling taskfiend' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300011,
          id = 300011,
          name = 'Dragorn Blightkeeper',
          source_url = 'https://lazaruseq.com/alla/npcs/300011',
          timer_source = 'lazarus_alla',
          points = {
            { x = 2295.0, y = 549.0, z = 40.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300011', timer_source = 'lazarus_alla', ph_names = { 'a dragorn darkwarrior' } },
            { x = 2500.0, y = 129.0, z = 48.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300011', timer_source = 'lazarus_alla', ph_names = { 'a dragorn darkwarrior', 'a dragorn assassin' } },
            { x = 2032.0, y = 546.0, z = 157.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300011', timer_source = 'lazarus_alla', ph_names = { 'a dragorn darkwarrior', 'a dragorn assassin' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300036,
          id = 300036,
          name = 'Dragorn Champion',
          source_url = 'https://lazaruseq.com/alla/npcs/300036',
          timer_source = 'lazarus_alla',
          points = {
            { x = -805.0, y = 298.0, z = 2.0, chance = 100.0, respawn_seconds = 7264, source_url = 'https://lazaruseq.com/alla/npcs/300036', timer_source = 'lazarus_alla', ph_names = {  } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300064,
          id = 300064,
          name = 'Dragorn Nightwalker',
          source_url = 'https://lazaruseq.com/alla/npcs/300064',
          timer_source = 'lazarus_alla',
          points = {
            { x = 2176.0, y = 597.0, z = 39.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300064', timer_source = 'lazarus_alla', ph_names = { 'a dragorn darkwarrior', 'a dragorn assassin' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300081,
          id = 300081,
          name = 'Dragorn Strategist',
          source_url = 'https://lazaruseq.com/alla/npcs/300081',
          timer_source = 'lazarus_alla',
          points = {
            { x = 496.0, y = -230.0, z = 64.0, chance = 10.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300081', timer_source = 'lazarus_alla', ph_names = { 'a dragorn battlemaster', 'a dragorn assassin' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300079,
          id = 300079,
          name = 'Dragorn Turretkeeper',
          source_url = 'https://lazaruseq.com/alla/npcs/300079',
          timer_source = 'lazarus_alla',
          points = {
            { x = -531.0, y = 284.0, z = -11.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300079', timer_source = 'lazarus_alla', ph_names = { 'a dragorn battlemaster' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300048,
          id = 300048,
          name = 'Feran Bloodkeeper',
          source_url = 'https://lazaruseq.com/alla/npcs/300048',
          timer_source = 'lazarus_alla',
          points = {
            { x = -1062.0, y = -876.0, z = -19.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300048', timer_source = 'lazarus_alla', ph_names = { 'an infernal chimera', 'a savage feran', 'a ferocious feran', 'a raging chimera' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300061,
          id = 300061,
          name = 'Feran Savageclaw',
          source_url = 'https://lazaruseq.com/alla/npcs/300061',
          timer_source = 'lazarus_alla',
          points = {
            { x = -445.0, y = -1059.0, z = -4.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300061', timer_source = 'lazarus_alla', ph_names = { 'a savage feran' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300037,
          id = 300037,
          name = 'Girplan Guardian',
          source_url = 'https://lazaruseq.com/alla/npcs/300037',
          timer_source = 'lazarus_alla',
          points = {
            { x = 853.0, y = 265.0, z = 129.0, chance = 100.0, respawn_seconds = 7264, source_url = 'https://lazaruseq.com/alla/npcs/300037', timer_source = 'lazarus_alla', ph_names = {  } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300082,
          id = 300082,
          name = 'Girplan Mastercrafter',
          source_url = 'https://lazaruseq.com/alla/npcs/300082',
          timer_source = 'lazarus_alla',
          points = {
            { x = 978.0, y = 680.0, z = 120.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300082', timer_source = 'lazarus_alla', ph_names = { 'a girplan stonecrafter', 'a girplan geomancer' } },
            { x = 232.0, y = 560.0, z = 3.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300082', timer_source = 'lazarus_alla', ph_names = { 'a girplan geomancer' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300075,
          id = 300075,
          name = 'Girplan Taskmaster',
          source_url = 'https://lazaruseq.com/alla/npcs/300075',
          timer_source = 'lazarus_alla',
          points = {
            { x = 426.0, y = 1056.0, z = 105.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300075', timer_source = 'lazarus_alla', ph_names = { 'a girplan geomancer' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300066,
          id = 300066,
          name = 'Hulcror',
          source_url = 'https://lazaruseq.com/alla/npcs/300066',
          timer_source = 'lazarus_alla',
          points = {
            { x = -1301.0, y = 1566.0, z = 47.0, chance = 100.0, respawn_seconds = 43200, source_url = 'https://lazaruseq.com/alla/npcs/300066', timer_source = 'lazarus_alla', ph_names = {  } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300051,
          id = 300051,
          name = 'Kyv Assassin',
          source_url = 'https://lazaruseq.com/alla/npcs/300051',
          timer_source = 'lazarus_alla',
          points = {
            { x = -123.0, y = 684.0, z = -15.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300051', timer_source = 'lazarus_alla', ph_names = { 'an elite kyv hunter' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300055,
          id = 300055,
          name = 'Kyv Pureshot',
          source_url = 'https://lazaruseq.com/alla/npcs/300055',
          timer_source = 'lazarus_alla',
          points = {
            { x = 697.0, y = 987.0, z = 103.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300055', timer_source = 'lazarus_alla', ph_names = { 'an elite kyv hunter' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300053,
          id = 300053,
          name = 'Noc Bonecleaver',
          source_url = 'https://lazaruseq.com/alla/npcs/300053',
          timer_source = 'lazarus_alla',
          points = {
            { x = 662.0, y = 958.0, z = 107.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300053', timer_source = 'lazarus_alla', ph_names = { 'an elite noc cleaver' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300056,
          id = 300056,
          name = 'Noc Shadowkeeper',
          source_url = 'https://lazaruseq.com/alla/npcs/300056',
          timer_source = 'lazarus_alla',
          points = {
            { x = -65.0, y = 451.0, z = -14.0, chance = 20.0, respawn_seconds = 7264, source_url = 'https://lazaruseq.com/alla/npcs/300056', timer_source = 'lazarus_alla', ph_names = { 'an elite noc sprayblood', 'an elite noc cleaver' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300043,
          id = 300043,
          name = 'Pyrique Redwing',
          source_url = 'https://lazaruseq.com/alla/npcs/300043',
          timer_source = 'lazarus_alla',
          points = {
            { x = 729.0, y = 11.0, z = 134.0, chance = 100.0, respawn_seconds = 21600, source_url = 'https://lazaruseq.com/alla/npcs/300043', timer_source = 'lazarus_alla', ph_names = {  } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300050,
          id = 300050,
          name = 'Shadowhunter',
          source_url = 'https://lazaruseq.com/alla/npcs/300050',
          timer_source = 'lazarus_alla',
          points = {
            { x = -909.0, y = -1047.0, z = -28.0, chance = 100.0, respawn_seconds = 7264, source_url = 'https://lazaruseq.com/alla/npcs/300050', timer_source = 'lazarus_alla', ph_names = { 'an infernal chimera', 'a ferocious feran', 'a raging chimera' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300042,
          id = 300042,
          name = 'The Murkglider Hivequeen',
          source_url = 'https://lazaruseq.com/alla/npcs/300042',
          timer_source = 'lazarus_alla',
          points = {
            { x = 1152.0, y = -1505.0, z = -34.0, chance = 100.0, respawn_seconds = 21600, source_url = 'https://lazaruseq.com/alla/npcs/300042', timer_source = 'lazarus_alla', ph_names = {  } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300076,
          id = 300076,
          name = 'Ukun Fleshflayer',
          source_url = 'https://lazaruseq.com/alla/npcs/300076',
          timer_source = 'lazarus_alla',
          points = {
            { x = -1025.0, y = 921.0, z = -8.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300076', timer_source = 'lazarus_alla', ph_names = { 'an elite ukun boneretriever' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300054,
          id = 300054,
          name = 'Ukun Tendonslicer',
          source_url = 'https://lazaruseq.com/alla/npcs/300054',
          timer_source = 'lazarus_alla',
          points = {
            { x = -244.0, y = 643.0, z = -8.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300054', timer_source = 'lazarus_alla', ph_names = { 'an elite ukun boneretriever', 'an elite ukun deathfang' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300020,
          id = 300020,
          name = 'Velitorkin',
          source_url = 'https://lazaruseq.com/alla/npcs/300020',
          timer_source = 'lazarus_alla',
          points = {
            { x = -114.0, y = -16.0, z = -3.0, chance = 100.0, respawn_seconds = 21600, source_url = 'https://lazaruseq.com/alla/npcs/300020', timer_source = 'lazarus_alla', ph_names = {  } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300019,
          id = 300019,
          name = 'a Dragorn Mastermind',
          source_url = 'https://lazaruseq.com/alla/npcs/300019',
          timer_source = 'lazarus_alla',
          points = {
            { x = 659.0, y = -528.0, z = -8.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300019', timer_source = 'lazarus_alla', ph_names = { 'a dragorn serf' } },
            { x = -1179.0, y = 1177.0, z = -11.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300019', timer_source = 'lazarus_alla', ph_names = { 'a dragorn serf' } },
            { x = 1092.0, y = 963.0, z = 105.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300019', timer_source = 'lazarus_alla', ph_names = { 'a dragorn serf' } },
            { x = -909.0, y = -814.0, z = -7.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300019', timer_source = 'lazarus_alla', ph_names = { 'a dragorn serf' } },
            { x = -607.0, y = 482.0, z = -11.0, chance = 20.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300019', timer_source = 'lazarus_alla', ph_names = { 'a dragorn serf' } },
          },
        },
        {
          schema = 'TurboMobsAllaSeedNpc',
          npc_id = 300046,
          id = 300046,
          name = 'a dragorn assassin',
          source_url = 'https://lazaruseq.com/alla/npcs/300046',
          timer_source = 'lazarus_alla',
          points = {
            { x = 2176.0, y = 597.0, z = 39.0, chance = 15.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300046', timer_source = 'lazarus_alla', ph_names = { 'a dragorn darkwarrior', 'Dragorn Nightwalker' } },
            { x = 2500.0, y = 129.0, z = 48.0, chance = 15.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300046', timer_source = 'lazarus_alla', ph_names = { 'a dragorn darkwarrior', 'Dragorn Blightkeeper' } },
            { x = 2032.0, y = 546.0, z = 157.0, chance = 15.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300046', timer_source = 'lazarus_alla', ph_names = { 'a dragorn darkwarrior', 'Dragorn Blightkeeper' } },
            { x = 1878.0, y = 346.0, z = 176.0, chance = 15.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300046', timer_source = 'lazarus_alla', ph_names = { 'a dragorn darkwarrior' } },
            { x = 496.0, y = -230.0, z = 64.0, chance = 10.0, respawn_seconds = 960, source_url = 'https://lazaruseq.com/alla/npcs/300046', timer_source = 'lazarus_alla', ph_names = { 'a dragorn battlemaster', 'Dragorn Strategist' } },
          },
        },
      },
    },
  },
}
