	['don'] = {
		['Bard'] = {
			['Head'] = 'Keeper\'s Ascendant Helm of Harmony/60457',
			['Chest'] = 'Keeper\'s Ascendant Chestguard of Harmony/60458',
			['Arms'] = 'Keeper\'s Ascendant Armbands of Harmony/60459',
			['Wrist1'] = 'Keeper\'s Ascendant Wristguard of Harmony/60460',
			['Hands'] = 'Keeper\'s Ascendant Gloves of Harmony/60461',
			['Legs'] = 'Keeper\'s Ascendant Legguards of Harmony/60462',
			['Feet'] = 'Keeper\'s Ascendant Boots of Harmony/60463',
			['Wrist2'] = 'Keeper\'s Eternal Bracer of Harmony/60464',
			['Ear1'] = 'Cloudkiller\'s Bauble/71584',
			['Ear2'] = 'Accursed Earhoop of Pain/71668',
			['Face'] = 'Mask of the Dawn Scorcher/71626',
			['Neck'] = 'Necklace of Sandstorms/71612',
			['Back'] = 'Cloak of Deepshadow/71665',
			['Shoulder'] = 'Lightning Singed Mantle/71654',
			['Waist'] = 'Thundercrash Girdle/71657',
			['Finger1'] = 'Glimmering Fire Opal Band/71634',
			['Finger2'] = 'Bloodstained Ring of Evisceration/71588',
			['Ranged'] = 'Head of the Putrid Drake/55052',
			['RangedAug'] = 'Preserved Eye of the Putrid Drake/71620',
			['Clicky1'] = 'Icon of Ancient Boon/56758',
			['Clicky2'] = 'Icon of Potent Prowess/56757',
			['Clicky3'] = 'Icon of Ancient Prowess/57142',
			['Shadow'] = 'Shadow of a Legendary Bard Weapon/60668',
			['Pack1'] = {
				item = 'Spell Pack: Cantata of Nife/82821',
				spells = {'Cantata of Nife'},
			},
			['Pack2'] = {
				item = 'Spell Pack: Symphony of Sound/82822',
				spells = {'Symphony of Sound'},
			},
			['Pack3'] = {
				item = 'Spell Pack: Echoes of the Ancient/82823',
				spells = {'Echoes of the Ancient'},
			},
			['Pack4'] = {
				item = 'Song: Niv\'s Symphonic/81935',
				spells = {'Niv\'s Symphonic'},
				spell_ids = {15264},
			},
			['Pack5'] = {
				item = 'Song: One Bard Band/78739',
				spells = {'One Bard Band'},
				spell_ids = {35234},
			},
			['Pack6'] = {
				item = 'Song: Squall Blade/50157',
				spells = {'Squall Blade Flourish'},
				spell_ids = {10940},
			},
			['Pack7'] = {
				item = 'Tome of Arcane Reprisal/79226',
				spells = {'Arcane Reprisal'},
				spell_ids = {10889},
			},
			['Pack8'] = {
				item = 'Tome of Endless Blades/50156',
				spells = {'Endless Blades'},
				spell_ids = {10939},
			},
			['Glyph1'] = 'Mnemonic Glyph: Cantata of Nife/80071',
			['Glyph2'] = 'Mnemonic Glyph: Symphony of Sound/80084',
			['Glyph3'] = 'Imbued Glyph: Echoes of the Ancient/80072',
			['Aug1'] = {
				item = 'Benevolent Extension',
				names = {'Benevolent Extension', 'Cryptic Clutch of Benevolent Extension', 'Vacant Vessel of Benevolent Extension'},
				ids = {62551, 63017},
				notes = '+40% beneficial spell duration | +10 hWIS',
			},
			['Aug2'] = {
				item = 'Malevolent Efficiency',
				names = {'Malevolent Efficiency', 'Cryptic Clutch of Malevolent Efficiency', 'Vacant Vessel of Malevolent Efficiency'},
				ids = {62540, 62560},
				notes = '-11–33% detrimental spell mana cost | +10 hINT',
			},
			['Aug3'] = {
				item = 'Expanded Reach',
				names = {'Expanded Reach', 'Cryptic Clutch of Expanded Reach', 'Vacant Vessel of Expanded Reach'},
				ids = {62552, 63018},
				notes = '+50% spell range | +10 hWIS, +10 hINT',
			},
			['Aug4'] = {
				item = 'Nimble Elusion',
				names = {'Nimble Elusion', 'Cryptic Clutch of Nimble Elusion', 'Vacant Vessel of Nimble Elusion'},
				ids = {62556, 64050},
				notes = '+70% dodge | +10 hAGI',
			},
			['Aug5'] = {
				item = 'Adept Guard',
				names = {'Adept Guard', 'Cryptic Clutch of Adept Guard', 'Vacant Vessel of Adept Guard'},
				ids = {62555, 64049},
				notes = '+70% parry, +70% block | +10 hSTA',
			},
			['Aug6'] = {
				item = 'Visceral Malice',
				names = {'Visceral Malice', 'Cryptic Clutch of Visceral Malice', 'Vacant Vessel of Visceral Malice'},
				ids = {62554, 63020},
				notes = '+300% melee critical damage | +10 hSTR',
			},
			['Aug7'] = {
				item = 'Wanton Assault',
				names = {'Wanton Assault', 'Cryptic Clutch of Wanton Assault', 'Vacant Vessel of Wanton Assault'},
				ids = {62553, 63019},
				notes = '+21% double attack, +7% triple attack, +5% chance to hit | +10 hSTR',
			},
			['Aug8'] = {
				item = 'Physical Prowess',
				names = {'Physical Prowess', 'Cryptic Clutch of Physical Prowess', 'Vacant Vessel of Physical Prowess'},
				ids = {62558, 66533},
				notes = 'No focus effect | +5 hSTR, +5 hSTA, +5 hAGI, +5 hDEX',
			},
		},
		['Beastlord'] = {
			['Head'] = 'Keeper\'s Ascendant Cap of the Wilds/60527',
			['Chest'] = 'Keeper\'s Ascendant Jerkin of the Wilds/60528',
			['Arms'] = 'Keeper\'s Ascendant Sleeves of the Wilds/60529',
			['Wrist1'] = 'Keeper\'s Ascendant Wristband of the Wilds/60530',
			['Hands'] = 'Keeper\'s Ascendant Gloves of the Wilds/60531',
			['Legs'] = 'Keeper\'s Ascendant Legguards of the Wilds/60532',
			['Feet'] = 'Keeper\'s Ascendant Sandals of the Wilds/60533',
			['Wrist2'] = 'Keeper\'s Eternal Bracer of the Wilds/60534',
			['Ear1'] = 'Hoop of the Drakeborn/71574',
			['Ear2'] = 'Accursed Earhoop of Pain/71668',
			['Face'] = 'Entrancing Silk Veil/71643',
			['Neck'] = 'Necklace of Sandstorms/71612',
			['Back'] = 'Cloak of Deepshadow/71665',
			['Shoulder'] = 'Brimstone Spaulders/71635',
			['Waist'] = 'Windwatcher Sash/71621',
			['Finger1'] = 'Thought Sieve Ring/71625',
			['Finger2'] = 'Bloodstained Ring of Evisceration/71588',
			['Ranged'] = 'Branch of the Twisting Tree/71627',
			['RangedAug'] = 'Fallen Leaf of the Twisting Tree/55053',
			['Clicky1'] = 'Icon of Ancient Boon/56758',
			['Clicky2'] = 'Icon of Potent Prowess/56757',
			['Clicky3'] = 'Icon of Ancient Prowess/57142',
			['Shadow'] = 'Shadow of a Legendary Beastlord Weapon/62534',
			['Pack1'] = {
				item = 'Spell Pack: Spiritual Vibrance/82817',
				spells = {'Spiritual Vibrance'},
			},
			['Pack2'] = {
				item = 'Spell Pack: Roaring Spirit of Tirranun/82818',
				spells = {'Roaring Spirit of Tirranun'},
			},
			['Pack3'] = {
				item = 'Spell Pack: Growl of the Mountain Puma/82819',
				spells = {'Growl of the Mountain Puma'},
			},
			['Pack4'] = {
				item = 'Spell Pack: Sha\'s Urgent Renewal/82820',
				spells = {'Sha\'s Urgent Renewal'},
			},
			['Pack5'] = {
				item = 'Spell: Feral Mettle/81933',
				spells = {'Feral Mettle'},
				spell_ids = {15261},
			},
			['Pack6'] = {
				item = 'Spell: Ravenous Ice/81934',
				spells = {'Ravenous Ice'},
				spell_ids = {15263},
			},
			['Pack7'] = {
				item = 'Spell: Roaring Sleet/78701',
				spells = {'Roaring Sleet'},
				spell_ids = {10364},
			},
			['Pack8'] = {
				item = 'Spell: Spiritual Enlightenment/81868',
				spells = {'Spiritual Enlightenment'},
				spell_ids = {15260},
			},
			['Pack9'] = {
				item = 'Spell: Swift Salve of the Stillmoon/81867',
				spells = {'Swift Salve of the Stillmoon'},
				spell_ids = {15257},
			},
			['Glyph1'] = 'Mnemonic Glyph: Spiritual Vibrance/80067',
			['Glyph2'] = 'Mnemonic Glyph: Roaring Spirit of Tirranun/80068',
			['Glyph3'] = 'Mnemonic Glyph: Growl of the Mountain Puma/80069',
			['Glyph4'] = 'Imbued Glyph: Sha\'s Urgent Renewal/80070',
			['Aug1'] = {
				item = 'Benevolent Extension',
				names = {'Benevolent Extension', 'Cryptic Clutch of Benevolent Extension', 'Vacant Vessel of Benevolent Extension'},
				ids = {62551, 63017},
				notes = '+40% beneficial spell duration | +10 hWIS',
			},
			['Aug2'] = {
				item = 'Malevolent Efficiency',
				names = {'Malevolent Efficiency', 'Cryptic Clutch of Malevolent Efficiency', 'Vacant Vessel of Malevolent Efficiency'},
				ids = {62540, 62560},
				notes = '-11–33% detrimental spell mana cost | +10 hINT',
			},
			['Aug3'] = {
				item = 'Malevolent Extension',
				names = {'Malevolent Extension', 'Cryptic Clutch of Malevolent Extension', 'Vacant Vessel of Malevolent Extension'},
				ids = {62550, 63016},
				notes = '+40% detrimental spell duration | +10 hINT',
			},
			['Aug4'] = {
				item = 'Noxious Demise',
				names = {'Noxious Demise', 'Cryptic Clutch of Noxious Demise', 'Vacant Vessel of Noxious Demise'},
				ids = {62547, 62567},
				notes = '+10–60% poison spell damage | +5 hINT, +25 hPR',
			},
			['Aug5'] = {
				item = 'Festering Demise',
				names = {'Festering Demise', 'Cryptic Clutch of Festering Demise', 'Vacant Vessel of Festering Demise'},
				ids = {62548, 62568},
				notes = '+10–60% disease spell damage | +5 hINT, +25 hDR',
			},
			['Aug6'] = {
				item = 'Merciful Mending',
				names = {'Merciful Mending', 'Cryptic Clutch of Merciful Mending', 'Vacant Vessel of Merciful Mending'},
				ids = {62549, 62569},
				notes = '+10–60% healing | +10 hWIS',
			},
			['Aug7'] = {
				item = 'Nimble Elusion',
				names = {'Nimble Elusion', 'Cryptic Clutch of Nimble Elusion', 'Vacant Vessel of Nimble Elusion'},
				ids = {62556, 64050},
				notes = '+70% dodge | +10 hAGI',
			},
			['Aug8'] = {
				item = 'Adept Guard',
				names = {'Adept Guard', 'Cryptic Clutch of Adept Guard', 'Vacant Vessel of Adept Guard'},
				ids = {62555, 64049},
				notes = '+70% parry, +70% block | +10 hSTA',
			},
			['Aug9'] = {
				item = 'Visceral Malice',
				names = {'Visceral Malice', 'Cryptic Clutch of Visceral Malice', 'Vacant Vessel of Visceral Malice'},
				ids = {62554, 63020},
				notes = '+300% melee critical damage | +10 hSTR',
			},
			['Aug10'] = {
				item = 'Wanton Assault',
				names = {'Wanton Assault', 'Cryptic Clutch of Wanton Assault', 'Vacant Vessel of Wanton Assault'},
				ids = {62553, 63019},
				notes = '+21% double attack, +7% triple attack, +5% chance to hit | +10 hSTR',
			},
			['Aug11'] = {
				item = 'Chilling Demise',
				names = {'Chilling Demise', 'Cryptic Clutch of Chilling Demise', 'Vacant Vessel of Chilling Demise'},
				ids = {62546, 62566},
				notes = '+10–60% cold spell damage | +5 hINT, +25 hCR',
			},
			['Aug12'] = {
				item = 'Physical Prowess',
				names = {'Physical Prowess', 'Cryptic Clutch of Physical Prowess', 'Vacant Vessel of Physical Prowess'},
				ids = {62558, 66533},
				notes = 'No focus effect | +5 hSTR, +5 hSTA, +5 hAGI, +5 hDEX',
			},
		},
		['Berserker'] = {
			['Head'] = 'Keeper\'s Ascendant Helm of the Vindicator/60449',
			['Chest'] = 'Keeper\'s Ascendant Chestguard of the Vindicator/60450',
			['Arms'] = 'Keeper\'s Ascendant Sleeves of the Vindicator/60451',
			['Wrist1'] = 'Keeper\'s Ascendant Wristguard of the Vindicator/60452',
			['Hands'] = 'Keeper\'s Ascendant Gloves of the Vindicator/60453',
			['Legs'] = 'Keeper\'s Ascendant Leggings of the Vindicator/60454',
			['Feet'] = 'Keeper\'s Ascendant Boots of the Vindicator/60455',
			['Wrist2'] = 'Keeper\'s Eternal Bracer of the Vindicator/60456',
			['Ear1'] = 'Cloudkiller\'s Bauble/71584',
			['Ear2'] = 'Accursed Earhoop of Pain/71668',
			['Face'] = 'Mask of the Dawn Scorcher/71626',
			['Neck'] = 'Necklace of Sandstorms/71612',
			['Back'] = 'Cloak of Deepshadow/71665',
			['Shoulder'] = 'Lightning Singed Mantle/71654',
			['Waist'] = 'Thundercrash Girdle/71657',
			['Finger1'] = 'Glimmering Fire Opal Band/71634',
			['Finger2'] = 'Bloodstained Ring of Evisceration/71588',
			['Ranged'] = 'Head of the Putrid Drake/55052',
			['RangedAug'] = 'Preserved Eye of the Putrid Drake/71620',
			['Clicky1'] = 'Icon of Ancient Boon/56758',
			['Clicky2'] = 'Icon of Potent Prowess/56757',
			['Clicky3'] = 'Icon of Ancient Prowess/57142',
			['Shadow'] = 'Shadow of a Legendary Berserker Augment/60667',
			['Pack1'] = {
				item = 'Tome Pack: Ancient: Annihilator\'s Volley/82657',
				spells = {'Ancient: Annihilator\'s Volley'},
			},
			['Pack2'] = {
				item = 'Tome of Arcane Reprisal/79226',
				spells = {'Arcane Reprisal'},
				spell_ids = {10889},
			},
			['Pack3'] = {
				item = 'Tome of Battle Focus Discipline/59925',
				spells = {'Battle Focus Discipline'},
				spell_ids = {5038},
			},
			['Pack4'] = {
				item = 'Tome of Bloodcurdling Scream/79251',
				spells = {'Bloodcurdling Scream'},
				spell_ids = {10915},
			},
			['Pack5'] = {
				item = 'Tome of Cleaving Madness Discipline/50120',
				spells = {'Cleaving Madness Discipline'},
				spell_ids = {10860},
			},
			['Pack6'] = {
				item = 'Tome of Cry of Catastrophe/50118',
				spells = {'Cry of Catastrophe'},
				spell_ids = {10857},
			},
			['Pack7'] = {
				item = 'Tome of Fourth Wind/80081',
				spells = {'Fourth Wind Discipline'},
				spell_ids = {15134},
			},
			['Pack8'] = {
				item = 'Tome of Rancorous Flurry Discipline/80280',
				spells = {'Rancorous Flurry Discipline'},
				spell_ids = {15120},
			},
			['Pack9'] = {
				item = 'Tome of Vigorous Axe Throw/50119',
				spells = {'Vigorous Axe Throw'},
				spell_ids = {10858},
			},
			['Pack10'] = {
				item = 'Tome of Wounded Rage Discipline/80281',
				spells = {'Wounding Rage'},
				spell_ids = {15122},
			},
			['Glyph1'] = 'Imbued Glyph: Ancient: Annihilator\'s Volley/80076',
			['Aug1'] = {
				item = 'Benevolent Extension',
				names = {'Benevolent Extension', 'Cryptic Clutch of Benevolent Extension', 'Vacant Vessel of Benevolent Extension'},
				ids = {62551, 63017},
				notes = '+40% beneficial spell duration | +10 hWIS',
			},
			['Aug2'] = {
				item = 'Malevolent Extension',
				names = {'Malevolent Extension', 'Cryptic Clutch of Malevolent Extension', 'Vacant Vessel of Malevolent Extension'},
				ids = {62550, 63016},
				notes = '+40% detrimental spell duration | +10 hINT',
			},
			['Aug3'] = {
				item = 'Noxious Demise',
				names = {'Noxious Demise', 'Cryptic Clutch of Noxious Demise', 'Vacant Vessel of Noxious Demise'},
				ids = {62547, 62567},
				notes = '+10–60% poison spell damage | +5 hINT, +25 hPR',
			},
			['Aug4'] = {
				item = 'Nimble Elusion',
				names = {'Nimble Elusion', 'Cryptic Clutch of Nimble Elusion', 'Vacant Vessel of Nimble Elusion'},
				ids = {62556, 64050},
				notes = '+70% dodge | +10 hAGI',
			},
			['Aug5'] = {
				item = 'Adept Guard',
				names = {'Adept Guard', 'Cryptic Clutch of Adept Guard', 'Vacant Vessel of Adept Guard'},
				ids = {62555, 64049},
				notes = '+70% parry, +70% block | +10 hSTA',
			},
			['Aug6'] = {
				item = 'Visceral Malice',
				names = {'Visceral Malice', 'Cryptic Clutch of Visceral Malice', 'Vacant Vessel of Visceral Malice'},
				ids = {62554, 63020},
				notes = '+300% melee critical damage | +10 hSTR',
			},
			['Aug7'] = {
				item = 'Wanton Assault',
				names = {'Wanton Assault', 'Cryptic Clutch of Wanton Assault', 'Vacant Vessel of Wanton Assault'},
				ids = {62553, 63019},
				notes = '+21% double attack, +7% triple attack, +5% chance to hit | +10 hSTR',
			},
			['Aug8'] = {
				item = 'Lethal Barrage',
				names = {'Lethal Barrage', 'Cryptic Clutch of Lethal Barrage', 'Vacant Vessel of Lethal Barrage'},
				ids = {62557, 64326},
				notes = '+28% archery and throwing chance to hit | +20 hDEX',
			},
			['Aug9'] = {
				item = 'Physical Prowess',
				names = {'Physical Prowess', 'Cryptic Clutch of Physical Prowess', 'Vacant Vessel of Physical Prowess'},
				ids = {62558, 66533},
				notes = 'No focus effect | +5 hSTR, +5 hSTA, +5 hAGI, +5 hDEX',
			},
		},
		['Cleric'] = {
			['Head'] = 'Keeper\'s Ascendant Cap of Conviction/57144',
			['Chest'] = 'Keeper\'s Ascendant Breastplate of Conviction/57145',
			['Arms'] = 'Keeper\'s Ascendant Armguards of Conviction/57146',
			['Wrist1'] = 'Keeper\'s Ascendant Wristband of Conviction/57147',
			['Hands'] = 'Keeper\'s Ascendant Gloves of Conviction/57148',
			['Legs'] = 'Keeper\'s Ascendant Leggings of Conviction/57149',
			['Feet'] = 'Keeper\'s Ascendant Boots of Conviction/57150',
			['Wrist2'] = 'Keeper\'s Eternal Bracer of Conviction/57151',
			['Ear1'] = 'Earring of Contemplation/71589',
			['Ear2'] = 'Tear of Kessdona/71642',
			['Face'] = 'Young Dragon Mask/71594',
			['Neck'] = 'Locket of Raining Tears/71655',
			['Back'] = 'Cape of Serenity/71613',
			['Shoulder'] = 'Obsidian Pauldrons/71666',
			['Waist'] = 'Windwatcher Sash/71621',
			['Finger1'] = 'Dragon Nursery Ring/71592',
			['Finger2'] = 'Eye of Tirranun/71652',
			['Ranged'] = 'Crux of the First Brood/60535',
			['RangedAug'] = 'Phial of the First Brood/71578',
			['Clicky1'] = 'Icon of Ancient Boon/56758',
			['Clicky2'] = 'Icon of Scribe\'s Endurance/56756',
			['Clicky3'] = 'Icon of the Ancient Scribe/57143',
			['Shadow'] = 'Shadow of a Legendary Cleric Staff/60546',
			['Pack1'] = {
				item = 'Spell Pack: Allegiance/82658',
				spells = {'Allegiance', 'Hand of Allegiance', 'Symbol of Elushar'},
			},
			['Pack2'] = {
				item = 'Spell Pack: Armor of the Sacred/82660',
				spells = {'Armor of the Sacred'},
			},
			['Pack3'] = {
				item = 'Spell Pack: Aegis of Vie/82661',
				spells = {'Aegis of Vie'},
			},
			['Pack4'] = {
				item = 'Spell: Chromablast/80284',
				spells = {'Chromablast'},
				spell_ids = {15140},
			},
			['Pack5'] = {
				item = 'Spell: Divine Redemption/124941',
				spells = {'Divine Redemption'},
				spell_ids = {25252},
			},
			['Pack6'] = {
				item = 'Spell: Elixir of Redemption/78149',
				spells = {'Elixir of Redemption'},
				spell_ids = {9812},
			},
			['Pack7'] = {
				item = 'Spell: Sound of Zeal/78086',
				spells = {'Sound of Zeal'},
				spell_ids = {9749},
			},
			['Pack8'] = {
				item = 'Spell: Urgent Renewal/80282',
				spells = {'Urgent Renewal'},
				spell_ids = {15135},
			},
			['Pack9'] = {
				item = 'Spell: Vigilant Censure/80283',
				spells = {'Vigilant Censure'},
				spell_ids = {15137},
			},
			['Glyph1'] = 'Mnemonic Glyph: Allegiance/76563',
			['Glyph2'] = 'Mnemonic Glyph: Hand of Allegiance/76564',
			['Glyph3'] = 'Mnemonic Glyph: Symbol of Elushar/76565',
			['Glyph4'] = 'Mnemonic Glyph: Armor of the Sacred/76566',
			['Glyph5'] = 'Imbued Glyph: Aegis of Vie/76567',
			['Aug1'] = {
				item = 'Benevolent Efficiency',
				names = {'Benevolent Efficiency', 'Cryptic Clutch of Benevolent Efficiency', 'Vacant Vessel of Benevolent Efficiency'},
				ids = {62541, 62561},
				notes = '-11–33% beneficial spell mana cost | +10 hWIS',
			},
			['Aug2'] = {
				item = 'Benevolent Extension',
				names = {'Benevolent Extension', 'Cryptic Clutch of Benevolent Extension', 'Vacant Vessel of Benevolent Extension'},
				ids = {62551, 63017},
				notes = '+40% beneficial spell duration | +10 hWIS',
			},
			['Aug3'] = {
				item = 'Benevolent Alacrity',
				names = {'Benevolent Alacrity', 'Cryptic Clutch of Benevolent Alacrity', 'Vacant Vessel of Benevolent Alacrity'},
				ids = {62543, 62563},
				notes = '-40% beneficial spell cast time | +10 hWIS',
			},
			['Aug4'] = {
				item = 'Malevolent Efficiency',
				names = {'Malevolent Efficiency', 'Cryptic Clutch of Malevolent Efficiency', 'Vacant Vessel of Malevolent Efficiency'},
				ids = {62540, 62560},
				notes = '-11–33% detrimental spell mana cost | +10 hINT',
			},
			['Aug5'] = {
				item = 'Malevolent Extension',
				names = {'Malevolent Extension', 'Cryptic Clutch of Malevolent Extension', 'Vacant Vessel of Malevolent Extension'},
				ids = {62550, 63016},
				notes = '+40% detrimental spell duration | +10 hINT',
			},
			['Aug6'] = {
				item = 'Malevolent Alacrity',
				names = {'Malevolent Alacrity', 'Cryptic Clutch of Malevolent Alacrity', 'Vacant Vessel of Malevolent Alacrity'},
				ids = {62542, 62562},
				notes = '-40% detrimental spell cast time | +10 hINT',
			},
			['Aug7'] = {
				item = 'Arcane Demise',
				names = {'Arcane Demise', 'Cryptic Clutch of Arcane Demise', 'Vacant Vessel of Arcane Demise'},
				ids = {62544, 62564},
				notes = '+10–60% magic spell damage | +5 hINT, +25 hMR',
			},
			['Aug8'] = {
				item = 'Expanded Reach',
				names = {'Expanded Reach', 'Cryptic Clutch of Expanded Reach', 'Vacant Vessel of Expanded Reach'},
				ids = {62552, 63018},
				notes = '+50% spell range | +10 hWIS, +10 hINT',
			},
			['Aug9'] = {
				item = 'Merciful Mending',
				names = {'Merciful Mending', 'Cryptic Clutch of Merciful Mending', 'Vacant Vessel of Merciful Mending'},
				ids = {62549, 62569},
				notes = '+10–60% healing | +10 hWIS',
			},
			['Aug10'] = {
				item = 'Nimble Elusion',
				names = {'Nimble Elusion', 'Cryptic Clutch of Nimble Elusion', 'Vacant Vessel of Nimble Elusion'},
				ids = {62556, 64050},
				notes = '+70% dodge | +10 hAGI',
			},
			['Aug11'] = {
				item = 'Mental Prowess',
				names = {'Mental Prowess', 'Cryptic Clutch of Mental Prowess', 'Vacant Vessel of Mental Prowess'},
				ids = {62559, 66720},
				notes = 'No focus effect | +10 hINT, +10 hWIS, +10 heroic resists',
			},
		},
		['Druid'] = {
			['Head'] = 'Keeper\'s Ascendant Cap of the Tangled Briars/57160',
			['Chest'] = 'Keeper\'s Ascendant Jerkin of the Tangled Briars/57161',
			['Arms'] = 'Keeper\'s Ascendant Sleeves of the Tangled Briars/57162',
			['Wrist1'] = 'Keeper\'s Ascendant Wristband of the Tangled Briars/57163',
			['Hands'] = 'Keeper\'s Ascendant Mitts of the Tangled Briars/57164',
			['Legs'] = 'Keeper\'s Ascendant Pants of the Tangled Briars/57165',
			['Feet'] = 'Keeper\'s Ascendant Slippers of the Tangled Briars/57178',
			['Wrist2'] = 'Keeper\'s Eternal Bracer of the Tangled Briars/57179',
			['Ear1'] = 'Earring of Contemplation/71589',
			['Ear2'] = 'Tear of Kessdona/71642',
			['Face'] = 'Young Dragon Mask/71594',
			['Neck'] = 'Locket of Raining Tears/71655',
			['Back'] = 'Cape of Serenity/71613',
			['Shoulder'] = 'Obsidian Pauldrons/71666',
			['Waist'] = 'Windwatcher Sash/71621',
			['Finger1'] = 'Dragon Nursery Ring/71592',
			['Finger2'] = 'Eye of Tirranun/71652',
			['Ranged'] = 'Crux of the First Brood/60535',
			['RangedAug'] = 'Phial of the First Brood/71578',
			['Clicky1'] = 'Icon of Ancient Boon/56758',
			['Clicky2'] = 'Icon of Scribe\'s Endurance/56756',
			['Clicky3'] = 'Icon of the Ancient Scribe/57143',
			['Shadow'] = 'Shadow of a Legendary Druid Staff/60548',
			['Pack1'] = {
				item = 'Spell Pack: Spiritoaks/82688',
				spells = {'Spiritoak Skin', 'Blessing of Spiritoak'},
			},
			['Pack2'] = {
				item = 'Spell Pack: Clumped Moss/82777',
				spells = {'Mossy Vigor', 'Blessing of Moss'},
			},
			['Pack3'] = {
				item = 'Spell Pack: Sun\'s Blistering Corona/82778',
				spells = {'Sun\'s Blistering Corona'},
			},
			['Pack4'] = {
				item = 'Spell: Ascent Frost/80757',
				spells = {'Ascent Frost'},
				spell_ids = {15153},
			},
			['Pack5'] = {
				item = 'Spell: Breath of the Ascent/78200',
				spells = {'Breath of The Ascent'},
				spell_ids = {9863},
			},
			['Pack6'] = {
				item = 'Spell: Dawnflame/80758',
				spells = {'Dawnflame'},
				spell_ids = {15156},
			},
			['Pack7'] = {
				item = 'Spell: Lunar Shadow/80759',
				spells = {'Lunar Shadow'},
				spell_ids = {15165},
			},
			['Pack8'] = {
				item = 'Spell: Nature Seeker\'s Behest/117592',
				spells = {'Nature Seeker\'s Behest'},
				spell_ids = {10839},
			},
			['Pack9'] = {
				item = 'Spell: Sunburst Devotion/80756',
				spells = {'Sunburst Devotion'},
				spell_ids = {15152},
			},
			['Glyph1'] = 'Mnemonic Glyph: Spiritoak Skin/76573',
			['Glyph2'] = 'Mnemonic Glyph: Blessing of Spiritoak/78227',
			['Glyph3'] = 'Mnemonic Glyph: Mossy Vigor/79518',
			['Glyph4'] = 'Mnemonic Glyph: Blessing of Moss/79519',
			['Glyph5'] = 'Imbued Glyph: Sun\'s Blistering Corona/79520',
			['Aug1'] = {
				item = 'Benevolent Efficiency',
				names = {'Benevolent Efficiency', 'Cryptic Clutch of Benevolent Efficiency', 'Vacant Vessel of Benevolent Efficiency'},
				ids = {62541, 62561},
				notes = '-11–33% beneficial spell mana cost | +10 hWIS',
			},
			['Aug2'] = {
				item = 'Benevolent Extension',
				names = {'Benevolent Extension', 'Cryptic Clutch of Benevolent Extension', 'Vacant Vessel of Benevolent Extension'},
				ids = {62551, 63017},
				notes = '+40% beneficial spell duration | +10 hWIS',
			},
			['Aug3'] = {
				item = 'Benevolent Alacrity',
				names = {'Benevolent Alacrity', 'Cryptic Clutch of Benevolent Alacrity', 'Vacant Vessel of Benevolent Alacrity'},
				ids = {62543, 62563},
				notes = '-40% beneficial spell cast time | +10 hWIS',
			},
			['Aug4'] = {
				item = 'Malevolent Efficiency',
				names = {'Malevolent Efficiency', 'Cryptic Clutch of Malevolent Efficiency', 'Vacant Vessel of Malevolent Efficiency'},
				ids = {62540, 62560},
				notes = '-11–33% detrimental spell mana cost | +10 hINT',
			},
			['Aug5'] = {
				item = 'Malevolent Extension',
				names = {'Malevolent Extension', 'Cryptic Clutch of Malevolent Extension', 'Vacant Vessel of Malevolent Extension'},
				ids = {62550, 63016},
				notes = '+40% detrimental spell duration | +10 hINT',
			},
			['Aug6'] = {
				item = 'Malevolent Alacrity',
				names = {'Malevolent Alacrity', 'Cryptic Clutch of Malevolent Alacrity', 'Vacant Vessel of Malevolent Alacrity'},
				ids = {62542, 62562},
				notes = '-40% detrimental spell cast time | +10 hINT',
			},
			['Aug7'] = {
				item = 'Fiery Demise',
				names = {'Fiery Demise', 'Cryptic Clutch of Fiery Demise', 'Vacant Vessel of Fiery Demise'},
				ids = {62545, 62565},
				notes = '+10–60% fire spell damage | +5 hINT, +25 hFR',
			},
			['Aug8'] = {
				item = 'Arcane Demise',
				names = {'Arcane Demise', 'Cryptic Clutch of Arcane Demise', 'Vacant Vessel of Arcane Demise'},
				ids = {62544, 62564},
				notes = '+10–60% magic spell damage | +5 hINT, +25 hMR',
			},
			['Aug9'] = {
				item = 'Expanded Reach',
				names = {'Expanded Reach', 'Cryptic Clutch of Expanded Reach', 'Vacant Vessel of Expanded Reach'},
				ids = {62552, 63018},
				notes = '+50% spell range | +10 hWIS, +10 hINT',
			},
			['Aug10'] = {
				item = 'Merciful Mending',
				names = {'Merciful Mending', 'Cryptic Clutch of Merciful Mending', 'Vacant Vessel of Merciful Mending'},
				ids = {62549, 62569},
				notes = '+10–60% healing | +10 hWIS',
			},
			['Aug11'] = {
				item = 'Nimble Elusion',
				names = {'Nimble Elusion', 'Cryptic Clutch of Nimble Elusion', 'Vacant Vessel of Nimble Elusion'},
				ids = {62556, 64050},
				notes = '+70% dodge | +10 hAGI',
			},
			['Aug12'] = {
				item = 'Mental Prowess',
				names = {'Mental Prowess', 'Cryptic Clutch of Mental Prowess', 'Vacant Vessel of Mental Prowess'},
				ids = {62559, 66720},
				notes = 'No focus effect | +10 hINT, +10 hWIS, +10 heroic resists',
			},
		},
		['Enchanter'] = {
			['Head'] = 'Keeper\'s Ascendant Skullcap of Coercion/60503',
			['Chest'] = 'Keeper\'s Ascendant Vest of Coercion/60504',
			['Arms'] = 'Keeper\'s Ascendant Armguards of Coercion/60505',
			['Wrist1'] = 'Keeper\'s Ascendant Bracer of Coercion/60506',
			['Hands'] = 'Keeper\'s Ascendant Handguards of Coercion/60507',
			['Legs'] = 'Keeper\'s Ascendant Leggings of Coercion/60508',
			['Feet'] = 'Keeper\'s Ascendant Shoes of Coercion/60509',
			['Wrist2'] = 'Keeper\'s Eternal Bracer of Coercion/60510',
			['Ear1'] = 'Hoop of the Drakeborn/71574',
			['Ear2'] = 'Grelian Earring of Uncertainty/71603',
			['Face'] = 'Entrancing Silk Veil/71643',
			['Neck'] = 'Choker of One Hundred Diamonds/71651',
			['Back'] = 'Shroud of the Surging Storm/71656',
			['Shoulder'] = 'Brimstone Spaulders/71635',
			['Waist'] = 'Sash of Frigidity/71650',
			['Finger1'] = 'Thought Sieve Ring/71625',
			['Finger2'] = 'Stormeye Band/71658',
			['Ranged'] = 'Spark of the Skies/60536',
			['RangedAug'] = 'Core of the Skies/71659',
			['Clicky1'] = 'Icon of Ancient Boon/56758',
			['Clicky2'] = 'Icon of Scribe\'s Endurance/56756',
			['Clicky3'] = 'Icon of the Ancient Scribe/57143',
			['Shadow'] = 'Shadow of a Legendary Enchanter Shield/62531',
			['Pack1'] = {
				item = 'Spell Pack: Intuition/82801',
				spells = {'Seer\'s Intuition', 'Voice of Intuition'},
			},
			['Pack2'] = {
				item = 'Spell Pack: Ellowind Hastening/82802',
				spells = {'Speed of Ellowind', 'Hastening of Ellowind'},
			},
			['Pack3'] = {
				item = 'Spell Pack: Presidio of the Seer/82803',
				spells = {'Presidio of the Seer'},
			},
			['Pack4'] = {
				item = 'Spell Pack: Edict of Tashan/82804',
				spells = {'Edict of Tashan'},
			},
			['Pack5'] = {
				item = 'Spell: Boon of the Sentinel/50149',
				spells = {'Boon of the Sentinel'},
				spell_ids = {10902},
			},
			['Pack6'] = {
				item = 'Spell: Chromatic Chaos/80781',
				spells = {'Chromatic Chaos'},
				spell_ids = {15212},
			},
			['Pack7'] = {
				item = 'Spell: Hysteria/80783',
				spells = {'Hysteria'},
				spell_ids = {15216},
			},
			['Pack8'] = {
				item = 'Spell: Urgent Rune of Destiny/80782',
				spells = {'Urgent Rune of Destiny'},
				spell_ids = {15213},
			},
			['Pack9'] = {
				item = 'Spell: Whispers of Emoush/80780',
				spells = {'Whispers of Emoush'},
				spell_ids = {10656},
			},
			['Glyph1'] = 'Mnemonic Glyph: Seer\'s Intuition/79529',
			['Glyph2'] = 'Mnemonic Glyph: Voice of Intuition/79530',
			['Glyph3'] = 'Mnemonic Glyph: Speed of Ellowind/79531',
			['Glyph4'] = 'Mnemonic Glyph: Hastening of Ellowind/79532',
			['Glyph5'] = 'Mnemonic Glyph: Presidio of the Seer/79533',
			['Glyph6'] = 'Imbued Glyph: Edict of Tashan/79534',
			['Aug1'] = {
				item = 'Benevolent Efficiency',
				names = {'Benevolent Efficiency', 'Cryptic Clutch of Benevolent Efficiency', 'Vacant Vessel of Benevolent Efficiency'},
				ids = {62541, 62561},
				notes = '-11–33% beneficial spell mana cost | +10 hWIS',
			},
			['Aug2'] = {
				item = 'Benevolent Extension',
				names = {'Benevolent Extension', 'Cryptic Clutch of Benevolent Extension', 'Vacant Vessel of Benevolent Extension'},
				ids = {62551, 63017},
				notes = '+40% beneficial spell duration | +10 hWIS',
			},
			['Aug3'] = {
				item = 'Benevolent Alacrity',
				names = {'Benevolent Alacrity', 'Cryptic Clutch of Benevolent Alacrity', 'Vacant Vessel of Benevolent Alacrity'},
				ids = {62543, 62563},
				notes = '-40% beneficial spell cast time | +10 hWIS',
			},
			['Aug4'] = {
				item = 'Malevolent Efficiency',
				names = {'Malevolent Efficiency', 'Cryptic Clutch of Malevolent Efficiency', 'Vacant Vessel of Malevolent Efficiency'},
				ids = {62540, 62560},
				notes = '-11–33% detrimental spell mana cost | +10 hINT',
			},
			['Aug5'] = {
				item = 'Malevolent Extension',
				names = {'Malevolent Extension', 'Cryptic Clutch of Malevolent Extension', 'Vacant Vessel of Malevolent Extension'},
				ids = {62550, 63016},
				notes = '+40% detrimental spell duration | +10 hINT',
			},
			['Aug6'] = {
				item = 'Malevolent Alacrity',
				names = {'Malevolent Alacrity', 'Cryptic Clutch of Malevolent Alacrity', 'Vacant Vessel of Malevolent Alacrity'},
				ids = {62542, 62562},
				notes = '-40% detrimental spell cast time | +10 hINT',
			},
			['Aug7'] = {
				item = 'Arcane Demise',
				names = {'Arcane Demise', 'Cryptic Clutch of Arcane Demise', 'Vacant Vessel of Arcane Demise'},
				ids = {62544, 62564},
				notes = '+10–60% magic spell damage | +5 hINT, +25 hMR',
			},
			['Aug8'] = {
				item = 'Expanded Reach',
				names = {'Expanded Reach', 'Cryptic Clutch of Expanded Reach', 'Vacant Vessel of Expanded Reach'},
				ids = {62552, 63018},
				notes = '+50% spell range | +10 hWIS, +10 hINT',
			},
			['Aug9'] = {
				item = 'Nimble Elusion',
				names = {'Nimble Elusion', 'Cryptic Clutch of Nimble Elusion', 'Vacant Vessel of Nimble Elusion'},
				ids = {62556, 64050},
				notes = '+70% dodge | +10 hAGI',
			},
			['Aug10'] = {
				item = 'Mental Prowess',
				names = {'Mental Prowess', 'Cryptic Clutch of Mental Prowess', 'Vacant Vessel of Mental Prowess'},
				ids = {62559, 66720},
				notes = 'No focus effect | +10 hINT, +10 hWIS, +10 heroic resists',
			},
		},
		['Magician'] = {
			['Head'] = 'Keeper\'s Ascendant Hat of the Summoner/60473',
			['Chest'] = 'Keeper\'s Ascendant Tunic of the Summoner/60474',
			['Arms'] = 'Keeper\'s Ascendant Sleeves of the Summoner/60475',
			['Wrist1'] = 'Keeper\'s Ascendant Wristband of the Summoner/60476',
			['Hands'] = 'Keeper\'s Ascendant Gloves of the Summoner/60477',
			['Legs'] = 'Keeper\'s Ascendant Leggings of the Summoner/60500',
			['Feet'] = 'Keeper\'s Ascendant Slippers of the Summoner/60501',
			['Wrist2'] = 'Keeper\'s Eternal Bracer of the Summoner/60502',
			['Ear1'] = 'Hoop of the Drakeborn/71574',
			['Ear2'] = 'Grelian Earring of Uncertainty/71603',
			['Face'] = 'Entrancing Silk Veil/71643',
			['Neck'] = 'Choker of One Hundred Diamonds/71651',
			['Back'] = 'Shroud of the Surging Storm/71656',
			['Shoulder'] = 'Brimstone Spaulders/71635',
			['Waist'] = 'Sash of Frigidity/71650',
			['Finger1'] = 'Thought Sieve Ring/71625',
			['Finger2'] = 'Stormeye Band/71658',
			['Ranged'] = 'Spark of the Skies/60536',
			['RangedAug'] = 'Core of the Skies/71659',
			['Clicky1'] = 'Icon of Ancient Boon/56758',
			['Clicky2'] = 'Icon of Scribe\'s Endurance/56756',
			['Clicky3'] = 'Icon of the Ancient Scribe/57143',
			['Shadow'] = 'Shadow of a Legendary Magician Staff/62530',
			['Pack1'] = {
				item = 'Spell Pack: Ward of the Conjurer/82798',
				spells = {'Ward of the Conjurer'},
			},
			['Pack2'] = {
				item = 'Spell Pack: Circle of Magmaskin/82799',
				spells = {'Circle of Magmaskin'},
			},
			['Pack3'] = {
				item = 'Spell Pack: Goner\'s Urgent Renewal/82800',
				spells = {'Goner\'s Urgent Renewal'},
			},
			['Pack4'] = {
				item = 'Spell: Blade Rend/80766',
				spells = {'Blade Rend'},
				spell_ids = {15191},
			},
			['Pack5'] = {
				item = 'Spell: Burning Bladestorm/50144',
				spells = {'Burning Bladestorm'},
				spell_ids = {10890},
			},
			['Pack6'] = {
				item = 'Spell: Fickle Inferno/79091',
				spells = {'Fickle Inferno'},
				spell_ids = {10754},
			},
			['Pack7'] = {
				item = 'Spell: Frantic Blaze/80764',
				spells = {'Frantic Blaze'},
				spell_ids = {15182},
			},
			['Pack8'] = {
				item = 'Spell: Grant Battle Materiel/80779',
				spells = {'Grant Battle Materiel'},
				spell_ids = {15192},
			},
			['Pack9'] = {
				item = 'Spell: Monolithic Strength/80765',
				spells = {'Monolithic Strength'},
				spell_ids = {15188},
			},
			['Glyph1'] = 'Mnemonic Glyph: Ward of the Conjurer/79524',
			['Glyph2'] = 'Mnemonic Glyph: Circle of Magmaskin/79525',
			['Glyph3'] = 'Imbued Glyph: Goner\'s Urgent Renewal/79526',
			['Aug1'] = {
				item = 'Benevolent Extension',
				names = {'Benevolent Extension', 'Cryptic Clutch of Benevolent Extension', 'Vacant Vessel of Benevolent Extension'},
				ids = {62551, 63017},
				notes = '+40% beneficial spell duration | +10 hWIS',
			},
			['Aug2'] = {
				item = 'Benevolent Alacrity',
				names = {'Benevolent Alacrity', 'Cryptic Clutch of Benevolent Alacrity', 'Vacant Vessel of Benevolent Alacrity'},
				ids = {62543, 62563},
				notes = '-40% beneficial spell cast time | +10 hWIS',
			},
			['Aug3'] = {
				item = 'Malevolent Efficiency',
				names = {'Malevolent Efficiency', 'Cryptic Clutch of Malevolent Efficiency', 'Vacant Vessel of Malevolent Efficiency'},
				ids = {62540, 62560},
				notes = '-11–33% detrimental spell mana cost | +10 hINT',
			},
			['Aug4'] = {
				item = 'Malevolent Extension',
				names = {'Malevolent Extension', 'Cryptic Clutch of Malevolent Extension', 'Vacant Vessel of Malevolent Extension'},
				ids = {62550, 63016},
				notes = '+40% detrimental spell duration | +10 hINT',
			},
			['Aug5'] = {
				item = 'Malevolent Alacrity',
				names = {'Malevolent Alacrity', 'Cryptic Clutch of Malevolent Alacrity', 'Vacant Vessel of Malevolent Alacrity'},
				ids = {62542, 62562},
				notes = '-40% detrimental spell cast time | +10 hINT',
			},
			['Aug6'] = {
				item = 'Fiery Demise',
				names = {'Fiery Demise', 'Cryptic Clutch of Fiery Demise', 'Vacant Vessel of Fiery Demise'},
				ids = {62545, 62565},
				notes = '+10–60% fire spell damage | +5 hINT, +25 hFR',
			},
			['Aug7'] = {
				item = 'Expanded Reach',
				names = {'Expanded Reach', 'Cryptic Clutch of Expanded Reach', 'Vacant Vessel of Expanded Reach'},
				ids = {62552, 63018},
				notes = '+50% spell range | +10 hWIS, +10 hINT',
			},
			['Aug8'] = {
				item = 'Nimble Elusion',
				names = {'Nimble Elusion', 'Cryptic Clutch of Nimble Elusion', 'Vacant Vessel of Nimble Elusion'},
				ids = {62556, 64050},
				notes = '+70% dodge | +10 hAGI',
			},
			['Aug9'] = {
				item = 'Mental Prowess',
				names = {'Mental Prowess', 'Cryptic Clutch of Mental Prowess', 'Vacant Vessel of Mental Prowess'},
				ids = {62559, 66720},
				notes = 'No focus effect | +10 hINT, +10 hWIS, +10 heroic resists',
			},
		},
		['Monk'] = {
			['Head'] = 'Keeper\'s Ascendant Cap of the Focused/57233',
			['Chest'] = 'Keeper\'s Ascendant Shroud of the Focused/57234',
			['Arms'] = 'Keeper\'s Ascendant Sleeves of the Focused/57711',
			['Wrist1'] = 'Keeper\'s Ascendant Wristband of the Focused/59168',
			['Hands'] = 'Keeper\'s Ascendant Gloves of the Focused/59169',
			['Legs'] = 'Keeper\'s Ascendant Leggings of the Focused/59170',
			['Feet'] = 'Keeper\'s Ascendant Tabis of the Focused/59357',
			['Wrist2'] = 'Keeper\'s Eternal Bracer of the Focused/59358',
			['Ear1'] = 'Cloudkiller\'s Bauble/71584',
			['Ear2'] = 'Accursed Earhoop of Pain/71668',
			['Face'] = 'Mask of the Dawn Scorcher/71626',
			['Neck'] = 'Necklace of Sandstorms/71612',
			['Back'] = 'Cloak of Deepshadow/71665',
			['Shoulder'] = 'Lightning Singed Mantle/71654',
			['Waist'] = 'Thundercrash Girdle/71657',
			['Finger1'] = 'Glimmering Fire Opal Band/71634',
			['Finger2'] = 'Bloodstained Ring of Evisceration/71588',
			['Ranged'] = 'Head of the Putrid Drake/55052',
			['RangedAug'] = 'Preserved Eye of the Putrid Drake/71620',
			['Clicky1'] = 'Icon of Ancient Boon/56758',
			['Clicky2'] = 'Icon of Potent Prowess/56757',
			['Clicky3'] = 'Icon of Ancient Prowess/57142',
			['Shadow'] = 'Shadow of a Legendary Monk Weapon/60549',
			['Pack1'] = {
				item = 'Tome Pack: Ancient: Arachnid Fang/82655',
				spells = {'Ancient: Arachnid Fang'},
			},
			['Pack2'] = {
				item = 'Tome of Arcane Reprisal/79226',
				spells = {'Arcane Reprisal'},
				spell_ids = {10889},
			},
			['Pack3'] = {
				item = 'Tome of Dragondance Discipline/88921',
				spells = {'Dragondance Discipline'},
				spell_ids = {15113},
			},
			['Pack4'] = {
				item = 'Tome of Fists of Thundercrest/50117',
				spells = {'Fists of Thundercrest'},
				spell_ids = {10854},
			},
			['Pack5'] = {
				item = 'Tome of Fourth Wind/80081',
				spells = {'Fourth Wind Discipline'},
				spell_ids = {15134},
			},
			['Pack6'] = {
				item = 'Tome of Grandmaster\'s Aura/80078',
				spells = {'Grandmaster\'s Aura'},
				spell_ids = {15095},
			},
			['Pack7'] = {
				item = 'Tome of Phantom Whispers/118654',
				spells = {'Phantom Whispers'},
				spell_ids = {18904},
			},
			['Pack8'] = {
				item = 'Tome of Stormfist Discipline/79445',
				spells = {'Stormfist Discipline'},
				spell_ids = {11923},
			},
			['Pack9'] = {
				item = 'Tome of Velocity Focus/80083',
				spells = {'Velocity Focus Discipline'},
				spell_ids = {15101},
			},
			['Pack10'] = {
				item = 'Tome of Wheel of Fists/88901',
				spells = {'Wheel of Fists'},
				spell_ids = {14797},
			},
			['Glyph1'] = 'Imbued Glyph: Ancient: Arachnid Fang/80074',
			['Aug1'] = {
				item = 'Benevolent Extension',
				names = {'Benevolent Extension', 'Cryptic Clutch of Benevolent Extension', 'Vacant Vessel of Benevolent Extension'},
				ids = {62551, 63017},
				notes = '+40% beneficial spell duration | +10 hWIS',
			},
			['Aug2'] = {
				item = 'Noxious Demise',
				names = {'Noxious Demise', 'Cryptic Clutch of Noxious Demise', 'Vacant Vessel of Noxious Demise'},
				ids = {62547, 62567},
				notes = '+10–60% poison spell damage | +5 hINT, +25 hPR',
			},
			['Aug3'] = {
				item = 'Nimble Elusion',
				names = {'Nimble Elusion', 'Cryptic Clutch of Nimble Elusion', 'Vacant Vessel of Nimble Elusion'},
				ids = {62556, 64050},
				notes = '+70% dodge | +10 hAGI',
			},
			['Aug4'] = {
				item = 'Adept Guard',
				names = {'Adept Guard', 'Cryptic Clutch of Adept Guard', 'Vacant Vessel of Adept Guard'},
				ids = {62555, 64049},
				notes = '+70% parry, +70% block | +10 hSTA',
			},
			['Aug5'] = {
				item = 'Visceral Malice',
				names = {'Visceral Malice', 'Cryptic Clutch of Visceral Malice', 'Vacant Vessel of Visceral Malice'},
				ids = {62554, 63020},
				notes = '+300% melee critical damage | +10 hSTR',
			},
			['Aug6'] = {
				item = 'Wanton Assault',
				names = {'Wanton Assault', 'Cryptic Clutch of Wanton Assault', 'Vacant Vessel of Wanton Assault'},
				ids = {62553, 63019},
				notes = '+21% double attack, +7% triple attack, +5% chance to hit | +10 hSTR',
			},
			['Aug7'] = {
				item = 'Physical Prowess',
				names = {'Physical Prowess', 'Cryptic Clutch of Physical Prowess', 'Vacant Vessel of Physical Prowess'},
				ids = {62558, 66533},
				notes = 'No focus effect | +5 hSTR, +5 hSTA, +5 hAGI, +5 hDEX',
			},
		},
		['Necromancer'] = {
			['Head'] = 'Keeper\'s Ascendant Cap of the Grave/60511',
			['Chest'] = 'Keeper\'s Ascendant Tunic of the Grave/60512',
			['Arms'] = 'Keeper\'s Ascendant Armband of the Grave/60513',
			['Wrist1'] = 'Keeper\'s Ascendant Bracer of the Grave/60514',
			['Hands'] = 'Keeper\'s Ascendant Handguards of the Grave/60515',
			['Legs'] = 'Keeper\'s Ascendant Pants of the Grave/60516',
			['Feet'] = 'Keeper\'s Ascendant Sandals of the Grave/60517',
			['Wrist2'] = 'Keeper\'s Eternal Bracer of the Grave/60518',
			['Ear1'] = 'Hoop of the Drakeborn/71574',
			['Ear2'] = 'Grelian Earring of Uncertainty/71603',
			['Face'] = 'Entrancing Silk Veil/71643',
			['Neck'] = 'Choker of One Hundred Diamonds/71651',
			['Back'] = 'Shroud of the Surging Storm/71656',
			['Shoulder'] = 'Brimstone Spaulders/71635',
			['Waist'] = 'Sash of Frigidity/71650',
			['Finger1'] = 'Thought Sieve Ring/71625',
			['Finger2'] = 'Stormeye Band/71658',
			['Ranged'] = 'Spark of the Skies/60536',
			['RangedAug'] = 'Core of the Skies/71659',
			['Clicky1'] = 'Icon of Ancient Boon/56758',
			['Clicky2'] = 'Icon of Scribe\'s Endurance/56756',
			['Clicky3'] = 'Icon of the Ancient Scribe/57143',
			['Shadow'] = 'Shadow of a Legendary Necromancer Shield/62532',
			['Pack1'] = {
				item = 'Spell Pack: Sacrilege of the Wraith/82805',
				spells = {'Sacrilege of the Wraith'},
			},
			['Pack2'] = {
				item = 'Spell Pack: Dull Agony/82806',
				spells = {'Dull Agony'},
			},
			['Pack3'] = {
				item = 'Spell Pack: Goner\'s Urgent Renewal/82800',
				spells = {'Goner\'s Urgent Renewal'},
			},
			['Pack4'] = {
				item = 'Spell: Malignant Plague/80786',
				spells = {'Malignant Plague'},
				spell_ids = {15230},
			},
			['Pack5'] = {
				item = 'Spell: Molten Pyre/80785',
				spells = {'Molten Pyre'},
				spell_ids = {15225},
			},
			['Pack6'] = {
				item = 'Spell: Pestilent Pustules/119599',
				spells = {'Pestilent Pustules'},
				spell_ids = {10906},
			},
			['Pack7'] = {
				item = 'Spell: Ritual of Blood/78819',
				spells = {'Ritual of Blood'},
				spell_ids = {10482},
			},
			['Pack8'] = {
				item = 'Spell: Venom of the Accursed Nest/78892',
				spells = {'Venom of the Accursed Nest'},
				spell_ids = {10555},
			},
			['Pack9'] = {
				item = 'Spell: Yearning of Death/80784',
				spells = {'Yearning of Death'},
				spell_ids = {15222},
			},
			['Glyph1'] = 'Mnemonic Glyph: Sacrilege of the Wraith/79527',
			['Glyph2'] = 'Mnemonic Glyph: Dull Agony/79528',
			['Glyph3'] = 'Imbued Glyph: Goner\'s Urgent Renewal/79526',
			['Aug1'] = {
				item = 'Benevolent Extension',
				names = {'Benevolent Extension', 'Cryptic Clutch of Benevolent Extension', 'Vacant Vessel of Benevolent Extension'},
				ids = {62551, 63017},
				notes = '+40% beneficial spell duration | +10 hWIS',
			},
			['Aug2'] = {
				item = 'Benevolent Alacrity',
				names = {'Benevolent Alacrity', 'Cryptic Clutch of Benevolent Alacrity', 'Vacant Vessel of Benevolent Alacrity'},
				ids = {62543, 62563},
				notes = '-40% beneficial spell cast time | +10 hWIS',
			},
			['Aug3'] = {
				item = 'Malevolent Efficiency',
				names = {'Malevolent Efficiency', 'Cryptic Clutch of Malevolent Efficiency', 'Vacant Vessel of Malevolent Efficiency'},
				ids = {62540, 62560},
				notes = '-11–33% detrimental spell mana cost | +10 hINT',
			},
			['Aug4'] = {
				item = 'Malevolent Extension',
				names = {'Malevolent Extension', 'Cryptic Clutch of Malevolent Extension', 'Vacant Vessel of Malevolent Extension'},
				ids = {62550, 63016},
				notes = '+40% detrimental spell duration | +10 hINT',
			},
			['Aug5'] = {
				item = 'Malevolent Alacrity',
				names = {'Malevolent Alacrity', 'Cryptic Clutch of Malevolent Alacrity', 'Vacant Vessel of Malevolent Alacrity'},
				ids = {62542, 62562},
				notes = '-40% detrimental spell cast time | +10 hINT',
			},
			['Aug6'] = {
				item = 'Fiery Demise',
				names = {'Fiery Demise', 'Cryptic Clutch of Fiery Demise', 'Vacant Vessel of Fiery Demise'},
				ids = {62545, 62565},
				notes = '+10–60% fire spell damage | +5 hINT, +25 hFR',
			},
			['Aug7'] = {
				item = 'Noxious Demise',
				names = {'Noxious Demise', 'Cryptic Clutch of Noxious Demise', 'Vacant Vessel of Noxious Demise'},
				ids = {62547, 62567},
				notes = '+10–60% poison spell damage | +5 hINT, +25 hPR',
			},
			['Aug8'] = {
				item = 'Arcane Demise',
				names = {'Arcane Demise', 'Cryptic Clutch of Arcane Demise', 'Vacant Vessel of Arcane Demise'},
				ids = {62544, 62564},
				notes = '+10–60% magic spell damage | +5 hINT, +25 hMR',
			},
			['Aug9'] = {
				item = 'Festering Demise',
				names = {'Festering Demise', 'Cryptic Clutch of Festering Demise', 'Vacant Vessel of Festering Demise'},
				ids = {62548, 62568},
				notes = '+10–60% disease spell damage | +5 hINT, +25 hDR',
			},
			['Aug10'] = {
				item = 'Expanded Reach',
				names = {'Expanded Reach', 'Cryptic Clutch of Expanded Reach', 'Vacant Vessel of Expanded Reach'},
				ids = {62552, 63018},
				notes = '+50% spell range | +10 hWIS, +10 hINT',
			},
			['Aug11'] = {
				item = 'Nimble Elusion',
				names = {'Nimble Elusion', 'Cryptic Clutch of Nimble Elusion', 'Vacant Vessel of Nimble Elusion'},
				ids = {62556, 64050},
				notes = '+70% dodge | +10 hAGI',
			},
			['Aug12'] = {
				item = 'Mental Prowess',
				names = {'Mental Prowess', 'Cryptic Clutch of Mental Prowess', 'Vacant Vessel of Mental Prowess'},
				ids = {62559, 66720},
				notes = 'No focus effect | +10 hINT, +10 hWIS, +10 heroic resists',
			},
		},
		['Paladin'] = {
			['Head'] = 'Keeper\'s Ascendant Coif of the Defender/54960',
			['Chest'] = 'Keeper\'s Ascendant Chestpiece of the Defender/54961',
			['Arms'] = 'Keeper\'s Ascendant Sleeves of the Defender/54962',
			['Wrist1'] = 'Keeper\'s Ascendant Wristguard of the Defender/54963',
			['Hands'] = 'Keeper\'s Ascendant Mitts of the Defender/54964',
			['Legs'] = 'Keeper\'s Ascendant Leggings of the Defender/54965',
			['Feet'] = 'Keeper\'s Ascendant Boots of the Defender/55037',
			['Wrist2'] = 'Keeper\'s Eternal Bracer of the Defender/55050',
			['Ear1'] = 'Weighted Loop of Eternal Battle/71624',
			['Ear2'] = 'Hoop of the Nest Defender/71593',
			['Face'] = 'Face of Unfeeling/71667',
			['Neck'] = 'Necklace of Grimspirit Beads/71597',
			['Back'] = 'Cape of Dragon Scales/71596',
			['Shoulder'] = 'Dark-Touched Mantle/71590',
			['Waist'] = 'Belt of the Black Dragon/71664',
			['Finger1'] = 'Ring of Unsung Legends/71608',
			['Finger2'] = 'Ring of Living Malachite/71562',
			['Ranged'] = 'Branch of the Twisting Tree/71627',
			['RangedAug'] = 'Fallen Leaf of the Twisting Tree/55053',
			['Clicky1'] = 'Icon of Ancient Boon/56758',
			['Clicky2'] = 'Icon of Unwavering Defense/56755',
			['Clicky3'] = 'Icon of Ancient Defense/57141',
			['Shadow'] = 'Shadow of a Legendary Paladin Shield/60545',
			['Pack1'] = {
				item = 'Spell Pack: Armor of the Savior/82810',
				spells = {'Armor of the Savior'},
			},
			['Pack2'] = {
				item = 'Spell Pack: Virtuous Fervor/82811',
				spells = {'Virtuous Fervor'},
			},
			['Pack3'] = {
				item = 'Spell Pack: Wave of the Stillmoon/82812',
				spells = {'Wave of the Stillmoon'},
			},
			['Pack4'] = {
				item = 'Spell: Benevolent Aura/81864',
				spells = {'Benevolent Aura'},
				spell_ids = {15251},
			},
			['Pack5'] = {
				item = 'Spell: Brell\'s Unshakable Barricade/81862',
				spells = {'Brell\'s Unshakable Barricade'},
				spell_ids = {15248},
			},
			['Pack6'] = {
				item = 'Spell: Force of the Sacred/81861',
				spells = {'Force of the Sacred'},
				spell_ids = {15240},
			},
			['Pack7'] = {
				item = 'Spell: Force of the Sentinel/81863',
				spells = {'Force of the Sentinel'},
				spell_ids = {15249},
			},
			['Pack8'] = {
				item = 'Spell: The Silent Decree/78039',
				spells = {'The Silent Decree'},
				spell_ids = {10919},
			},
			['Pack9'] = {
				item = 'Tome of Aegis of Righteousness/79399',
				spells = {'Aegis of Righteousness'},
				spell_ids = {11854},
			},
			['Glyph1'] = 'Mnemonic Glyph: Armor of the Savior/79538',
			['Glyph2'] = 'Mnemonic Glyph: Virtuous Fervor/79539',
			['Glyph3'] = 'Imbued Glyph: Wave of the Stillmoon/79540',
			['Aug1'] = {
				item = 'Benevolent Efficiency',
				names = {'Benevolent Efficiency', 'Cryptic Clutch of Benevolent Efficiency', 'Vacant Vessel of Benevolent Efficiency'},
				ids = {62541, 62561},
				notes = '-11–33% beneficial spell mana cost | +10 hWIS',
			},
			['Aug2'] = {
				item = 'Benevolent Extension',
				names = {'Benevolent Extension', 'Cryptic Clutch of Benevolent Extension', 'Vacant Vessel of Benevolent Extension'},
				ids = {62551, 63017},
				notes = '+40% beneficial spell duration | +10 hWIS',
			},
			['Aug3'] = {
				item = 'Arcane Demise',
				names = {'Arcane Demise', 'Cryptic Clutch of Arcane Demise', 'Vacant Vessel of Arcane Demise'},
				ids = {62544, 62564},
				notes = '+10–60% magic spell damage | +5 hINT, +25 hMR',
			},
			['Aug4'] = {
				item = 'Expanded Reach',
				names = {'Expanded Reach', 'Cryptic Clutch of Expanded Reach', 'Vacant Vessel of Expanded Reach'},
				ids = {62552, 63018},
				notes = '+50% spell range | +10 hWIS, +10 hINT',
			},
			['Aug5'] = {
				item = 'Merciful Mending',
				names = {'Merciful Mending', 'Cryptic Clutch of Merciful Mending', 'Vacant Vessel of Merciful Mending'},
				ids = {62549, 62569},
				notes = '+10–60% healing | +10 hWIS',
			},
			['Aug6'] = {
				item = 'Nimble Elusion',
				names = {'Nimble Elusion', 'Cryptic Clutch of Nimble Elusion', 'Vacant Vessel of Nimble Elusion'},
				ids = {62556, 64050},
				notes = '+70% dodge | +10 hAGI',
			},
			['Aug7'] = {
				item = 'Adept Guard',
				names = {'Adept Guard', 'Cryptic Clutch of Adept Guard', 'Vacant Vessel of Adept Guard'},
				ids = {62555, 64049},
				notes = '+70% parry, +70% block | +10 hSTA',
			},
			['Aug8'] = {
				item = 'Visceral Malice',
				names = {'Visceral Malice', 'Cryptic Clutch of Visceral Malice', 'Vacant Vessel of Visceral Malice'},
				ids = {62554, 63020},
				notes = '+300% melee critical damage | +10 hSTR',
			},
			['Aug9'] = {
				item = 'Wanton Assault',
				names = {'Wanton Assault', 'Cryptic Clutch of Wanton Assault', 'Vacant Vessel of Wanton Assault'},
				ids = {62553, 63019},
				notes = '+21% double attack, +7% triple attack, +5% chance to hit | +10 hSTR',
			},
			['Aug10'] = {
				item = 'Physical Prowess',
				names = {'Physical Prowess', 'Cryptic Clutch of Physical Prowess', 'Vacant Vessel of Physical Prowess'},
				ids = {62558, 66533},
				notes = 'No focus effect | +5 hSTR, +5 hSTA, +5 hAGI, +5 hDEX',
			},
		},
		['Ranger'] = {
			['Head'] = 'Keeper\'s Ascendant Cap of Journeys/60519',
			['Chest'] = 'Keeper\'s Ascendant Vest of Journeys/60520',
			['Arms'] = 'Keeper\'s Ascendant Sleeves of Journeys/60521',
			['Wrist1'] = 'Keeper\'s Ascendant Wristband of Journeys/60522',
			['Hands'] = 'Keeper\'s Ascendant Gloves of Journeys/60523',
			['Legs'] = 'Keeper\'s Ascendant Legguards of Journeys/60524',
			['Feet'] = 'Keeper\'s Ascendant Boots of Journeys/60525',
			['Wrist2'] = 'Keeper\'s Eternal Bracer of of Journeys/60526',
			['Ear1'] = 'Cloudkiller\'s Bauble/71584',
			['Ear2'] = 'Grelian Earring of Uncertainty/71603',
			['Face'] = 'Mask of the Dawn Scorcher/71626',
			['Neck'] = 'Choker of One Hundred Diamonds/71651',
			['Back'] = 'Shroud of the Surging Storm/71656',
			['Shoulder'] = 'Lightning Singed Mantle/71654',
			['Waist'] = 'Belt of the Black Dragon/71664',
			['Finger1'] = 'Glimmering Fire Opal Band/71634',
			['Finger2'] = 'Stormeye Band/71658',
			['Ranged'] = 'Branch of the Twisting Tree/71627',
			['RangedAug'] = 'Fallen Leaf of the Twisting Tree/55053',
			['Clicky1'] = 'Icon of Ancient Boon/56758',
			['Clicky2'] = 'Icon of Potent Prowess/56757',
			['Clicky3'] = 'Icon of Ancient Prowess/57142',
			['Shadow'] = 'Shadow of a Legendary Ranger Shield/62533',
			['Pack1'] = {
				item = 'Spell Pack: Snarl of the Predator/82813',
				spells = {'Snarl of the Predator'},
			},
			['Pack2'] = {
				item = 'Spell Pack: Guard of Thundercrest/82814',
				spells = {'Guard of Thundercrest'},
			},
			['Pack3'] = {
				item = 'Spell Pack: Call of Storms/82815',
				spells = {'Call of Storms'},
			},
			['Pack4'] = {
				item = 'Tome Pack: Jolting Thunderkicks/82816',
				spells = {'Jolting Thunderkicks'},
			},
			['Pack5'] = {
				item = 'Spell Pack: Flame and Frost/50150',
				spells = {'Flame and Frost'},
			},
			['Pack6'] = {
				item = 'Spell: Eyes of the Drake/81866',
				spells = {'Eyes of the Drake'},
				spell_ids = {15255},
			},
			['Pack7'] = {
				item = 'Spell: Heartshatter/116082',
				spells = {'Heartshatter'},
				spell_ids = {15082},
			},
			['Pack8'] = {
				item = 'Spell: Swift Salve of the Stillmoon/81867',
				spells = {'Swift Salve of the Stillmoon'},
				spell_ids = {15257},
			},
			['Pack9'] = {
				item = 'Spell: Ward of the Stalker/81865',
				spells = {'Ward of the Stalker'},
				spell_ids = {15254},
			},
			['Glyph1'] = 'Mnemonic Glyph: Snarl of the Predator/80063',
			['Glyph2'] = 'Mnemonic Glyph: Guard of Thundercrest/80064',
			['Glyph3'] = 'Mnemonic Glyph: Call of Storms/80065',
			['Glyph4'] = 'Imbued Glyph: Jolting Thunderkicks/80066',
			['Aug1'] = {
				item = 'Benevolent Extension',
				names = {'Benevolent Extension', 'Cryptic Clutch of Benevolent Extension', 'Vacant Vessel of Benevolent Extension'},
				ids = {62551, 63017},
				notes = '+40% beneficial spell duration | +10 hWIS',
			},
			['Aug2'] = {
				item = 'Malevolent Efficiency',
				names = {'Malevolent Efficiency', 'Cryptic Clutch of Malevolent Efficiency', 'Vacant Vessel of Malevolent Efficiency'},
				ids = {62540, 62560},
				notes = '-11–33% detrimental spell mana cost | +10 hINT',
			},
			['Aug3'] = {
				item = 'Malevolent Extension',
				names = {'Malevolent Extension', 'Cryptic Clutch of Malevolent Extension', 'Vacant Vessel of Malevolent Extension'},
				ids = {62550, 63016},
				notes = '+40% detrimental spell duration | +10 hINT',
			},
			['Aug4'] = {
				item = 'Fiery Demise',
				names = {'Fiery Demise', 'Cryptic Clutch of Fiery Demise', 'Vacant Vessel of Fiery Demise'},
				ids = {62545, 62565},
				notes = '+10–60% fire spell damage | +5 hINT, +25 hFR',
			},
			['Aug5'] = {
				item = 'Arcane Demise',
				names = {'Arcane Demise', 'Cryptic Clutch of Arcane Demise', 'Vacant Vessel of Arcane Demise'},
				ids = {62544, 62564},
				notes = '+10–60% magic spell damage | +5 hINT, +25 hMR',
			},
			['Aug6'] = {
				item = 'Expanded Reach',
				names = {'Expanded Reach', 'Cryptic Clutch of Expanded Reach', 'Vacant Vessel of Expanded Reach'},
				ids = {62552, 63018},
				notes = '+50% spell range | +10 hWIS, +10 hINT',
			},
			['Aug7'] = {
				item = 'Merciful Mending',
				names = {'Merciful Mending', 'Cryptic Clutch of Merciful Mending', 'Vacant Vessel of Merciful Mending'},
				ids = {62549, 62569},
				notes = '+10–60% healing | +10 hWIS',
			},
			['Aug8'] = {
				item = 'Nimble Elusion',
				names = {'Nimble Elusion', 'Cryptic Clutch of Nimble Elusion', 'Vacant Vessel of Nimble Elusion'},
				ids = {62556, 64050},
				notes = '+70% dodge | +10 hAGI',
			},
			['Aug9'] = {
				item = 'Adept Guard',
				names = {'Adept Guard', 'Cryptic Clutch of Adept Guard', 'Vacant Vessel of Adept Guard'},
				ids = {62555, 64049},
				notes = '+70% parry, +70% block | +10 hSTA',
			},
			['Aug10'] = {
				item = 'Visceral Malice',
				names = {'Visceral Malice', 'Cryptic Clutch of Visceral Malice', 'Vacant Vessel of Visceral Malice'},
				ids = {62554, 63020},
				notes = '+300% melee critical damage | +10 hSTR',
			},
			['Aug11'] = {
				item = 'Wanton Assault',
				names = {'Wanton Assault', 'Cryptic Clutch of Wanton Assault', 'Vacant Vessel of Wanton Assault'},
				ids = {62553, 63019},
				notes = '+21% double attack, +7% triple attack, +5% chance to hit | +10 hSTR',
			},
			['Aug12'] = {
				item = 'Lethal Barrage',
				names = {'Lethal Barrage', 'Cryptic Clutch of Lethal Barrage', 'Vacant Vessel of Lethal Barrage'},
				ids = {62557, 64326},
				notes = '+28% archery and throwing chance to hit | +20 hDEX',
			},
		},
		['Rogue'] = {
			['Head'] = 'Keeper\'s Ascendant Hat of Shadows/59359',
			['Chest'] = 'Keeper\'s Ascendant Tunic of Shadows/60442',
			['Arms'] = 'Keeper\'s Ascendant Armguard of Shadows/60443',
			['Wrist1'] = 'Keeper\'s Ascendant Bracer of Shadows/60444',
			['Hands'] = 'Keeper\'s Ascendant Gloves of Shadows/60445',
			['Legs'] = 'Keeper\'s Ascendant Pants of Shadows/60446',
			['Feet'] = 'Keeper\'s Ascendant Boots of Shadows/60447',
			['Wrist2'] = 'Keeper\'s Eternal Bracer of Shadows/60448',
			['Ear1'] = 'Cloudkiller\'s Bauble/71584',
			['Ear2'] = 'Accursed Earhoop of Pain/71668',
			['Face'] = 'Mask of the Dawn Scorcher/71626',
			['Neck'] = 'Necklace of Sandstorms/71612',
			['Back'] = 'Cloak of Deepshadow/71665',
			['Shoulder'] = 'Lightning Singed Mantle/71654',
			['Waist'] = 'Thundercrash Girdle/71657',
			['Finger1'] = 'Glimmering Fire Opal Band/71634',
			['Finger2'] = 'Bloodstained Ring of Evisceration/71588',
			['Ranged'] = 'Head of the Putrid Drake/55052',
			['RangedAug'] = 'Preserved Eye of the Putrid Drake/71620',
			['Clicky1'] = 'Icon of Ancient Boon/56758',
			['Clicky2'] = 'Icon of Potent Prowess/56757',
			['Clicky3'] = 'Icon of Ancient Prowess/57142',
			['Shadow'] = 'Shadow of a Legendary Rogue Weapon/60550',
			['Pack1'] = {
				item = 'Tome Pack: Ancient: Incursion/82656',
				spells = {'Ancient: Incursion'},
			},
			['Pack2'] = {
				item = 'Tome of Arcane Reprisal/79226',
				spells = {'Arcane Reprisal'},
				spell_ids = {10889},
			},
			['Pack3'] = {
				item = 'Tome of Assailant Discipline/80087',
				spells = {'Assailant Discipline'},
				spell_ids = {15117},
			},
			['Pack4'] = {
				item = 'Tome of Fourth Wind/80081',
				spells = {'Fourth Wind Discipline'},
				spell_ids = {15134},
			},
			['Pack5'] = {
				item = 'Tome of Frenetic Stabbing Discipline/80088',
				spells = {'Frenetic Stabbing Discipline'},
				spell_ids = {15119},
			},
			['Pack6'] = {
				item = 'Tome of Lithe Discipline/80085',
				spells = {'Lithe Discipline'},
				spell_ids = {15102},
			},
			['Pack7'] = {
				item = 'Tome of Outlaw\'s Glare/88900',
				spells = {'Outlaw\'s Glare'},
				spell_ids = {40294},
			},
			['Pack8'] = {
				item = 'Tome of Pinpoint Weakness/88902',
				spells = {'Pinpoint Weakness'},
				spell_ids = {15115},
			},
			['Pack9'] = {
				item = 'Tome of Twisted Fortune Discipline/50116',
				spells = {'Twisted Fortune Discipline'},
				spell_ids = {10852},
			},
			['Pack10'] = {
				item = 'Tome of Vigorous Dagger Throw/79236',
				spells = {'Vigorous Dagger Throw'},
				spell_ids = {10851},
			},
			['Glyph1'] = 'Imbued Glyph: Ancient: Incursion/80075',
			['Aug1'] = {
				item = 'Benevolent Extension',
				names = {'Benevolent Extension', 'Cryptic Clutch of Benevolent Extension', 'Vacant Vessel of Benevolent Extension'},
				ids = {62551, 63017},
				notes = '+40% beneficial spell duration | +10 hWIS',
			},
			['Aug2'] = {
				item = 'Malevolent Extension',
				names = {'Malevolent Extension', 'Cryptic Clutch of Malevolent Extension', 'Vacant Vessel of Malevolent Extension'},
				ids = {62550, 63016},
				notes = '+40% detrimental spell duration | +10 hINT',
			},
			['Aug3'] = {
				item = 'Noxious Demise',
				names = {'Noxious Demise', 'Cryptic Clutch of Noxious Demise', 'Vacant Vessel of Noxious Demise'},
				ids = {62547, 62567},
				notes = '+10–60% poison spell damage | +5 hINT, +25 hPR',
			},
			['Aug4'] = {
				item = 'Nimble Elusion',
				names = {'Nimble Elusion', 'Cryptic Clutch of Nimble Elusion', 'Vacant Vessel of Nimble Elusion'},
				ids = {62556, 64050},
				notes = '+70% dodge | +10 hAGI',
			},
			['Aug5'] = {
				item = 'Adept Guard',
				names = {'Adept Guard', 'Cryptic Clutch of Adept Guard', 'Vacant Vessel of Adept Guard'},
				ids = {62555, 64049},
				notes = '+70% parry, +70% block | +10 hSTA',
			},
			['Aug6'] = {
				item = 'Visceral Malice',
				names = {'Visceral Malice', 'Cryptic Clutch of Visceral Malice', 'Vacant Vessel of Visceral Malice'},
				ids = {62554, 63020},
				notes = '+300% melee critical damage | +10 hSTR',
			},
			['Aug7'] = {
				item = 'Wanton Assault',
				names = {'Wanton Assault', 'Cryptic Clutch of Wanton Assault', 'Vacant Vessel of Wanton Assault'},
				ids = {62553, 63019},
				notes = '+21% double attack, +7% triple attack, +5% chance to hit | +10 hSTR',
			},
			['Aug8'] = {
				item = 'Physical Prowess',
				names = {'Physical Prowess', 'Cryptic Clutch of Physical Prowess', 'Vacant Vessel of Physical Prowess'},
				ids = {62558, 66533},
				notes = 'No focus effect | +5 hSTR, +5 hSTA, +5 hAGI, +5 hDEX',
			},
		},
		['Shadow Knight'] = {
			['Head'] = 'Keeper\'s Ascendant Helm of the Hateful/54953',
			['Chest'] = 'Keeper\'s Ascendant Chestguard of the Hateful/54954',
			['Arms'] = 'Keeper\'s Ascendant Armguards of the Hateful/54955',
			['Wrist1'] = 'Keeper\'s Ascendant Wristguard of the Hateful/54956',
			['Hands'] = 'Keeper\'s Ascendant Gloves of the Hateful/54957',
			['Legs'] = 'Keeper\'s Ascendant Legguards of the Hateful/54958',
			['Feet'] = 'Keeper\'s Ascendant Boots of the Hateful/54959',
			['Wrist2'] = 'Keeper\'s Eternal Bracer of the Hateful/55051',
			['Ear1'] = 'Weighted Loop of Eternal Battle/71624',
			['Ear2'] = 'Hoop of the Nest Defender/71593',
			['Face'] = 'Face of Unfeeling/71667',
			['Neck'] = 'Necklace of Grimspirit Beads/71597',
			['Back'] = 'Cape of Dragon Scales/71596',
			['Shoulder'] = 'Dark-Touched Mantle/71590',
			['Waist'] = 'Belt of the Black Dragon/71664',
			['Finger1'] = 'Ring of Unsung Legends/71608',
			['Finger2'] = 'Ring of Living Malachite/71562',
			['Ranged'] = 'Branch of the Twisting Tree/71627',
			['RangedAug'] = 'Fallen Leaf of the Twisting Tree/55053',
			['Clicky1'] = 'Icon of Ancient Boon/56758',
			['Clicky2'] = 'Icon of Unwavering Defense/56755',
			['Clicky3'] = 'Icon of Ancient Defense/57141',
			['Shadow'] = 'Shadow of a Legendary Shadowknight Shield/60544',
			['Pack1'] = {
				item = 'Spell Pack: Cloak of the Corrupter/82807',
				spells = {'Cloak of the Corrupter'},
			},
			['Pack2'] = {
				item = 'Spell Pack: Shroud of the Accursed/82808',
				spells = {'Shroud of the Accursed'},
			},
			['Pack3'] = {
				item = 'Spell Pack: Theft of Misery/82809',
				-- Pack opens to Spell: Theft of Misery (71777); scribed spell id 15073.
				names = {'Spell Pack: Theft of Misery', 'Spell: Theft of Misery'},
				ids = {82809, 71777},
				spells = {'Theft of Misery'},
				spell_ids = {15073},
			},
			['Pack4'] = {
				item = 'Spell: Blood of the Harbinger/80788',
				spells = {'Blood of the Harbinger'},
				spell_ids = {15233},
			},
			['Pack5'] = {
				item = 'Spell: Grasp of Ju\'rek/78565',
				spells = {'Grasp of Ju\'rek'},
				spell_ids = {10913},
			},
			['Pack6'] = {
				item = 'Spell: Terror of Lavaspinner\'s Lair/78594',
				spells = {'Terror of Lavaspinner\'s Lair'},
				spell_ids = {10257},
			},
			['Pack7'] = {
				item = 'Spell: Touch of the Shadows/80787',
				spells = {'Touch of the Shadows'},
				spell_ids = {15231},
			},
			['Pack8'] = {
				item = 'Spell: Voice of Emoush/81860',
				spells = {'Voice of Emoush'},
				spell_ids = {15239},
			},
			['Pack9'] = {
				item = 'Tome of Soul Carapace/79408',
				spells = {'Soul Carapace'},
				spell_ids = {11866},
			},
			['Glyph1'] = 'Mnemonic Glyph: Cloak of the Corrupter/79535',
			['Glyph2'] = 'Mnemonic Glyph: Shroud of the Accursed/79536',
			['Glyph3'] = 'Imbued Glyph: Theft of Misery/79537',
			['Aug1'] = {
				item = 'Benevolent Extension',
				names = {'Benevolent Extension', 'Cryptic Clutch of Benevolent Extension', 'Vacant Vessel of Benevolent Extension'},
				ids = {62551, 63017},
				notes = '+40% beneficial spell duration | +10 hWIS',
			},
			['Aug2'] = {
				item = 'Malevolent Extension',
				names = {'Malevolent Extension', 'Cryptic Clutch of Malevolent Extension', 'Vacant Vessel of Malevolent Extension'},
				ids = {62550, 63016},
				notes = '+40% detrimental spell duration | +10 hINT',
			},
			['Aug3'] = {
				item = 'Noxious Demise',
				names = {'Noxious Demise', 'Cryptic Clutch of Noxious Demise', 'Vacant Vessel of Noxious Demise'},
				ids = {62547, 62567},
				notes = '+10–60% poison spell damage | +5 hINT, +25 hPR',
			},
			['Aug4'] = {
				item = 'Arcane Demise',
				names = {'Arcane Demise', 'Cryptic Clutch of Arcane Demise', 'Vacant Vessel of Arcane Demise'},
				ids = {62544, 62564},
				notes = '+10–60% magic spell damage | +5 hINT, +25 hMR',
			},
			['Aug5'] = {
				item = 'Festering Demise',
				names = {'Festering Demise', 'Cryptic Clutch of Festering Demise', 'Vacant Vessel of Festering Demise'},
				ids = {62548, 62568},
				notes = '+10–60% disease spell damage | +5 hINT, +25 hDR',
			},
			['Aug6'] = {
				item = 'Expanded Reach',
				names = {'Expanded Reach', 'Cryptic Clutch of Expanded Reach', 'Vacant Vessel of Expanded Reach'},
				ids = {62552, 63018},
				notes = '+50% spell range | +10 hWIS, +10 hINT',
			},
			['Aug7'] = {
				item = 'Nimble Elusion',
				names = {'Nimble Elusion', 'Cryptic Clutch of Nimble Elusion', 'Vacant Vessel of Nimble Elusion'},
				ids = {62556, 64050},
				notes = '+70% dodge | +10 hAGI',
			},
			['Aug8'] = {
				item = 'Adept Guard',
				names = {'Adept Guard', 'Cryptic Clutch of Adept Guard', 'Vacant Vessel of Adept Guard'},
				ids = {62555, 64049},
				notes = '+70% parry, +70% block | +10 hSTA',
			},
			['Aug9'] = {
				item = 'Visceral Malice',
				names = {'Visceral Malice', 'Cryptic Clutch of Visceral Malice', 'Vacant Vessel of Visceral Malice'},
				ids = {62554, 63020},
				notes = '+300% melee critical damage | +10 hSTR',
			},
			['Aug10'] = {
				item = 'Wanton Assault',
				names = {'Wanton Assault', 'Cryptic Clutch of Wanton Assault', 'Vacant Vessel of Wanton Assault'},
				ids = {62553, 63019},
				notes = '+21% double attack, +7% triple attack, +5% chance to hit | +10 hSTR',
			},
			['Aug11'] = {
				item = 'Physical Prowess',
				names = {'Physical Prowess', 'Cryptic Clutch of Physical Prowess', 'Vacant Vessel of Physical Prowess'},
				ids = {62558, 66533},
				notes = 'No focus effect | +5 hSTR, +5 hSTA, +5 hAGI, +5 hDEX',
			},
		},
		['Shaman'] = {
			['Head'] = 'Keeper\'s Ascendant Cap of the Ancestors/57152',
			['Chest'] = 'Keeper\'s Ascendant Tunic of the Ancestors/57153',
			['Arms'] = 'Keeper\'s Ascendant Armguards of the Ancestors/57154',
			['Wrist1'] = 'Keeper\'s Ascendant Wristband of the Ancestors/57155',
			['Hands'] = 'Keeper\'s Ascendant Mitts of the Ancestors/57156',
			['Legs'] = 'Keeper\'s Ascendant Leggings of the Ancestors/57157',
			['Feet'] = 'Keeper\'s Ascendant Boots of the Ancestors/57158',
			['Wrist2'] = 'Keeper\'s Eternal Bracer of the Ancestors/57159',
			['Ear1'] = 'Earring of Contemplation/71589',
			['Ear2'] = 'Tear of Kessdona/71642',
			['Face'] = 'Young Dragon Mask/71594',
			['Neck'] = 'Locket of Raining Tears/71655',
			['Back'] = 'Cape of Serenity/71613',
			['Shoulder'] = 'Obsidian Pauldrons/71666',
			['Waist'] = 'Windwatcher Sash/71621',
			['Finger1'] = 'Dragon Nursery Ring/71592',
			['Finger2'] = 'Eye of Tirranun/71652',
			['Ranged'] = 'Crux of the First Brood/60535',
			['RangedAug'] = 'Phial of the First Brood/71578',
			['Clicky1'] = 'Icon of Ancient Boon/56758',
			['Clicky2'] = 'Icon of Scribe\'s Endurance/56756',
			['Clicky3'] = 'Icon of the Ancient Scribe/57143',
			['Shadow'] = 'Shadow of a Legendary Shaman Shield/60547',
			['Pack1'] = {
				item = 'Spell Pack: Stillmoon Focus/82662',
				spells = {'Stillmoon Focusing', 'Talisman of the Stillmoon'},
			},
			['Pack2'] = {
				item = 'Spell Pack: Blood of Volkara/82663',
				spells = {'Blood of Volkara'},
			},
			['Pack3'] = {
				item = 'Spell Pack: Talisman of Coalescence/82664',
				spells = {'Talisman of Coalescence'},
			},
			['Pack4'] = {
				item = 'Spell Pack: Talisman of the Cougar/82665',
				spells = {'Talisman of the Cougar'},
			},
			['Pack5'] = {
				item = 'Spell Pack: Wild Companions/50107',
				spells = {'Wild Companions'},
			},
			['Pack6'] = {
				item = 'Spell: Breath of Ju\'rek/80285',
				spells = {'Breath of Shadows'},
				spell_ids = {41232},
			},
			['Pack7'] = {
				item = 'Spell: Curse of Emoush/80288',
				spells = {'Curse of Emoush'},
				spell_ids = {15147},
			},
			['Pack8'] = {
				item = 'Spell: Shadowy Sloth/80287',
				spells = {'Shadowy Sloth'},
				spell_ids = {15144},
			},
			['Pack9'] = {
				item = 'Spell: Transcendental Torpor/80286',
				spells = {'Transcendental Torpor'},
				spell_ids = {15141},
			},
			['Glyph1'] = 'Mnemonic Glyph: Stillmoon Focusing/76568',
			['Glyph2'] = 'Mnemonic Glyph: Talisman of the Stillmoon/76569',
			['Glyph3'] = 'Mnemonic Glyph: Blood of Volkara/76570',
			['Glyph4'] = 'Mnemonic Glyph: Talisman of Coalescence/76571',
			['Glyph5'] = 'Imbued Glyph: Talisman of the Cougar/76572',
			['Aug1'] = {
				item = 'Benevolent Efficiency',
				names = {'Benevolent Efficiency', 'Cryptic Clutch of Benevolent Efficiency', 'Vacant Vessel of Benevolent Efficiency'},
				ids = {62541, 62561},
				notes = '-11–33% beneficial spell mana cost | +10 hWIS',
			},
			['Aug2'] = {
				item = 'Benevolent Extension',
				names = {'Benevolent Extension', 'Cryptic Clutch of Benevolent Extension', 'Vacant Vessel of Benevolent Extension'},
				ids = {62551, 63017},
				notes = '+40% beneficial spell duration | +10 hWIS',
			},
			['Aug3'] = {
				item = 'Benevolent Alacrity',
				names = {'Benevolent Alacrity', 'Cryptic Clutch of Benevolent Alacrity', 'Vacant Vessel of Benevolent Alacrity'},
				ids = {62543, 62563},
				notes = '-40% beneficial spell cast time | +10 hWIS',
			},
			['Aug4'] = {
				item = 'Malevolent Efficiency',
				names = {'Malevolent Efficiency', 'Cryptic Clutch of Malevolent Efficiency', 'Vacant Vessel of Malevolent Efficiency'},
				ids = {62540, 62560},
				notes = '-11–33% detrimental spell mana cost | +10 hINT',
			},
			['Aug5'] = {
				item = 'Malevolent Extension',
				names = {'Malevolent Extension', 'Cryptic Clutch of Malevolent Extension', 'Vacant Vessel of Malevolent Extension'},
				ids = {62550, 63016},
				notes = '+40% detrimental spell duration | +10 hINT',
			},
			['Aug6'] = {
				item = 'Malevolent Alacrity',
				names = {'Malevolent Alacrity', 'Cryptic Clutch of Malevolent Alacrity', 'Vacant Vessel of Malevolent Alacrity'},
				ids = {62542, 62562},
				notes = '-40% detrimental spell cast time | +10 hINT',
			},
			['Aug7'] = {
				item = 'Noxious Demise',
				names = {'Noxious Demise', 'Cryptic Clutch of Noxious Demise', 'Vacant Vessel of Noxious Demise'},
				ids = {62547, 62567},
				notes = '+10–60% poison spell damage | +5 hINT, +25 hPR',
			},
			['Aug8'] = {
				item = 'Festering Demise',
				names = {'Festering Demise', 'Cryptic Clutch of Festering Demise', 'Vacant Vessel of Festering Demise'},
				ids = {62548, 62568},
				notes = '+10–60% disease spell damage | +5 hINT, +25 hDR',
			},
			['Aug9'] = {
				item = 'Expanded Reach',
				names = {'Expanded Reach', 'Cryptic Clutch of Expanded Reach', 'Vacant Vessel of Expanded Reach'},
				ids = {62552, 63018},
				notes = '+50% spell range | +10 hWIS, +10 hINT',
			},
			['Aug10'] = {
				item = 'Merciful Mending',
				names = {'Merciful Mending', 'Cryptic Clutch of Merciful Mending', 'Vacant Vessel of Merciful Mending'},
				ids = {62549, 62569},
				notes = '+10–60% healing | +10 hWIS',
			},
			['Aug11'] = {
				item = 'Nimble Elusion',
				names = {'Nimble Elusion', 'Cryptic Clutch of Nimble Elusion', 'Vacant Vessel of Nimble Elusion'},
				ids = {62556, 64050},
				notes = '+70% dodge | +10 hAGI',
			},
			['Aug12'] = {
				item = 'Mental Prowess',
				names = {'Mental Prowess', 'Cryptic Clutch of Mental Prowess', 'Vacant Vessel of Mental Prowess'},
				ids = {62559, 66720},
				notes = 'No focus effect | +10 hINT, +10 hWIS, +10 heroic resists',
			},
		},
		['Warrior'] = {
			['Head'] = 'Keeper\'s Ascendant Helm of War/54945',
			['Chest'] = 'Keeper\'s Ascendant Chestguard of War/54946',
			['Arms'] = 'Keeper\'s Ascendant Sleeves of War/54947',
			['Wrist1'] = 'Keeper\'s Ascendant Bracer of War/54948',
			['Hands'] = 'Keeper\'s Ascendant Gloves of War/54949',
			['Legs'] = 'Keeper\'s Ascendant Legguards of War/54950',
			['Feet'] = 'Keeper\'s Ascendant Boots of War/54951',
			['Wrist2'] = 'Keeper\'s Eternal Bracer of War/54952',
			['Ear1'] = 'Weighted Loop of Eternal Battle/71624',
			['Ear2'] = 'Hoop of the Nest Defender/71593',
			['Face'] = 'Face of Unfeeling/71667',
			['Neck'] = 'Necklace of Grimspirit Beads/71597',
			['Back'] = 'Cape of Dragon Scales/71596',
			['Shoulder'] = 'Dark-Touched Mantle/71590',
			['Waist'] = 'Belt of the Black Dragon/71664',
			['Finger1'] = 'Ring of Unsung Legends/71608',
			['Finger2'] = 'Ring of Living Malachite/71562',
			['Ranged'] = 'Head of the Putrid Drake/55052',
			['RangedAug'] = 'Preserved Eye of the Putrid Drake/71620',
			['Clicky1'] = 'Icon of Ancient Boon/56758',
			['Clicky2'] = 'Icon of Unwavering Defense/56755',
			['Clicky3'] = 'Icon of Ancient Defense/57141',
			['Shadow'] = 'Shadow of a Legendary Warrior Shield/60538',
			['Pack1'] = {
				item = 'Tome Pack: Ancient: Malicious Onslaught/82654',
				spells = {'Malicious Onslaught Discipline'},
			},
			['Pack2'] = {
				item = 'Tome of Field Conqueror/88919',
				spells = {'Field Conqueror'},
				spell_ids = {25036},
			},
			['Pack3'] = {
				item = 'Tome of Final Stand Discipline/79302',
				spells = {'Final Stand Discipline'},
				spell_ids = {10965},
			},
			['Pack4'] = {
				item = 'Tome of Fourth Wind/80081',
				spells = {'Fourth Wind Discipline'},
				spell_ids = {15134},
			},
			['Pack5'] = {
				item = 'Tome of Jeer/88909',
				spells = {'Jeer'},
				spell_ids = {10848},
			},
			['Pack6'] = {
				item = 'Tome of Maelstrom Blade/79310',
				spells = {'Maelstrom Blade'},
				spell_ids = {10973},
			},
			['Pack7'] = {
				item = 'Tome of Maximum Effort/80080',
				spells = {'Maximum Effort Discipline'},
				spell_ids = {15104},
			},
			['Pack8'] = {
				item = 'Tome of Roaring Hatred/88910',
				spells = {'Roaring Hatred'},
				spell_ids = {19537},
			},
			['Pack9'] = {
				item = 'Tome of Vanquisher\'s Aura/88925',
				spells = {'Vanquisher\'s Aura'},
				spell_ids = {14351},
			},
			['Glyph1'] = 'Imbued Glyph: Malicious Onslaught Discipline/80073',
			['Aug1'] = {
				item = 'Benevolent Extension',
				names = {'Benevolent Extension', 'Cryptic Clutch of Benevolent Extension', 'Vacant Vessel of Benevolent Extension'},
				ids = {62551, 63017},
				notes = '+40% beneficial spell duration | +10 hWIS',
			},
			['Aug2'] = {
				item = 'Fiery Demise',
				names = {'Fiery Demise', 'Cryptic Clutch of Fiery Demise', 'Vacant Vessel of Fiery Demise'},
				ids = {62545, 62565},
				notes = '+10–60% fire spell damage | +5 hINT, +25 hFR',
			},
			['Aug3'] = {
				item = 'Noxious Demise',
				names = {'Noxious Demise', 'Cryptic Clutch of Noxious Demise', 'Vacant Vessel of Noxious Demise'},
				ids = {62547, 62567},
				notes = '+10–60% poison spell damage | +5 hINT, +25 hPR',
			},
			['Aug4'] = {
				item = 'Nimble Elusion',
				names = {'Nimble Elusion', 'Cryptic Clutch of Nimble Elusion', 'Vacant Vessel of Nimble Elusion'},
				ids = {62556, 64050},
				notes = '+70% dodge | +10 hAGI',
			},
			['Aug5'] = {
				item = 'Adept Guard',
				names = {'Adept Guard', 'Cryptic Clutch of Adept Guard', 'Vacant Vessel of Adept Guard'},
				ids = {62555, 64049},
				notes = '+70% parry, +70% block | +10 hSTA',
			},
			['Aug6'] = {
				item = 'Visceral Malice',
				names = {'Visceral Malice', 'Cryptic Clutch of Visceral Malice', 'Vacant Vessel of Visceral Malice'},
				ids = {62554, 63020},
				notes = '+300% melee critical damage | +10 hSTR',
			},
			['Aug7'] = {
				item = 'Wanton Assault',
				names = {'Wanton Assault', 'Cryptic Clutch of Wanton Assault', 'Vacant Vessel of Wanton Assault'},
				ids = {62553, 63019},
				notes = '+21% double attack, +7% triple attack, +5% chance to hit | +10 hSTR',
			},
			['Aug8'] = {
				item = 'Physical Prowess',
				names = {'Physical Prowess', 'Cryptic Clutch of Physical Prowess', 'Vacant Vessel of Physical Prowess'},
				ids = {62558, 66533},
				notes = 'No focus effect | +5 hSTR, +5 hSTA, +5 hAGI, +5 hDEX',
			},
		},
		['Wizard'] = {
			['Head'] = 'Keeper\'s Ascendant Cap of the Arcanists/60465',
			['Chest'] = 'Keeper\'s Ascendant Robe of the Arcanists/60466',
			['Arms'] = 'Keeper\'s Ascendant Sleeves of the Arcanists/60467',
			['Wrist1'] = 'Keeper\'s Ascendant Wristband of the Arcanists/60468',
			['Hands'] = 'Keeper\'s Ascendant Gloves of the Arcanists/60469',
			['Legs'] = 'Keeper\'s Ascendant Pants of the Arcanists/60470',
			['Feet'] = 'Keeper\'s Ascendant Slippers of the Arcanists/60471',
			['Wrist2'] = 'Keeper\'s Eternal Bracer of the Arcanists/60472',
			['Ear1'] = 'Hoop of the Drakeborn/71574',
			['Ear2'] = 'Grelian Earring of Uncertainty/71603',
			['Face'] = 'Entrancing Silk Veil/71643',
			['Neck'] = 'Choker of One Hundred Diamonds/71651',
			['Back'] = 'Shroud of the Surging Storm/71656',
			['Shoulder'] = 'Brimstone Spaulders/71635',
			['Waist'] = 'Sash of Frigidity/71650',
			['Finger1'] = 'Thought Sieve Ring/71625',
			['Finger2'] = 'Stormeye Band/71658',
			['Ranged'] = 'Spark of the Skies/60536',
			['RangedAug'] = 'Core of the Skies/71659',
			['Clicky1'] = 'Icon of Ancient Boon/56758',
			['Clicky2'] = 'Icon of Scribe\'s Endurance/56756',
			['Clicky3'] = 'Icon of the Ancient Scribe/57143',
			['Shadow'] = 'Shadow of a Legendary Wizard Staff/60669',
			['Pack1'] = {
				item = 'Spell Pack: Bolster of the Sorcerer/82795',
				spells = {'Bolster of the Sorcerer'},
			},
			['Pack2'] = {
				item = 'Spell Pack: Supernal Skin/82796',
				spells = {'Supernal Skin'},
			},
			['Pack3'] = {
				item = 'Spell Pack: Ethereal Weave/82797',
				spells = {'Ethereal Weave'},
			},
			['Pack4'] = {
				item = 'Spell: Arcane Sanctuary/80763',
				spells = {'Arcane Sanctuary'},
				spell_ids = {15180},
			},
			['Pack5'] = {
				item = 'Spell: Eruption of Telakemara/80760',
				spells = {'Eruption of Telakemara'},
				spell_ids = {15167},
			},
			['Pack6'] = {
				item = 'Spell: Ether Blaze/79388',
				spells = {'Ether Blaze'},
				spell_ids = {11835},
			},
			['Pack7'] = {
				item = 'Spell: Evoker\'s Pyromantic Blade/80761',
				spells = {'Evoker\'s Pyromantic Blade'},
				spell_ids = {15168},
			},
			['Pack8'] = {
				item = 'Spell: Serenity Harvest/79129',
				spells = {'Serenity Harvest'},
				spell_ids = {10792},
			},
			['Pack9'] = {
				item = 'Spell: Wildmagic Salvo/79390',
				spells = {'Wildmagic Salvo'},
				spell_ids = {11840},
			},
			['Glyph1'] = 'Mnemonic Glyph: Bolster of the Sorceror/79521',
			['Glyph2'] = 'Mnemonic Glyph: Supernal Skin/79522',
			['Glyph3'] = 'Imbued Glyph: Ethereal Weave/79523',
			['Aug1'] = {
				item = 'Benevolent Extension',
				names = {'Benevolent Extension', 'Cryptic Clutch of Benevolent Extension', 'Vacant Vessel of Benevolent Extension'},
				ids = {62551, 63017},
				notes = '+40% beneficial spell duration | +10 hWIS',
			},
			['Aug2'] = {
				item = 'Malevolent Efficiency',
				names = {'Malevolent Efficiency', 'Cryptic Clutch of Malevolent Efficiency', 'Vacant Vessel of Malevolent Efficiency'},
				ids = {62540, 62560},
				notes = '-11–33% detrimental spell mana cost | +10 hINT',
			},
			['Aug3'] = {
				item = 'Malevolent Extension',
				names = {'Malevolent Extension', 'Cryptic Clutch of Malevolent Extension', 'Vacant Vessel of Malevolent Extension'},
				ids = {62550, 63016},
				notes = '+40% detrimental spell duration | +10 hINT',
			},
			['Aug4'] = {
				item = 'Malevolent Alacrity',
				names = {'Malevolent Alacrity', 'Cryptic Clutch of Malevolent Alacrity', 'Vacant Vessel of Malevolent Alacrity'},
				ids = {62542, 62562},
				notes = '-40% detrimental spell cast time | +10 hINT',
			},
			['Aug5'] = {
				item = 'Fiery Demise',
				names = {'Fiery Demise', 'Cryptic Clutch of Fiery Demise', 'Vacant Vessel of Fiery Demise'},
				ids = {62545, 62565},
				notes = '+10–60% fire spell damage | +5 hINT, +25 hFR',
			},
			['Aug6'] = {
				item = 'Arcane Demise',
				names = {'Arcane Demise', 'Cryptic Clutch of Arcane Demise', 'Vacant Vessel of Arcane Demise'},
				ids = {62544, 62564},
				notes = '+10–60% magic spell damage | +5 hINT, +25 hMR',
			},
			['Aug7'] = {
				item = 'Expanded Reach',
				names = {'Expanded Reach', 'Cryptic Clutch of Expanded Reach', 'Vacant Vessel of Expanded Reach'},
				ids = {62552, 63018},
				notes = '+50% spell range | +10 hWIS, +10 hINT',
			},
			['Aug8'] = {
				item = 'Nimble Elusion',
				names = {'Nimble Elusion', 'Cryptic Clutch of Nimble Elusion', 'Vacant Vessel of Nimble Elusion'},
				ids = {62556, 64050},
				notes = '+70% dodge | +10 hAGI',
			},
			['Aug9'] = {
				item = 'Mental Prowess',
				names = {'Mental Prowess', 'Cryptic Clutch of Mental Prowess', 'Vacant Vessel of Mental Prowess'},
				ids = {62559, 66720},
				notes = 'No focus effect | +10 hINT, +10 hWIS, +10 heroic resists',
			},
		},
		['Main'] = {
			['Slots'] = {
				{Name='Visibles', Slots={'Head','Chest','Arms','Wrist1','Hands','Legs','Feet','Wrist2',}},
				{Name='Non-Visibles', Slots={'Ear1','Ear2','Face','Neck','Back','Shoulder','Waist','Finger1','Finger2',}},
				{Name='Ranged + Charm', Slots={'Ranged','RangedAug','Duality','CharmExtreme','CharmSafe',}},
				{Name='Spells', Slots={'Pack1','Pack2','Pack3','Pack4','Pack5','Pack6','Pack7','Pack8','Pack9','Pack10',}},
				{Name='Clickies', Slots={'Clicky1','Clicky2','Clicky3',}},
				{Name='Glyphs', Slots={'Glyph1','Glyph2','Glyph3','Glyph4','Glyph5','Glyph6',}},
				{Name='Cryptic Clutch Foci Augs', Slots={'Aug1','Aug2','Aug3','Aug4','Aug5','Aug6','Aug7','Aug8','Aug9','Aug10','Aug11','Aug12',}},
				{Name='Shadow', Slots={'Materium1','Materium2','Materium3','Shadow',}},
				{Name='Misc', Slots={'Misc1','Misc2','Misc3','Misc4','Misc5',}},
			},
		},
		['Template'] = {
			['CharmExtreme'] = 'Lustrous Gem of Eternal Avarice/55054',
			['CharmSafe'] = 'Solemn Gem of Restrained Avarice/55055',
			['Duality'] = 'Duality of Desire/66903',
			['Materium1'] = 'Primary Materium of Legends/62535',
			['Materium2'] = 'Secondary Materium of Legends/62536',
			['Materium3'] = 'Tertiary Materium of Legends/62537',
			['Misc1'] = 'Dark Reign Elite Satchel/66731',
			['Misc2'] = 'Dark Reign Initiate Satchel/66732',
			['Misc3'] = 'Ancient Draconic Lockbox I/66733',
			['Misc4'] = 'Scales of the Lava Dragon/66904',
			['Misc5'] = 'Draconium Surveyor\'s Waystone/43224',
		},
	},
