-- Generate TurboGear's shipped built-in [TG] announce Tier-1 index.
-- Run from repo root:
--   luajit tools/generate_turbogear_builtin_announce_index.lua

package.path = "lua/turbogear/?.lua;lua/turbogear/?/init.lua;" .. package.path

package.preload["mq"] = function()
    local empty = setmetatable({}, {
        __call = function() return nil end,
        __index = function() return nil end,
    })
    return {
        TLO = {
            Me = {
                CleanName = function() return "Generator" end,
                Class = { Name = function() return "Warrior" end },
            },
            MacroQuest = { Server = function() return "Generator" end },
            EverQuest = { GameState = function() return "INGAME" end },
            FindItem = function() return empty end,
            FindItemBank = function() return empty end,
            Cursor = empty,
        },
        configDir = ".",
        pickle = function() end,
    }
end

package.preload["config"] = function()
    return {
        CFG = {},
        Settings = {},
        SharedSettings = { bisAnnounceDisabledLists = {} },
        SaveSettings = function() end,
        SaveSharedSettings = function() end,
        known_class = function(c)
            c = tostring(c or "")
            if c == "" or c == "?" then return nil end
            return c == "Shadowknight" and "Shadow Knight" or c
        end,
        canonical_class = function(c)
            c = tostring(c or "")
            if c == "" or c == "?" then return nil end
            return c == "Shadowknight" and "Shadow Knight" or c
        end,
    }
end

package.preload["diagnostics"] = function()
    return {
        time = function(_, fn) return fn() end,
        count = function() end,
        event = function() end,
        sample = function() end,
        context = function() end,
    }
end

local catalog = require("bis_catalog")
catalog.warm_catalog()
local payload, reason = catalog.generate_builtin_announce_index_payload()
if not payload then
    error("could not generate built-in announce index: " .. tostring(reason))
end

local function is_identifier_key(k)
    return type(k) == "string" and k:match("^[A-Za-z_][A-Za-z0-9_]*$") ~= nil
end

local function sorted_keys(t)
    local keys = {}
    for k in pairs(t or {}) do keys[#keys + 1] = k end
    table.sort(keys, function(a, b)
        if type(a) == type(b) then return tostring(a) < tostring(b) end
        return type(a) < type(b)
    end)
    return keys
end

local function serialize(v, indent)
    indent = indent or ""
    local tv = type(v)
    if tv == "nil" then return "nil" end
    if tv == "number" or tv == "boolean" then return tostring(v) end
    if tv == "string" then return string.format("%q", v) end
    if tv ~= "table" then error("cannot serialize " .. tv) end
    local parts = { "{\n" }
    local child = indent .. "    "
    local array_n = #v
    for i = 1, array_n do
        parts[#parts + 1] = child .. serialize(v[i], child) .. ",\n"
    end
    for _, k in ipairs(sorted_keys(v)) do
        if not (type(k) == "number" and k >= 1 and k <= array_n and math.floor(k) == k) then
            local key
            if is_identifier_key(k) then
                key = tostring(k)
            else
                key = "[" .. serialize(k, child) .. "]"
            end
            parts[#parts + 1] = child .. key .. " = " .. serialize(v[k], child) .. ",\n"
        end
    end
    parts[#parts + 1] = indent .. "}"
    return table.concat(parts)
end

local out_path = "lua/turbogear/generated/builtin_announce_index.lua"
local tmp_path = out_path .. ".tmp"
os.execute('cmd /c if not exist "lua\\turbogear\\generated" mkdir "lua\\turbogear\\generated"')
local fh, err = io.open(tmp_path, "w")
if not fh then error(err or "open failed") end
fh:write("-- Generated by tools/generate_turbogear_builtin_announce_index.lua; do not edit by hand.\n")
fh:write("return ")
fh:write(serialize(payload))
fh:write("\n")
fh:close()
os.remove(out_path)
assert(os.rename(tmp_path, out_path))
io.write(string.format("generated %s locators=%s keys=%s\n",
    out_path, tostring(payload.locator_count), tostring(payload.key_count)))
